// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Managed Agents Environment API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.environment;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * Delete Environment 响应体。
 */
@JsonPropertyOrder({
  DeleteEnvironmentResponse.JSON_PROPERTY_ID,
  DeleteEnvironmentResponse.JSON_PROPERTY_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class DeleteEnvironmentResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private String type;

  public DeleteEnvironmentResponse() {
  }

  public DeleteEnvironmentResponse id(@javax.annotation.Nonnull String id) {

    this.id = id;
    return this;
  }

  /**
   * 被删除的 Environment ID。
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }

  public DeleteEnvironmentResponse type(@javax.annotation.Nonnull String type) {

    this.type = type;
    return this;
  }

  /**
   * 对象类型标识。
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteEnvironmentResponse deleteEnvironmentResponse = (DeleteEnvironmentResponse) o;
    return Objects.equals(this.id, deleteEnvironmentResponse.id) &&
        Objects.equals(this.type, deleteEnvironmentResponse.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteEnvironmentResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private DeleteEnvironmentResponse instance;

    public Builder() {
      this(new DeleteEnvironmentResponse());
    }

    protected Builder(DeleteEnvironmentResponse instance) {
      this.instance = instance;
    }

    public DeleteEnvironmentResponse.Builder id(String id) {
      this.instance.id = id;
      return this;
    }
    public DeleteEnvironmentResponse.Builder type(String type) {
      this.instance.type = type;
      return this;
    }


    /**
    * returns a built DeleteEnvironmentResponse instance.
    *
    * The builder is not reusable.
    */
    public DeleteEnvironmentResponse build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static DeleteEnvironmentResponse.Builder builder() {
    return new DeleteEnvironmentResponse.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public DeleteEnvironmentResponse.Builder toBuilder() {
    return new DeleteEnvironmentResponse.Builder()
      .id(getId())
      .type(getType());
  }


}
