// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Managed Agents Environment API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.environment;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * 启动时预装的依赖包。版本通过包管理器自身语义指定 (e.g. pip 用 &#x60;\&quot;pkg&#x3D;&#x3D;1.0.0\&quot;&#x60;；不指定版本则装最新)。
 */
@JsonPropertyOrder({
  PackagesConfig.JSON_PROPERTY_TYPE,
  PackagesConfig.JSON_PROPERTY_PIP,
  PackagesConfig.JSON_PROPERTY_APT,
  PackagesConfig.JSON_PROPERTY_NPM,
  PackagesConfig.JSON_PROPERTY_CARGO,
  PackagesConfig.JSON_PROPERTY_GEM,
  PackagesConfig.JSON_PROPERTY_GO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class PackagesConfig {
  /**
   * 固定 &#x60;\&quot;packages\&quot;&#x60;；标识这是 Packages 配置。
   */
  public enum TypeEnum {
    PACKAGES(String.valueOf("packages"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equalsIgnoreCase(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nullable
  private TypeEnum type;

  public static final String JSON_PROPERTY_PIP = "pip";
  @javax.annotation.Nullable
  private List<String> pip;

  public static final String JSON_PROPERTY_APT = "apt";
  @javax.annotation.Nullable
  private List<String> apt;

  public static final String JSON_PROPERTY_NPM = "npm";
  @javax.annotation.Nullable
  private List<String> npm;

  public static final String JSON_PROPERTY_CARGO = "cargo";
  @javax.annotation.Nullable
  private List<String> cargo;

  public static final String JSON_PROPERTY_GEM = "gem";
  @javax.annotation.Nullable
  private List<String> gem;

  public static final String JSON_PROPERTY_GO = "go";
  @javax.annotation.Nullable
  private List<String> go;

  public PackagesConfig() {
  }

  public PackagesConfig type(@javax.annotation.Nullable TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * 固定 &#x60;\&quot;packages\&quot;&#x60;；标识这是 Packages 配置。
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@javax.annotation.Nullable TypeEnum type) {
    this.type = type;
  }

  public PackagesConfig pip(@javax.annotation.Nullable List<String> pip) {

    this.pip = pip;
    return this;
  }

  public PackagesConfig addPipItem(String pipItem) {
    if (this.pip == null) {
      this.pip = new ArrayList<>();
    }
    this.pip.add(pipItem);
    return this;
  }

  /**
   * pip 依赖条目列表。
   * @return pip
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PIP, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<String> getPip() {
    return pip;
  }


  @JsonProperty(value = JSON_PROPERTY_PIP, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setPip(@javax.annotation.Nullable List<String> pip) {
    this.pip = pip;
  }

  public PackagesConfig apt(@javax.annotation.Nullable List<String> apt) {

    this.apt = apt;
    return this;
  }

  public PackagesConfig addAptItem(String aptItem) {
    if (this.apt == null) {
      this.apt = new ArrayList<>();
    }
    this.apt.add(aptItem);
    return this;
  }

  /**
   * apt 包名列表。
   * @return apt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APT, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<String> getApt() {
    return apt;
  }


  @JsonProperty(value = JSON_PROPERTY_APT, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setApt(@javax.annotation.Nullable List<String> apt) {
    this.apt = apt;
  }

  public PackagesConfig npm(@javax.annotation.Nullable List<String> npm) {

    this.npm = npm;
    return this;
  }

  public PackagesConfig addNpmItem(String npmItem) {
    if (this.npm == null) {
      this.npm = new ArrayList<>();
    }
    this.npm.add(npmItem);
    return this;
  }

  /**
   * npm 包名列表。
   * @return npm
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NPM, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<String> getNpm() {
    return npm;
  }


  @JsonProperty(value = JSON_PROPERTY_NPM, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setNpm(@javax.annotation.Nullable List<String> npm) {
    this.npm = npm;
  }

  public PackagesConfig cargo(@javax.annotation.Nullable List<String> cargo) {

    this.cargo = cargo;
    return this;
  }

  public PackagesConfig addCargoItem(String cargoItem) {
    if (this.cargo == null) {
      this.cargo = new ArrayList<>();
    }
    this.cargo.add(cargoItem);
    return this;
  }

  /**
   * cargo crate 名列表。
   * @return cargo
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CARGO, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<String> getCargo() {
    return cargo;
  }


  @JsonProperty(value = JSON_PROPERTY_CARGO, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setCargo(@javax.annotation.Nullable List<String> cargo) {
    this.cargo = cargo;
  }

  public PackagesConfig gem(@javax.annotation.Nullable List<String> gem) {

    this.gem = gem;
    return this;
  }

  public PackagesConfig addGemItem(String gemItem) {
    if (this.gem == null) {
      this.gem = new ArrayList<>();
    }
    this.gem.add(gemItem);
    return this;
  }

  /**
   * RubyGems gem 名列表。
   * @return gem
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GEM, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<String> getGem() {
    return gem;
  }


  @JsonProperty(value = JSON_PROPERTY_GEM, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setGem(@javax.annotation.Nullable List<String> gem) {
    this.gem = gem;
  }

  public PackagesConfig go(@javax.annotation.Nullable List<String> go) {

    this.go = go;
    return this;
  }

  public PackagesConfig addGoItem(String goItem) {
    if (this.go == null) {
      this.go = new ArrayList<>();
    }
    this.go.add(goItem);
    return this;
  }

  /**
   * go module import 路径列表。
   * @return go
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GO, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<String> getGo() {
    return go;
  }


  @JsonProperty(value = JSON_PROPERTY_GO, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setGo(@javax.annotation.Nullable List<String> go) {
    this.go = go;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackagesConfig packagesConfig = (PackagesConfig) o;
    return Objects.equals(this.type, packagesConfig.type) &&
        Objects.equals(this.pip, packagesConfig.pip) &&
        Objects.equals(this.apt, packagesConfig.apt) &&
        Objects.equals(this.npm, packagesConfig.npm) &&
        Objects.equals(this.cargo, packagesConfig.cargo) &&
        Objects.equals(this.gem, packagesConfig.gem) &&
        Objects.equals(this.go, packagesConfig.go);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, pip, apt, npm, cargo, gem, go);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackagesConfig {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    pip: ").append(toIndentedString(pip)).append("\n");
    sb.append("    apt: ").append(toIndentedString(apt)).append("\n");
    sb.append("    npm: ").append(toIndentedString(npm)).append("\n");
    sb.append("    cargo: ").append(toIndentedString(cargo)).append("\n");
    sb.append("    gem: ").append(toIndentedString(gem)).append("\n");
    sb.append("    go: ").append(toIndentedString(go)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private PackagesConfig instance;

    public Builder() {
      this(new PackagesConfig());
    }

    protected Builder(PackagesConfig instance) {
      this.instance = instance;
    }

    public PackagesConfig.Builder type(TypeEnum type) {
      this.instance.type = type;
      return this;
    }
    public PackagesConfig.Builder pip(List<String> pip) {
      this.instance.pip = pip;
      return this;
    }
    public PackagesConfig.Builder apt(List<String> apt) {
      this.instance.apt = apt;
      return this;
    }
    public PackagesConfig.Builder npm(List<String> npm) {
      this.instance.npm = npm;
      return this;
    }
    public PackagesConfig.Builder cargo(List<String> cargo) {
      this.instance.cargo = cargo;
      return this;
    }
    public PackagesConfig.Builder gem(List<String> gem) {
      this.instance.gem = gem;
      return this;
    }
    public PackagesConfig.Builder go(List<String> go) {
      this.instance.go = go;
      return this;
    }


    /**
    * returns a built PackagesConfig instance.
    *
    * The builder is not reusable.
    */
    public PackagesConfig build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static PackagesConfig.Builder builder() {
    return new PackagesConfig.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public PackagesConfig.Builder toBuilder() {
    return new PackagesConfig.Builder()
      .type(getType())
      .pip(getPip())
      .apt(getApt())
      .npm(getNpm())
      .cargo(getCargo())
      .gem(getGem())
      .go(getGo());
  }


}
