// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Managed Agents Memory API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.memory;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * List MemoryStores 响应体。
 */
@JsonPropertyOrder({
  ListMemoryStoresResponse.JSON_PROPERTY_DATA,
  ListMemoryStoresResponse.JSON_PROPERTY_NEXT_PAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ListMemoryStoresResponse {
  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nonnull
  private List<MemoryStore> data;

  public static final String JSON_PROPERTY_NEXT_PAGE = "next_page";
  @javax.annotation.Nullable
  private String nextPage;

  public ListMemoryStoresResponse() {
  }

  public ListMemoryStoresResponse data(@javax.annotation.Nonnull List<MemoryStore> data) {
    
    this.data = data;
    return this;
  }

  public ListMemoryStoresResponse addDataItem(MemoryStore dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * 本页 MemoryStore 列表。
   * @return data
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<MemoryStore> getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(@javax.annotation.Nonnull List<MemoryStore> data) {
    this.data = data;
  }

  public ListMemoryStoresResponse nextPage(@javax.annotation.Nullable String nextPage) {
    
    this.nextPage = nextPage;
    return this;
  }

  /**
   * 下一页 cursor；已列尽时为空或缺省。
   * @return nextPage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NEXT_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextPage() {
    return nextPage;
  }


  @JsonProperty(value = JSON_PROPERTY_NEXT_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextPage(@javax.annotation.Nullable String nextPage) {
    this.nextPage = nextPage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListMemoryStoresResponse listMemoryStoresResponse = (ListMemoryStoresResponse) o;
    return Objects.equals(this.data, listMemoryStoresResponse.data) &&
        Objects.equals(this.nextPage, listMemoryStoresResponse.nextPage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, nextPage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListMemoryStoresResponse {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    nextPage: ").append(toIndentedString(nextPage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ListMemoryStoresResponse instance;

    public Builder() {
      this(new ListMemoryStoresResponse());
    }

    protected Builder(ListMemoryStoresResponse instance) {
      this.instance = instance;
    }

    public ListMemoryStoresResponse.Builder data(List<MemoryStore> data) {
      this.instance.data = data;
      return this;
    }
    public ListMemoryStoresResponse.Builder nextPage(String nextPage) {
      this.instance.nextPage = nextPage;
      return this;
    }


    /**
    * returns a built ListMemoryStoresResponse instance.
    *
    * The builder is not reusable.
    */
    public ListMemoryStoresResponse build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ListMemoryStoresResponse.Builder builder() {
    return new ListMemoryStoresResponse.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ListMemoryStoresResponse.Builder toBuilder() {
    return new ListMemoryStoresResponse.Builder()
      .data(getData())
      .nextPage(getNextPage());
  }


}

