// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Managed Agents Vault API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.vault;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * ValidateRequest
 */
@JsonPropertyOrder({
  ValidateRequest.JSON_PROPERTY_VAULT_ID,
  ValidateRequest.JSON_PROPERTY_CREDENTIAL_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ValidateRequest {
  public static final String JSON_PROPERTY_VAULT_ID = "vaultId";
  @javax.annotation.Nonnull
  private String vaultId;

  public static final String JSON_PROPERTY_CREDENTIAL_ID = "credentialId";
  @javax.annotation.Nonnull
  private String credentialId;

  public ValidateRequest() {
  }

  public ValidateRequest vaultId(@javax.annotation.Nonnull String vaultId) {

    this.vaultId = vaultId;
    return this;
  }

  /**
   * Get vaultId
   * @return vaultId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VAULT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getVaultId() {
    return vaultId;
  }


  @JsonProperty(value = JSON_PROPERTY_VAULT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVaultId(@javax.annotation.Nonnull String vaultId) {
    this.vaultId = vaultId;
  }

  public ValidateRequest credentialId(@javax.annotation.Nonnull String credentialId) {

    this.credentialId = credentialId;
    return this;
  }

  /**
   * Get credentialId
   * @return credentialId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREDENTIAL_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCredentialId() {
    return credentialId;
  }


  @JsonProperty(value = JSON_PROPERTY_CREDENTIAL_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCredentialId(@javax.annotation.Nonnull String credentialId) {
    this.credentialId = credentialId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidateRequest validateRequest = (ValidateRequest) o;
    return Objects.equals(this.vaultId, validateRequest.vaultId) &&
        Objects.equals(this.credentialId, validateRequest.credentialId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vaultId, credentialId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidateRequest {\n");
    sb.append("    vaultId: ").append(toIndentedString(vaultId)).append("\n");
    sb.append("    credentialId: ").append(toIndentedString(credentialId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ValidateRequest instance;

    public Builder() {
      this(new ValidateRequest());
    }

    protected Builder(ValidateRequest instance) {
      this.instance = instance;
    }

    public ValidateRequest.Builder vaultId(String vaultId) {
      this.instance.vaultId = vaultId;
      return this;
    }
    public ValidateRequest.Builder credentialId(String credentialId) {
      this.instance.credentialId = credentialId;
      return this;
    }


    /**
    * returns a built ValidateRequest instance.
    *
    * The builder is not reusable.
    */
    public ValidateRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ValidateRequest.Builder builder() {
    return new ValidateRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ValidateRequest.Builder toBuilder() {
    return new ValidateRequest.Builder()
      .vaultId(getVaultId())
      .credentialId(getCredentialId());
  }


}
