// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Tokenization API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.tokenization;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * TokenizationResponse
 */
@JsonPropertyOrder({
  TokenizationResponse.JSON_PROPERTY_ID,
  TokenizationResponse.JSON_PROPERTY_OBJECT,
  TokenizationResponse.JSON_PROPERTY_CREATED,
  TokenizationResponse.JSON_PROPERTY_MODEL,
  TokenizationResponse.JSON_PROPERTY_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class TokenizationResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  /**
   * The object type. Always &#x60;list&#x60;.
   */
  public enum ObjectEnum {
    LIST(String.valueOf("list"));

    private String value;

    ObjectEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ObjectEnum fromValue(String value) {
      for (ObjectEnum b : ObjectEnum.values()) {
        if (b.value.equalsIgnoreCase(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OBJECT = "object";
  @javax.annotation.Nonnull
  private ObjectEnum _object;

  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nonnull
  private Long created;

  public static final String JSON_PROPERTY_MODEL = "model";
  @javax.annotation.Nonnull
  private String model;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nonnull
  private List<TokenizationItem> data;

  public TokenizationResponse() {
  }

  public TokenizationResponse id(@javax.annotation.Nonnull String id) {

    this.id = id;
    return this;
  }

  /**
   * A unique identifier for the tokenization response.
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }

  public TokenizationResponse _object(@javax.annotation.Nonnull ObjectEnum _object) {

    this._object = _object;
    return this;
  }

  /**
   * The object type. Always &#x60;list&#x60;.
   * @return _object
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ObjectEnum getObject() {
    return _object;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObject(@javax.annotation.Nonnull ObjectEnum _object) {
    this._object = _object;
  }

  public TokenizationResponse created(@javax.annotation.Nonnull Long created) {

    this.created = created;
    return this;
  }

  /**
   * Unix timestamp (in seconds) of when the response was created.
   * @return created
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getCreated() {
    return created;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreated(@javax.annotation.Nonnull Long created) {
    this.created = created;
  }

  public TokenizationResponse model(@javax.annotation.Nonnull String model) {

    this.model = model;
    return this;
  }

  /**
   * The model that produced the tokenization.
   * @return model
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getModel() {
    return model;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModel(@javax.annotation.Nonnull String model) {
    this.model = model;
  }

  public TokenizationResponse data(@javax.annotation.Nonnull List<TokenizationItem> data) {

    this.data = data;
    return this;
  }

  public TokenizationResponse addDataItem(TokenizationItem dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * The list of tokenization results, one per input.
   * @return data
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<TokenizationItem> getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(@javax.annotation.Nonnull List<TokenizationItem> data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokenizationResponse tokenizationResponse = (TokenizationResponse) o;
    return Objects.equals(this.id, tokenizationResponse.id) &&
        Objects.equals(this._object, tokenizationResponse._object) &&
        Objects.equals(this.created, tokenizationResponse.created) &&
        Objects.equals(this.model, tokenizationResponse.model) &&
        Objects.equals(this.data, tokenizationResponse.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, _object, created, model, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokenizationResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private TokenizationResponse instance;

    public Builder() {
      this(new TokenizationResponse());
    }

    protected Builder(TokenizationResponse instance) {
      this.instance = instance;
    }

    public TokenizationResponse.Builder id(String id) {
      this.instance.id = id;
      return this;
    }
    public TokenizationResponse.Builder _object(ObjectEnum _object) {
      this.instance._object = _object;
      return this;
    }
    public TokenizationResponse.Builder created(Long created) {
      this.instance.created = created;
      return this;
    }
    public TokenizationResponse.Builder model(String model) {
      this.instance.model = model;
      return this;
    }
    public TokenizationResponse.Builder data(List<TokenizationItem> data) {
      this.instance.data = data;
      return this;
    }


    /**
    * returns a built TokenizationResponse instance.
    *
    * The builder is not reusable.
    */
    public TokenizationResponse build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static TokenizationResponse.Builder builder() {
    return new TokenizationResponse.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public TokenizationResponse.Builder toBuilder() {
    return new TokenizationResponse.Builder()
      .id(getId())
      ._object(getObject())
      .created(getCreated())
      .model(getModel())
      .data(getData());
  }


}
