// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Managed Agents Session API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.session;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * 创建 Checkpoint 时冻结的用户可见 Session 配置。  &#x60;agent&#x60; / &#x60;environment&#x60; 反映创建瞬间的 wire 形态（分别与 Ark.Agent 的 Agent、Ark.Environment 的 Environment 同 shape），为保持本模块自足， 此处承载为 &#x60;Record&lt;unknown&gt;&#x60;。
 */
@JsonPropertyOrder({
  CheckpointSessionSnapshot.JSON_PROPERTY_AGENT,
  CheckpointSessionSnapshot.JSON_PROPERTY_ENVIRONMENT,
  CheckpointSessionSnapshot.JSON_PROPERTY_RESOURCES,
  CheckpointSessionSnapshot.JSON_PROPERTY_VAULT_IDS,
  CheckpointSessionSnapshot.JSON_PROPERTY_TITLE,
  CheckpointSessionSnapshot.JSON_PROPERTY_TAGS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class CheckpointSessionSnapshot {
  public static final String JSON_PROPERTY_AGENT = "agent";
  @javax.annotation.Nullable
  private Map<String, Object> agent;

  public static final String JSON_PROPERTY_ENVIRONMENT = "environment";
  @javax.annotation.Nullable
  private Map<String, Object> environment;

  public static final String JSON_PROPERTY_RESOURCES = "resources";
  @javax.annotation.Nullable
  private List<SessionResource> resources;

  public static final String JSON_PROPERTY_VAULT_IDS = "vault_ids";
  @javax.annotation.Nullable
  private List<String> vaultIds;

  public static final String JSON_PROPERTY_TITLE = "title";
  @javax.annotation.Nullable
  private String title;

  public static final String JSON_PROPERTY_TAGS = "tags";
  @javax.annotation.Nullable
  private List<Tag> tags;

  public CheckpointSessionSnapshot() {
  }

  public CheckpointSessionSnapshot agent(@javax.annotation.Nullable Map<String, Object> agent) {

    this.agent = agent;
    return this;
  }

  public CheckpointSessionSnapshot putAgentItem(String key, Object agentItem) {
    if (this.agent == null) {
      this.agent = new HashMap<>();
    }
    this.agent.put(key, agentItem);
    return this;
  }

  /**
   * 冻结的 Agent 快照。
   * @return agent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.NON_EMPTY)

  public Map<String, Object> getAgent() {
    return agent;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.NON_EMPTY)
  public void setAgent(@javax.annotation.Nullable Map<String, Object> agent) {
    this.agent = agent;
  }

  public CheckpointSessionSnapshot environment(@javax.annotation.Nullable Map<String, Object> environment) {

    this.environment = environment;
    return this;
  }

  public CheckpointSessionSnapshot putEnvironmentItem(String key, Object environmentItem) {
    if (this.environment == null) {
      this.environment = new HashMap<>();
    }
    this.environment.put(key, environmentItem);
    return this;
  }

  /**
   * 冻结的 Environment 快照。
   * @return environment
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENVIRONMENT, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.NON_EMPTY)

  public Map<String, Object> getEnvironment() {
    return environment;
  }


  @JsonProperty(value = JSON_PROPERTY_ENVIRONMENT, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.NON_EMPTY)
  public void setEnvironment(@javax.annotation.Nullable Map<String, Object> environment) {
    this.environment = environment;
  }

  public CheckpointSessionSnapshot resources(@javax.annotation.Nullable List<SessionResource> resources) {

    this.resources = resources;
    return this;
  }

  public CheckpointSessionSnapshot addResourcesItem(SessionResource resourcesItem) {
    if (this.resources == null) {
      this.resources = new ArrayList<>();
    }
    this.resources.add(resourcesItem);
    return this;
  }

  /**
   * 冻结的挂载资源列表。
   * @return resources
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESOURCES, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<SessionResource> getResources() {
    return resources;
  }


  @JsonProperty(value = JSON_PROPERTY_RESOURCES, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setResources(@javax.annotation.Nullable List<SessionResource> resources) {
    this.resources = resources;
  }

  public CheckpointSessionSnapshot vaultIds(@javax.annotation.Nullable List<String> vaultIds) {

    this.vaultIds = vaultIds;
    return this;
  }

  public CheckpointSessionSnapshot addVaultIdsItem(String vaultIdsItem) {
    if (this.vaultIds == null) {
      this.vaultIds = new ArrayList<>();
    }
    this.vaultIds.add(vaultIdsItem);
    return this;
  }

  /**
   * 冻结的可访问 Vault ID 列表。
   * @return vaultIds
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VAULT_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<String> getVaultIds() {
    return vaultIds;
  }


  @JsonProperty(value = JSON_PROPERTY_VAULT_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setVaultIds(@javax.annotation.Nullable List<String> vaultIds) {
    this.vaultIds = vaultIds;
  }

  public CheckpointSessionSnapshot title(@javax.annotation.Nullable String title) {

    this.title = title;
    return this;
  }

  /**
   * 冻结的会话标题。
   * @return title
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }

  public CheckpointSessionSnapshot tags(@javax.annotation.Nullable List<Tag> tags) {

    this.tags = tags;
    return this;
  }

  public CheckpointSessionSnapshot addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * 冻结的资源标签。
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<Tag> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setTags(@javax.annotation.Nullable List<Tag> tags) {
    this.tags = tags;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckpointSessionSnapshot checkpointSessionSnapshot = (CheckpointSessionSnapshot) o;
    return Objects.equals(this.agent, checkpointSessionSnapshot.agent) &&
        Objects.equals(this.environment, checkpointSessionSnapshot.environment) &&
        Objects.equals(this.resources, checkpointSessionSnapshot.resources) &&
        Objects.equals(this.vaultIds, checkpointSessionSnapshot.vaultIds) &&
        Objects.equals(this.title, checkpointSessionSnapshot.title) &&
        Objects.equals(this.tags, checkpointSessionSnapshot.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agent, environment, resources, vaultIds, title, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckpointSessionSnapshot {\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("    environment: ").append(toIndentedString(environment)).append("\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    vaultIds: ").append(toIndentedString(vaultIds)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private CheckpointSessionSnapshot instance;

    public Builder() {
      this(new CheckpointSessionSnapshot());
    }

    protected Builder(CheckpointSessionSnapshot instance) {
      this.instance = instance;
    }

    public CheckpointSessionSnapshot.Builder agent(Map<String, Object> agent) {
      this.instance.agent = agent;
      return this;
    }
    public CheckpointSessionSnapshot.Builder environment(Map<String, Object> environment) {
      this.instance.environment = environment;
      return this;
    }
    public CheckpointSessionSnapshot.Builder resources(List<SessionResource> resources) {
      this.instance.resources = resources;
      return this;
    }
    public CheckpointSessionSnapshot.Builder vaultIds(List<String> vaultIds) {
      this.instance.vaultIds = vaultIds;
      return this;
    }
    public CheckpointSessionSnapshot.Builder title(String title) {
      this.instance.title = title;
      return this;
    }
    public CheckpointSessionSnapshot.Builder tags(List<Tag> tags) {
      this.instance.tags = tags;
      return this;
    }


    /**
    * returns a built CheckpointSessionSnapshot instance.
    *
    * The builder is not reusable.
    */
    public CheckpointSessionSnapshot build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static CheckpointSessionSnapshot.Builder builder() {
    return new CheckpointSessionSnapshot.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public CheckpointSessionSnapshot.Builder toBuilder() {
    return new CheckpointSessionSnapshot.Builder()
      .agent(getAgent())
      .environment(getEnvironment())
      .resources(getResources())
      .vaultIds(getVaultIds())
      .title(getTitle())
      .tags(getTags());
  }


}
