// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Managed Agents Session API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.session;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * 跨账号 Checkpoint 恢复的目标账号侧配置。  是否提供分三种情况： - 同账号恢复：**必须省略**，携带返回 400； - 跨账号恢复但 Checkpoint 不含 customer TOS 数据（仅平台托管的 uploads/outputs/memory 等）：**必须省略**，携带返回 400，错误码 消息为 \&quot;checkpoint_restore_config is only allowed when the checkpoint contains customer TOS data\&quot;； - 跨账号恢复且 Checkpoint 包含 customer TOS 数据：**必填** &#x60;tos_bucket&#x60;，声明调用方已离线同步好快照的目标账号 TOS 桶； 省略返回 400。  快照源 prefix、region、mount_path、access 均从 Checkpoint 继承， 最终 Session 目标 key 由平台生成。
 */
@JsonPropertyOrder({
  CheckpointRestoreConfig.JSON_PROPERTY_TOS_BUCKET
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class CheckpointRestoreConfig {
  public static final String JSON_PROPERTY_TOS_BUCKET = "tos_bucket";
  @javax.annotation.Nonnull
  private String tosBucket;

  public CheckpointRestoreConfig() {
  }

  public CheckpointRestoreConfig tosBucket(@javax.annotation.Nonnull String tosBucket) {

    this.tosBucket = tosBucket;
    return this;
  }

  /**
   * 调用方已将 customer TOS 快照同步到的目标账号 TOS 桶。
   * @return tosBucket
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOS_BUCKET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTosBucket() {
    return tosBucket;
  }


  @JsonProperty(value = JSON_PROPERTY_TOS_BUCKET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTosBucket(@javax.annotation.Nonnull String tosBucket) {
    this.tosBucket = tosBucket;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckpointRestoreConfig checkpointRestoreConfig = (CheckpointRestoreConfig) o;
    return Objects.equals(this.tosBucket, checkpointRestoreConfig.tosBucket);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tosBucket);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckpointRestoreConfig {\n");
    sb.append("    tosBucket: ").append(toIndentedString(tosBucket)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private CheckpointRestoreConfig instance;

    public Builder() {
      this(new CheckpointRestoreConfig());
    }

    protected Builder(CheckpointRestoreConfig instance) {
      this.instance = instance;
    }

    public CheckpointRestoreConfig.Builder tosBucket(String tosBucket) {
      this.instance.tosBucket = tosBucket;
      return this;
    }


    /**
    * returns a built CheckpointRestoreConfig instance.
    *
    * The builder is not reusable.
    */
    public CheckpointRestoreConfig build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static CheckpointRestoreConfig.Builder builder() {
    return new CheckpointRestoreConfig.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public CheckpointRestoreConfig.Builder toBuilder() {
    return new CheckpointRestoreConfig.Builder()
      .tosBucket(getTosBucket());
  }


}
