// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Managed Agents Session API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.session;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * 发起一次已有 Session 的运行配置升级。  &#x60;agent&#x60; / &#x60;environment&#x60; / &#x60;vault_ids&#x60; 至少提供一个作为升级目标，全部省略 返回 400 &#x60;MissingUpgradeTarget&#x60;（只传 &#x60;initial_events&#x60; 不算升级目标）。 Session 必须处于 &#x60;idle&#x60; 且上一轮 turn 以 &#x60;end_turn&#x60; 收尾，否则返回 403 &#x60;SessionNotIdle&#x60; / &#x60;SessionNotEndTurn&#x60;；同一 Session 上一次升级尚未收敛时 返回 403 &#x60;UpgradeInProgress&#x60;。
 */
@JsonPropertyOrder({
  CreateSessionUpgradeRequest.JSON_PROPERTY_AGENT,
  CreateSessionUpgradeRequest.JSON_PROPERTY_ENVIRONMENT,
  CreateSessionUpgradeRequest.JSON_PROPERTY_VAULT_IDS,
  CreateSessionUpgradeRequest.JSON_PROPERTY_INITIAL_EVENTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class CreateSessionUpgradeRequest {
  public static final String JSON_PROPERTY_AGENT = "agent";
  @javax.annotation.Nullable
  private AgentWithUpgrades agent;

  public static final String JSON_PROPERTY_ENVIRONMENT = "environment";
  @javax.annotation.Nullable
  private EnvironmentWithUpgrades environment;

  public static final String JSON_PROPERTY_VAULT_IDS = "vault_ids";
  @javax.annotation.Nullable
  private List<String> vaultIds;

  public static final String JSON_PROPERTY_INITIAL_EVENTS = "initial_events";
  @javax.annotation.Nullable
  private List<ManagedAgentsEventParams> initialEvents;

  public CreateSessionUpgradeRequest() {
  }

  public CreateSessionUpgradeRequest agent(@javax.annotation.Nullable AgentWithUpgrades agent) {

    this.agent = agent;
    return this;
  }

  /**
   * 目标 Agent 运行配置。
   * @return agent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AgentWithUpgrades getAgent() {
    return agent;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgent(@javax.annotation.Nullable AgentWithUpgrades agent) {
    this.agent = agent;
  }

  public CreateSessionUpgradeRequest environment(@javax.annotation.Nullable EnvironmentWithUpgrades environment) {

    this.environment = environment;
    return this;
  }

  /**
   * 目标 Environment 运行配置。
   * @return environment
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENVIRONMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EnvironmentWithUpgrades getEnvironment() {
    return environment;
  }


  @JsonProperty(value = JSON_PROPERTY_ENVIRONMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnvironment(@javax.annotation.Nullable EnvironmentWithUpgrades environment) {
    this.environment = environment;
  }

  public CreateSessionUpgradeRequest vaultIds(@javax.annotation.Nullable List<String> vaultIds) {

    this.vaultIds = vaultIds;
    return this;
  }

  public CreateSessionUpgradeRequest addVaultIdsItem(String vaultIdsItem) {
    if (this.vaultIds == null) {
      this.vaultIds = new ArrayList<>();
    }
    this.vaultIds.add(vaultIdsItem);
    return this;
  }

  /**
   * Session 绑定的 Vault 列表。  只能用来**刷新已绑定 Vault 的内容**，不能改变绑定集合：传入集合必须与 当前 Session 的 &#x60;vault_ids&#x60; 相等（忽略顺序与重复），否则返回 403 &#x60;VaultMismatch&#x60;。显式传 &#x60;[]&#x60; 表示声明空集，仅当当前 Session 本身没有 Vault 绑定时通过 —— 因此省略与 &#x60;[]&#x60; 在 wire 上必须可区分，SDK 不能把 空数组优化成省略字段。
   * @return vaultIds
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VAULT_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<String> getVaultIds() {
    return vaultIds;
  }


  @JsonProperty(value = JSON_PROPERTY_VAULT_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setVaultIds(@javax.annotation.Nullable List<String> vaultIds) {
    this.vaultIds = vaultIds;
  }

  public CreateSessionUpgradeRequest initialEvents(@javax.annotation.Nullable List<ManagedAgentsEventParams> initialEvents) {

    this.initialEvents = initialEvents;
    return this;
  }

  public CreateSessionUpgradeRequest addInitialEventsItem(ManagedAgentsEventParams initialEventsItem) {
    if (this.initialEvents == null) {
      this.initialEvents = new ArrayList<>();
    }
    this.initialEvents.add(initialEventsItem);
    return this;
  }

  /**
   * 配置切换收敛后由服务端补投的事件。当前只接受**恰好一个** &#x60;user.message&#x60; 事件，且 content 为单个 text block、内容是 &#x60;/compact&#x60; 命令 XML；不满足 返回 400 &#x60;InvalidInitialEvents&#x60; / &#x60;InvalidCompactCommand&#x60;。省略或传 &#x60;[]&#x60; 表示本次不投递事件。
   * @return initialEvents
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INITIAL_EVENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<ManagedAgentsEventParams> getInitialEvents() {
    return initialEvents;
  }


  @JsonProperty(value = JSON_PROPERTY_INITIAL_EVENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setInitialEvents(@javax.annotation.Nullable List<ManagedAgentsEventParams> initialEvents) {
    this.initialEvents = initialEvents;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSessionUpgradeRequest createSessionUpgradeRequest = (CreateSessionUpgradeRequest) o;
    return Objects.equals(this.agent, createSessionUpgradeRequest.agent) &&
        Objects.equals(this.environment, createSessionUpgradeRequest.environment) &&
        Objects.equals(this.vaultIds, createSessionUpgradeRequest.vaultIds) &&
        Objects.equals(this.initialEvents, createSessionUpgradeRequest.initialEvents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agent, environment, vaultIds, initialEvents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSessionUpgradeRequest {\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("    environment: ").append(toIndentedString(environment)).append("\n");
    sb.append("    vaultIds: ").append(toIndentedString(vaultIds)).append("\n");
    sb.append("    initialEvents: ").append(toIndentedString(initialEvents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private CreateSessionUpgradeRequest instance;

    public Builder() {
      this(new CreateSessionUpgradeRequest());
    }

    protected Builder(CreateSessionUpgradeRequest instance) {
      this.instance = instance;
    }

    public CreateSessionUpgradeRequest.Builder agent(AgentWithUpgrades agent) {
      this.instance.agent = agent;
      return this;
    }
    public CreateSessionUpgradeRequest.Builder environment(EnvironmentWithUpgrades environment) {
      this.instance.environment = environment;
      return this;
    }
    public CreateSessionUpgradeRequest.Builder vaultIds(List<String> vaultIds) {
      this.instance.vaultIds = vaultIds;
      return this;
    }
    public CreateSessionUpgradeRequest.Builder initialEvents(List<ManagedAgentsEventParams> initialEvents) {
      this.instance.initialEvents = initialEvents;
      return this;
    }


    /**
    * returns a built CreateSessionUpgradeRequest instance.
    *
    * The builder is not reusable.
    */
    public CreateSessionUpgradeRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static CreateSessionUpgradeRequest.Builder builder() {
    return new CreateSessionUpgradeRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public CreateSessionUpgradeRequest.Builder toBuilder() {
    return new CreateSessionUpgradeRequest.Builder()
      .agent(getAgent())
      .environment(getEnvironment())
      .vaultIds(getVaultIds())
      .initialEvents(getInitialEvents());
  }


}
