// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Managed Agents Session API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.session;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * &#x60;POST /sessions/{session_id}/checkpoints&#x60; 响应体。
 */
@JsonPropertyOrder({
  CreateSessionCheckpointResponse.JSON_PROPERTY_CHECKPOINT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class CreateSessionCheckpointResponse {
  public static final String JSON_PROPERTY_CHECKPOINT = "checkpoint";
  @javax.annotation.Nonnull
  private SessionCheckpoint checkpoint;

  public CreateSessionCheckpointResponse() {
  }

  public CreateSessionCheckpointResponse checkpoint(@javax.annotation.Nonnull SessionCheckpoint checkpoint) {

    this.checkpoint = checkpoint;
    return this;
  }

  /**
   * 创建出的 Checkpoint。
   * @return checkpoint
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CHECKPOINT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SessionCheckpoint getCheckpoint() {
    return checkpoint;
  }


  @JsonProperty(value = JSON_PROPERTY_CHECKPOINT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCheckpoint(@javax.annotation.Nonnull SessionCheckpoint checkpoint) {
    this.checkpoint = checkpoint;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSessionCheckpointResponse createSessionCheckpointResponse = (CreateSessionCheckpointResponse) o;
    return Objects.equals(this.checkpoint, createSessionCheckpointResponse.checkpoint);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkpoint);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSessionCheckpointResponse {\n");
    sb.append("    checkpoint: ").append(toIndentedString(checkpoint)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private CreateSessionCheckpointResponse instance;

    public Builder() {
      this(new CreateSessionCheckpointResponse());
    }

    protected Builder(CreateSessionCheckpointResponse instance) {
      this.instance = instance;
    }

    public CreateSessionCheckpointResponse.Builder checkpoint(SessionCheckpoint checkpoint) {
      this.instance.checkpoint = checkpoint;
      return this;
    }


    /**
    * returns a built CreateSessionCheckpointResponse instance.
    *
    * The builder is not reusable.
    */
    public CreateSessionCheckpointResponse build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static CreateSessionCheckpointResponse.Builder builder() {
    return new CreateSessionCheckpointResponse.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public CreateSessionCheckpointResponse.Builder toBuilder() {
    return new CreateSessionCheckpointResponse.Builder()
      .checkpoint(getCheckpoint());
  }


}
