// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Managed Agents Session API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.session;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ListRequest
 */
@JsonPropertyOrder({
  ListRequest.JSON_PROPERTY_AGENT_ID,
  ListRequest.JSON_PROPERTY_AGENT_VERSION,
  ListRequest.JSON_PROPERTY_CREATED_AT_GT,
  ListRequest.JSON_PROPERTY_CREATED_AT_GTE,
  ListRequest.JSON_PROPERTY_CREATED_AT_LT,
  ListRequest.JSON_PROPERTY_CREATED_AT_LTE,
  ListRequest.JSON_PROPERTY_LIMIT,
  ListRequest.JSON_PROPERTY_MEMORY_STORE_ID,
  ListRequest.JSON_PROPERTY_ORDER,
  ListRequest.JSON_PROPERTY_PAGE,
  ListRequest.JSON_PROPERTY_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ListRequest {
  public static final String JSON_PROPERTY_AGENT_ID = "agent_id";
  @javax.annotation.Nullable
  private String agentId;

  public static final String JSON_PROPERTY_AGENT_VERSION = "agent_version";
  @javax.annotation.Nullable
  private Integer agentVersion;

  public static final String JSON_PROPERTY_CREATED_AT_GT = "created_at_gt";
  @javax.annotation.Nullable
  private String createdAtGt;

  public static final String JSON_PROPERTY_CREATED_AT_GTE = "created_at_gte";
  @javax.annotation.Nullable
  private String createdAtGte;

  public static final String JSON_PROPERTY_CREATED_AT_LT = "created_at_lt";
  @javax.annotation.Nullable
  private String createdAtLt;

  public static final String JSON_PROPERTY_CREATED_AT_LTE = "created_at_lte";
  @javax.annotation.Nullable
  private String createdAtLte;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @javax.annotation.Nullable
  private Integer limit;

  public static final String JSON_PROPERTY_MEMORY_STORE_ID = "memory_store_id";
  @javax.annotation.Nullable
  private String memoryStoreId;

  public static final String JSON_PROPERTY_ORDER = "order";
  @javax.annotation.Nullable
  private ListSessionsOrder order;

  public static final String JSON_PROPERTY_PAGE = "page";
  @javax.annotation.Nullable
  private String page;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private List<SessionStatus> status;

  public ListRequest() {
  }

  public ListRequest agentId(@javax.annotation.Nullable String agentId) {

    this.agentId = agentId;
    return this;
  }

  /**
   * 按 agent_id 精确过滤。
   * @return agentId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AGENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAgentId() {
    return agentId;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgentId(@javax.annotation.Nullable String agentId) {
    this.agentId = agentId;
  }

  public ListRequest agentVersion(@javax.annotation.Nullable Integer agentVersion) {

    this.agentVersion = agentVersion;
    return this;
  }

  /**
   * 按 agent_version 精确过滤（配合 agent_id）。
   * @return agentVersion
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AGENT_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAgentVersion() {
    return agentVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENT_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgentVersion(@javax.annotation.Nullable Integer agentVersion) {
    this.agentVersion = agentVersion;
  }

  public ListRequest createdAtGt(@javax.annotation.Nullable String createdAtGt) {

    this.createdAtGt = createdAtGt;
    return this;
  }

  /**
   * 创建时间下界（严格大于，RFC 3339）。
   * @return createdAtGt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT_GT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedAtGt() {
    return createdAtGt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT_GT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAtGt(@javax.annotation.Nullable String createdAtGt) {
    this.createdAtGt = createdAtGt;
  }

  public ListRequest createdAtGte(@javax.annotation.Nullable String createdAtGte) {

    this.createdAtGte = createdAtGte;
    return this;
  }

  /**
   * 创建时间下界（大于等于，RFC 3339）。
   * @return createdAtGte
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT_GTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedAtGte() {
    return createdAtGte;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT_GTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAtGte(@javax.annotation.Nullable String createdAtGte) {
    this.createdAtGte = createdAtGte;
  }

  public ListRequest createdAtLt(@javax.annotation.Nullable String createdAtLt) {

    this.createdAtLt = createdAtLt;
    return this;
  }

  /**
   * 创建时间上界（严格小于，RFC 3339）。
   * @return createdAtLt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT_LT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedAtLt() {
    return createdAtLt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT_LT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAtLt(@javax.annotation.Nullable String createdAtLt) {
    this.createdAtLt = createdAtLt;
  }

  public ListRequest createdAtLte(@javax.annotation.Nullable String createdAtLte) {

    this.createdAtLte = createdAtLte;
    return this;
  }

  /**
   * 创建时间上界（小于等于，RFC 3339）。
   * @return createdAtLte
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT_LTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreatedAtLte() {
    return createdAtLte;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT_LTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAtLte(@javax.annotation.Nullable String createdAtLte) {
    this.createdAtLte = createdAtLte;
  }

  public ListRequest limit(@javax.annotation.Nullable Integer limit) {

    this.limit = limit;
    return this;
  }

  /**
   * 单页最大条数。
   * @return limit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLimit() {
    return limit;
  }


  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLimit(@javax.annotation.Nullable Integer limit) {
    this.limit = limit;
  }

  public ListRequest memoryStoreId(@javax.annotation.Nullable String memoryStoreId) {

    this.memoryStoreId = memoryStoreId;
    return this;
  }

  /**
   * 按 memory_store_id 过滤（会话若挂载了此 store）。
   * @return memoryStoreId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEMORY_STORE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMemoryStoreId() {
    return memoryStoreId;
  }


  @JsonProperty(value = JSON_PROPERTY_MEMORY_STORE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemoryStoreId(@javax.annotation.Nullable String memoryStoreId) {
    this.memoryStoreId = memoryStoreId;
  }

  public ListRequest order(@javax.annotation.Nullable ListSessionsOrder order) {

    this.order = order;
    return this;
  }

  /**
   * 排序方向。
   * @return order
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ListSessionsOrder getOrder() {
    return order;
  }


  @JsonProperty(value = JSON_PROPERTY_ORDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrder(@javax.annotation.Nullable ListSessionsOrder order) {
    this.order = order;
  }

  public ListRequest page(@javax.annotation.Nullable String page) {

    this.page = page;
    return this;
  }

  /**
   * 下一页 cursor（opaque）；首次可留空。
   * @return page
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPage() {
    return page;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPage(@javax.annotation.Nullable String page) {
    this.page = page;
  }

  public ListRequest status(@javax.annotation.Nullable List<SessionStatus> status) {

    this.status = status;
    return this;
  }

  public ListRequest addStatusItem(SessionStatus statusItem) {
    if (this.status == null) {
      this.status = new ArrayList<>();
    }
    this.status.add(statusItem);
    return this;
  }

  /**
   * 状态过滤，可重复。
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<SessionStatus> getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setStatus(@javax.annotation.Nullable List<SessionStatus> status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListRequest listRequest = (ListRequest) o;
    return Objects.equals(this.agentId, listRequest.agentId) &&
        Objects.equals(this.agentVersion, listRequest.agentVersion) &&
        Objects.equals(this.createdAtGt, listRequest.createdAtGt) &&
        Objects.equals(this.createdAtGte, listRequest.createdAtGte) &&
        Objects.equals(this.createdAtLt, listRequest.createdAtLt) &&
        Objects.equals(this.createdAtLte, listRequest.createdAtLte) &&
        Objects.equals(this.limit, listRequest.limit) &&
        Objects.equals(this.memoryStoreId, listRequest.memoryStoreId) &&
        Objects.equals(this.order, listRequest.order) &&
        Objects.equals(this.page, listRequest.page) &&
        Objects.equals(this.status, listRequest.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agentId, agentVersion, createdAtGt, createdAtGte, createdAtLt, createdAtLte, limit, memoryStoreId, order, page, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListRequest {\n");
    sb.append("    agentId: ").append(toIndentedString(agentId)).append("\n");
    sb.append("    agentVersion: ").append(toIndentedString(agentVersion)).append("\n");
    sb.append("    createdAtGt: ").append(toIndentedString(createdAtGt)).append("\n");
    sb.append("    createdAtGte: ").append(toIndentedString(createdAtGte)).append("\n");
    sb.append("    createdAtLt: ").append(toIndentedString(createdAtLt)).append("\n");
    sb.append("    createdAtLte: ").append(toIndentedString(createdAtLte)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    memoryStoreId: ").append(toIndentedString(memoryStoreId)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ListRequest instance;

    public Builder() {
      this(new ListRequest());
    }

    protected Builder(ListRequest instance) {
      this.instance = instance;
    }

    public ListRequest.Builder agentId(String agentId) {
      this.instance.agentId = agentId;
      return this;
    }
    public ListRequest.Builder agentVersion(Integer agentVersion) {
      this.instance.agentVersion = agentVersion;
      return this;
    }
    public ListRequest.Builder createdAtGt(String createdAtGt) {
      this.instance.createdAtGt = createdAtGt;
      return this;
    }
    public ListRequest.Builder createdAtGte(String createdAtGte) {
      this.instance.createdAtGte = createdAtGte;
      return this;
    }
    public ListRequest.Builder createdAtLt(String createdAtLt) {
      this.instance.createdAtLt = createdAtLt;
      return this;
    }
    public ListRequest.Builder createdAtLte(String createdAtLte) {
      this.instance.createdAtLte = createdAtLte;
      return this;
    }
    public ListRequest.Builder limit(Integer limit) {
      this.instance.limit = limit;
      return this;
    }
    public ListRequest.Builder memoryStoreId(String memoryStoreId) {
      this.instance.memoryStoreId = memoryStoreId;
      return this;
    }
    public ListRequest.Builder order(ListSessionsOrder order) {
      this.instance.order = order;
      return this;
    }
    public ListRequest.Builder page(String page) {
      this.instance.page = page;
      return this;
    }
    public ListRequest.Builder status(List<SessionStatus> status) {
      this.instance.status = status;
      return this;
    }


    /**
    * returns a built ListRequest instance.
    *
    * The builder is not reusable.
    */
    public ListRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ListRequest.Builder builder() {
    return new ListRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ListRequest.Builder toBuilder() {
    return new ListRequest.Builder()
      .agentId(getAgentId())
      .agentVersion(getAgentVersion())
      .createdAtGt(getCreatedAtGt())
      .createdAtGte(getCreatedAtGte())
      .createdAtLt(getCreatedAtLt())
      .createdAtLte(getCreatedAtLte())
      .limit(getLimit())
      .memoryStoreId(getMemoryStoreId())
      .order(getOrder())
      .page(getPage())
      .status(getStatus());
  }


}
