// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Managed Agents Session API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.session;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * 会话流上的一个事件。&#x60;type&#x60; 是判别式，其余字段随 type 变化。SDK 层建议 把这个模型作为出流事件的公共 envelope；具体 variant 的 payload 可以在 消费侧按 &#x60;type&#x60; 再解构。&#x60;event_start&#x60; / &#x60;event_delta&#x60; 的强类型结构见 &#x60;ManagedAgentsStreamPreviewEvent&#x60;；这两种瞬时预览帧不携带 &#x60;id&#x60; / &#x60;processed_at&#x60;。
 */
@JsonPropertyOrder({
  ManagedAgentsSessionEvent.JSON_PROPERTY_TYPE,
  ManagedAgentsSessionEvent.JSON_PROPERTY_ID,
  ManagedAgentsSessionEvent.JSON_PROPERTY_PROCESSED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ManagedAgentsSessionEvent {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private String type;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_PROCESSED_AT = "processed_at";
  @javax.annotation.Nullable
  private String processedAt;

  public ManagedAgentsSessionEvent() {
  }

  public ManagedAgentsSessionEvent type(@javax.annotation.Nonnull String type) {
    
    this.type = type;
    return this;
  }

  /**
   * 事件类型判别式，例如 &#x60;agent.message&#x60; / &#x60;event_start&#x60; / &#x60;event_delta&#x60; / &#x60;session.status_idle&#x60;。
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }

  public ManagedAgentsSessionEvent id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * 事件 id（服务端在 ingest 阶段 stamp，形如 &#x60;sevt-&lt;ts&gt;-&lt;rand&gt;&#x60;）。
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public ManagedAgentsSessionEvent processedAt(@javax.annotation.Nullable String processedAt) {
    
    this.processedAt = processedAt;
    return this;
  }

  /**
   * 事件产生时间（RFC 3339）。
   * @return processedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROCESSED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProcessedAt() {
    return processedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_PROCESSED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessedAt(@javax.annotation.Nullable String processedAt) {
    this.processedAt = processedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManagedAgentsSessionEvent managedAgentsSessionEvent = (ManagedAgentsSessionEvent) o;
    return Objects.equals(this.type, managedAgentsSessionEvent.type) &&
        Objects.equals(this.id, managedAgentsSessionEvent.id) &&
        Objects.equals(this.processedAt, managedAgentsSessionEvent.processedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, id, processedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManagedAgentsSessionEvent {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    processedAt: ").append(toIndentedString(processedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ManagedAgentsSessionEvent instance;

    public Builder() {
      this(new ManagedAgentsSessionEvent());
    }

    protected Builder(ManagedAgentsSessionEvent instance) {
      this.instance = instance;
    }

    public ManagedAgentsSessionEvent.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public ManagedAgentsSessionEvent.Builder id(String id) {
      this.instance.id = id;
      return this;
    }
    public ManagedAgentsSessionEvent.Builder processedAt(String processedAt) {
      this.instance.processedAt = processedAt;
      return this;
    }


    /**
    * returns a built ManagedAgentsSessionEvent instance.
    *
    * The builder is not reusable.
    */
    public ManagedAgentsSessionEvent build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ManagedAgentsSessionEvent.Builder builder() {
    return new ManagedAgentsSessionEvent.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ManagedAgentsSessionEvent.Builder toBuilder() {
    return new ManagedAgentsSessionEvent.Builder()
      .type(getType())
      .id(getId())
      .processedAt(getProcessedAt());
  }


}

