// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Managed Agents Session API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.session;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * &#x60;system.message&#x60;：把 system 侧的显式消息插入到 turn 输入（用于 rubric 补充、外部 world state 灌注等场景）。&#x60;content&#x60; 是文本 block 列表。
 */
@JsonPropertyOrder({
  ManagedAgentsSystemMessageEventParams.JSON_PROPERTY_CONTENT,
  ManagedAgentsSystemMessageEventParams.JSON_PROPERTY_SESSION_ID,
  ManagedAgentsSystemMessageEventParams.JSON_PROPERTY_SESSION_THREAD_ID,
  ManagedAgentsSystemMessageEventParams.JSON_PROPERTY_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ManagedAgentsSystemMessageEventParams implements ManagedAgentsEventParams {
  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nullable
  private List<ManagedAgentsTextBlock> content;

  public static final String JSON_PROPERTY_SESSION_ID = "session_id";
  @javax.annotation.Nullable
  private String sessionId;

  public static final String JSON_PROPERTY_SESSION_THREAD_ID = "session_thread_id";
  @javax.annotation.Nullable
  private String sessionThreadId;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private ManagedAgentsEventParamsType type = ManagedAgentsEventParamsType.SYSTEM_MESSAGE;

  public ManagedAgentsSystemMessageEventParams() {
  }

  public ManagedAgentsSystemMessageEventParams content(@javax.annotation.Nullable List<ManagedAgentsTextBlock> content) {
    
    this.content = content;
    return this;
  }

  public ManagedAgentsSystemMessageEventParams addContentItem(ManagedAgentsTextBlock contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<>();
    }
    this.content.add(contentItem);
    return this;
  }

  /**
   * 消息 content：目前仅支持文本块。
   * @return content
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<ManagedAgentsTextBlock> getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setContent(@javax.annotation.Nullable List<ManagedAgentsTextBlock> content) {
    this.content = content;
  }

  public ManagedAgentsSystemMessageEventParams sessionId(@javax.annotation.Nullable String sessionId) {
    
    this.sessionId = sessionId;
    return this;
  }

  /**
   * 目标 session id；SDK 通常从 URL 路径推断，此字段可省。
   * @return sessionId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SESSION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSessionId() {
    return sessionId;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessionId(@javax.annotation.Nullable String sessionId) {
    this.sessionId = sessionId;
  }

  public ManagedAgentsSystemMessageEventParams sessionThreadId(@javax.annotation.Nullable String sessionThreadId) {
    
    this.sessionThreadId = sessionThreadId;
    return this;
  }

  /**
   * 目标 session_thread_id（可选）。
   * @return sessionThreadId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SESSION_THREAD_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSessionThreadId() {
    return sessionThreadId;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_THREAD_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessionThreadId(@javax.annotation.Nullable String sessionThreadId) {
    this.sessionThreadId = sessionThreadId;
  }

  public ManagedAgentsSystemMessageEventParams type(@javax.annotation.Nonnull ManagedAgentsEventParamsType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ManagedAgentsEventParamsType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull ManagedAgentsEventParamsType type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ManagedAgentsSystemMessageEventParams managedAgentsSystemMessageEventParams = (ManagedAgentsSystemMessageEventParams) o;
    return Objects.equals(this.content, managedAgentsSystemMessageEventParams.content) &&
        Objects.equals(this.sessionId, managedAgentsSystemMessageEventParams.sessionId) &&
        Objects.equals(this.sessionThreadId, managedAgentsSystemMessageEventParams.sessionThreadId) &&
        Objects.equals(this.type, managedAgentsSystemMessageEventParams.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, sessionId, sessionThreadId, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ManagedAgentsSystemMessageEventParams {\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    sessionThreadId: ").append(toIndentedString(sessionThreadId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ManagedAgentsSystemMessageEventParams instance;

    public Builder() {
      this(new ManagedAgentsSystemMessageEventParams());
    }

    protected Builder(ManagedAgentsSystemMessageEventParams instance) {
      this.instance = instance;
    }

    public ManagedAgentsSystemMessageEventParams.Builder content(List<ManagedAgentsTextBlock> content) {
      this.instance.content = content;
      return this;
    }
    public ManagedAgentsSystemMessageEventParams.Builder sessionId(String sessionId) {
      this.instance.sessionId = sessionId;
      return this;
    }
    public ManagedAgentsSystemMessageEventParams.Builder sessionThreadId(String sessionThreadId) {
      this.instance.sessionThreadId = sessionThreadId;
      return this;
    }
    public ManagedAgentsSystemMessageEventParams.Builder type(ManagedAgentsEventParamsType type) {
      this.instance.type = type;
      return this;
    }


    /**
    * returns a built ManagedAgentsSystemMessageEventParams instance.
    *
    * The builder is not reusable.
    */
    public ManagedAgentsSystemMessageEventParams build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ManagedAgentsSystemMessageEventParams.Builder builder() {
    return new ManagedAgentsSystemMessageEventParams.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ManagedAgentsSystemMessageEventParams.Builder toBuilder() {
    return new ManagedAgentsSystemMessageEventParams.Builder()
      .content(getContent())
      .sessionId(getSessionId())
      .sessionThreadId(getSessionThreadId())
      .type(getType());
  }


}

