// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Managed Agents Session API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.session;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * Session 创建期模型覆写使用的 token 限制。  **整体替换语义**：省略整个 &#x60;token_limits&#x60; 对象表示不覆写、继承快照值； 一旦提供对象，三个字段**全部必填**且为正整数（&gt;&#x3D; 1），服务端不会与 快照中的旧 limits 按字段合并——只传部分字段返回 400 &#x60;model.token_limits.&lt;field&gt;: required&#x60;。
 */
@JsonPropertyOrder({
  OverrideTokenLimits.JSON_PROPERTY_CONTEXT_WINDOW,
  OverrideTokenLimits.JSON_PROPERTY_MAX_INPUT_TOKEN_LENGTH,
  OverrideTokenLimits.JSON_PROPERTY_MAX_OUTPUT_TOKEN_LENGTH
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class OverrideTokenLimits {
  public static final String JSON_PROPERTY_CONTEXT_WINDOW = "context_window";
  @javax.annotation.Nonnull
  private Long contextWindow;

  public static final String JSON_PROPERTY_MAX_INPUT_TOKEN_LENGTH = "max_input_token_length";
  @javax.annotation.Nonnull
  private Long maxInputTokenLength;

  public static final String JSON_PROPERTY_MAX_OUTPUT_TOKEN_LENGTH = "max_output_token_length";
  @javax.annotation.Nonnull
  private Long maxOutputTokenLength;

  public OverrideTokenLimits() {
  }

  public OverrideTokenLimits contextWindow(@javax.annotation.Nonnull Long contextWindow) {

    this.contextWindow = contextWindow;
    return this;
  }

  /**
   * 模型上下文窗口；正整数。
   * minimum: 1
   * @return contextWindow
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTEXT_WINDOW, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getContextWindow() {
    return contextWindow;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTEXT_WINDOW, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContextWindow(@javax.annotation.Nonnull Long contextWindow) {
    this.contextWindow = contextWindow;
  }

  public OverrideTokenLimits maxInputTokenLength(@javax.annotation.Nonnull Long maxInputTokenLength) {

    this.maxInputTokenLength = maxInputTokenLength;
    return this;
  }

  /**
   * 最大输入 token 长度；正整数。
   * minimum: 1
   * @return maxInputTokenLength
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MAX_INPUT_TOKEN_LENGTH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getMaxInputTokenLength() {
    return maxInputTokenLength;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_INPUT_TOKEN_LENGTH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaxInputTokenLength(@javax.annotation.Nonnull Long maxInputTokenLength) {
    this.maxInputTokenLength = maxInputTokenLength;
  }

  public OverrideTokenLimits maxOutputTokenLength(@javax.annotation.Nonnull Long maxOutputTokenLength) {

    this.maxOutputTokenLength = maxOutputTokenLength;
    return this;
  }

  /**
   * 最大输出 token 长度；正整数。
   * minimum: 1
   * @return maxOutputTokenLength
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MAX_OUTPUT_TOKEN_LENGTH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getMaxOutputTokenLength() {
    return maxOutputTokenLength;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_OUTPUT_TOKEN_LENGTH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMaxOutputTokenLength(@javax.annotation.Nonnull Long maxOutputTokenLength) {
    this.maxOutputTokenLength = maxOutputTokenLength;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OverrideTokenLimits overrideTokenLimits = (OverrideTokenLimits) o;
    return Objects.equals(this.contextWindow, overrideTokenLimits.contextWindow) &&
        Objects.equals(this.maxInputTokenLength, overrideTokenLimits.maxInputTokenLength) &&
        Objects.equals(this.maxOutputTokenLength, overrideTokenLimits.maxOutputTokenLength);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contextWindow, maxInputTokenLength, maxOutputTokenLength);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OverrideTokenLimits {\n");
    sb.append("    contextWindow: ").append(toIndentedString(contextWindow)).append("\n");
    sb.append("    maxInputTokenLength: ").append(toIndentedString(maxInputTokenLength)).append("\n");
    sb.append("    maxOutputTokenLength: ").append(toIndentedString(maxOutputTokenLength)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private OverrideTokenLimits instance;

    public Builder() {
      this(new OverrideTokenLimits());
    }

    protected Builder(OverrideTokenLimits instance) {
      this.instance = instance;
    }

    public OverrideTokenLimits.Builder contextWindow(Long contextWindow) {
      this.instance.contextWindow = contextWindow;
      return this;
    }
    public OverrideTokenLimits.Builder maxInputTokenLength(Long maxInputTokenLength) {
      this.instance.maxInputTokenLength = maxInputTokenLength;
      return this;
    }
    public OverrideTokenLimits.Builder maxOutputTokenLength(Long maxOutputTokenLength) {
      this.instance.maxOutputTokenLength = maxOutputTokenLength;
      return this;
    }


    /**
    * returns a built OverrideTokenLimits instance.
    *
    * The builder is not reusable.
    */
    public OverrideTokenLimits build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static OverrideTokenLimits.Builder builder() {
    return new OverrideTokenLimits.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public OverrideTokenLimits.Builder toBuilder() {
    return new OverrideTokenLimits.Builder()
      .contextWindow(getContextWindow())
      .maxInputTokenLength(getMaxInputTokenLength())
      .maxOutputTokenLength(getMaxOutputTokenLength());
  }


}
