// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Managed Agents Session API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.session;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * 会话 token / 缓存用量。
 */
@JsonPropertyOrder({
  SessionUsage.JSON_PROPERTY_INPUT_TOKENS,
  SessionUsage.JSON_PROPERTY_OUTPUT_TOKENS,
  SessionUsage.JSON_PROPERTY_CACHE_READ_INPUT_TOKENS,
  SessionUsage.JSON_PROPERTY_CACHE_CREATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class SessionUsage {
  public static final String JSON_PROPERTY_INPUT_TOKENS = "input_tokens";
  @javax.annotation.Nonnull
  private Long inputTokens;

  public static final String JSON_PROPERTY_OUTPUT_TOKENS = "output_tokens";
  @javax.annotation.Nonnull
  private Long outputTokens;

  public static final String JSON_PROPERTY_CACHE_READ_INPUT_TOKENS = "cache_read_input_tokens";
  @javax.annotation.Nonnull
  private Long cacheReadInputTokens;

  public static final String JSON_PROPERTY_CACHE_CREATION = "cache_creation";
  @javax.annotation.Nullable
  private CacheCreation cacheCreation;

  public SessionUsage() {
  }

  public SessionUsage inputTokens(@javax.annotation.Nonnull Long inputTokens) {
    
    this.inputTokens = inputTokens;
    return this;
  }

  /**
   * 累计输入 token。
   * @return inputTokens
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INPUT_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getInputTokens() {
    return inputTokens;
  }


  @JsonProperty(value = JSON_PROPERTY_INPUT_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInputTokens(@javax.annotation.Nonnull Long inputTokens) {
    this.inputTokens = inputTokens;
  }

  public SessionUsage outputTokens(@javax.annotation.Nonnull Long outputTokens) {
    
    this.outputTokens = outputTokens;
    return this;
  }

  /**
   * 累计输出 token。
   * @return outputTokens
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTPUT_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getOutputTokens() {
    return outputTokens;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTPUT_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutputTokens(@javax.annotation.Nonnull Long outputTokens) {
    this.outputTokens = outputTokens;
  }

  public SessionUsage cacheReadInputTokens(@javax.annotation.Nonnull Long cacheReadInputTokens) {
    
    this.cacheReadInputTokens = cacheReadInputTokens;
    return this;
  }

  /**
   * 累计从缓存读取的输入 token。
   * @return cacheReadInputTokens
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CACHE_READ_INPUT_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getCacheReadInputTokens() {
    return cacheReadInputTokens;
  }


  @JsonProperty(value = JSON_PROPERTY_CACHE_READ_INPUT_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCacheReadInputTokens(@javax.annotation.Nonnull Long cacheReadInputTokens) {
    this.cacheReadInputTokens = cacheReadInputTokens;
  }

  public SessionUsage cacheCreation(@javax.annotation.Nullable CacheCreation cacheCreation) {
    
    this.cacheCreation = cacheCreation;
    return this;
  }

  /**
   * 缓存创建 token 明细。
   * @return cacheCreation
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CACHE_CREATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CacheCreation getCacheCreation() {
    return cacheCreation;
  }


  @JsonProperty(value = JSON_PROPERTY_CACHE_CREATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCacheCreation(@javax.annotation.Nullable CacheCreation cacheCreation) {
    this.cacheCreation = cacheCreation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionUsage sessionUsage = (SessionUsage) o;
    return Objects.equals(this.inputTokens, sessionUsage.inputTokens) &&
        Objects.equals(this.outputTokens, sessionUsage.outputTokens) &&
        Objects.equals(this.cacheReadInputTokens, sessionUsage.cacheReadInputTokens) &&
        Objects.equals(this.cacheCreation, sessionUsage.cacheCreation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inputTokens, outputTokens, cacheReadInputTokens, cacheCreation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionUsage {\n");
    sb.append("    inputTokens: ").append(toIndentedString(inputTokens)).append("\n");
    sb.append("    outputTokens: ").append(toIndentedString(outputTokens)).append("\n");
    sb.append("    cacheReadInputTokens: ").append(toIndentedString(cacheReadInputTokens)).append("\n");
    sb.append("    cacheCreation: ").append(toIndentedString(cacheCreation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private SessionUsage instance;

    public Builder() {
      this(new SessionUsage());
    }

    protected Builder(SessionUsage instance) {
      this.instance = instance;
    }

    public SessionUsage.Builder inputTokens(Long inputTokens) {
      this.instance.inputTokens = inputTokens;
      return this;
    }
    public SessionUsage.Builder outputTokens(Long outputTokens) {
      this.instance.outputTokens = outputTokens;
      return this;
    }
    public SessionUsage.Builder cacheReadInputTokens(Long cacheReadInputTokens) {
      this.instance.cacheReadInputTokens = cacheReadInputTokens;
      return this;
    }
    public SessionUsage.Builder cacheCreation(CacheCreation cacheCreation) {
      this.instance.cacheCreation = cacheCreation;
      return this;
    }


    /**
    * returns a built SessionUsage instance.
    *
    * The builder is not reusable.
    */
    public SessionUsage build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SessionUsage.Builder builder() {
    return new SessionUsage.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SessionUsage.Builder toBuilder() {
    return new SessionUsage.Builder()
      .inputTokens(getInputTokens())
      .outputTokens(getOutputTokens())
      .cacheReadInputTokens(getCacheReadInputTokens())
      .cacheCreation(getCacheCreation());
  }


}

