// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Image Generation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.images;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * ToolUsage
 */
@JsonPropertyOrder({
  ToolUsage.JSON_PROPERTY_WEB_SEARCH
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ToolUsage {
  public static final String JSON_PROPERTY_WEB_SEARCH = "web_search";
  @javax.annotation.Nullable
  private Long webSearch;

  public ToolUsage() {
  }

  public ToolUsage webSearch(@javax.annotation.Nullable Long webSearch) {

    this.webSearch = webSearch;
    return this;
  }

  /**
   * Number of web-search invocations consumed.
   * @return webSearch
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEB_SEARCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getWebSearch() {
    return webSearch;
  }


  @JsonProperty(value = JSON_PROPERTY_WEB_SEARCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebSearch(@javax.annotation.Nullable Long webSearch) {
    this.webSearch = webSearch;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ToolUsage toolUsage = (ToolUsage) o;
    return Objects.equals(this.webSearch, toolUsage.webSearch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(webSearch);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ToolUsage {\n");
    sb.append("    webSearch: ").append(toIndentedString(webSearch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ToolUsage instance;

    public Builder() {
      this(new ToolUsage());
    }

    protected Builder(ToolUsage instance) {
      this.instance = instance;
    }

    public ToolUsage.Builder webSearch(Long webSearch) {
      this.instance.webSearch = webSearch;
      return this;
    }


    /**
    * returns a built ToolUsage instance.
    *
    * The builder is not reusable.
    */
    public ToolUsage build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ToolUsage.Builder builder() {
    return new ToolUsage.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ToolUsage.Builder toBuilder() {
    return new ToolUsage.Builder()
      .webSearch(getWebSearch());
  }


}
