// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

package com.volcengine.ark.runtime.selfhosted;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import com.volcengine.ark.runtime.models.session.Base64ImageSource;
import com.volcengine.ark.runtime.models.session.ManagedAgentsEventParams;
import com.volcengine.ark.runtime.models.session.ManagedAgentsImageBlock;
import com.volcengine.ark.runtime.models.session.ManagedAgentsUserCustomToolResultEventParams;
import com.volcengine.ark.runtime.service.ArkService;
import org.junit.Test;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

public class ContentBlockTest {
    @Test
    public void toMapPreservesStructuredFields() {
        Map<String, Object> source = new LinkedHashMap<>();
        source.put("type", "base64");
        source.put("media_type", "image/png");
        source.put("data", "aW1hZ2U=");
        ContentBlock block = new ContentBlock();
        block.setType("image");
        block.setSource(source);
        block.setTitle("result");
        block.setContext("generated by MCP");

        Map<String, Object> value = block.toMap();

        assertEquals("image", value.get("type"));
        assertEquals(source, value.get("source"));
        assertEquals("result", value.get("title"));
        assertEquals("generated by MCP", value.get("context"));
    }

    @Test
    public void toMapPreservesRequiredEmptyText() {
        ContentBlock block = new ContentBlock("text", "");

        Map<String, Object> value = block.toMap();

        assertTrue(value.containsKey("text"));
        assertEquals("", value.get("text"));
    }

    @Test
    public void eventRoundTripAndGeneratedModelPreserveSource() {
        Map<String, Object> source = new LinkedHashMap<>();
        source.put("type", "base64");
        source.put("media_type", "image/png");
        source.put("data", "aW1hZ2U=");
        ContentBlock block = new ContentBlock();
        block.setType("image");
        block.setSource(source);
        Event event = Event.newUserCustomToolResultEvent(
                "call-1", Collections.singletonList(block), false, "");

        Event restored = Event.fromMap(event.toMap());
        assertEquals(source, restored.getContent().get(0).getSource());

        ManagedAgentsEventParams generated = ArkService.defaultObjectMapper().convertValue(
                restored.toMap(), ManagedAgentsEventParams.class);
        assertTrue(generated instanceof ManagedAgentsUserCustomToolResultEventParams);
        ManagedAgentsUserCustomToolResultEventParams result =
                (ManagedAgentsUserCustomToolResultEventParams) generated;
        assertTrue(result.getContent().get(0) instanceof ManagedAgentsImageBlock);
        ManagedAgentsImageBlock image = (ManagedAgentsImageBlock) result.getContent().get(0);
        assertTrue(image.getSource() instanceof Base64ImageSource);
        assertEquals("aW1hZ2U=", ((Base64ImageSource) image.getSource()).getData());
    }
}
