// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Messages API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * MessagesContextManagementClearToolUsesTrigger
 */
@JsonPropertyOrder({
  MessagesContextManagementClearToolUsesTrigger.JSON_PROPERTY_TYPE,
  MessagesContextManagementClearToolUsesTrigger.JSON_PROPERTY_VALUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class MessagesContextManagementClearToolUsesTrigger {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private String type;

  public static final String JSON_PROPERTY_VALUE = "value";
  @javax.annotation.Nullable
  private Integer value;

  public MessagesContextManagementClearToolUsesTrigger() {
  }

  public MessagesContextManagementClearToolUsesTrigger type(@javax.annotation.Nonnull String type) {

    this.type = type;
    return this;
  }

  /**
   * The trigger type. &#x60;tool_uses&#x60; and other values such as &#x60;input_tokens&#x60; are accepted.
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }

  public MessagesContextManagementClearToolUsesTrigger value(@javax.annotation.Nullable Integer value) {

    this.value = value;
    return this;
  }

  /**
   * For &#x60;tool_uses&#x60;, the server requires a value of at least 1. Other trigger types accept an omitted value or any uint32 value, including 0. This type-specific constraint is validated by the server.
   * @return value
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getValue() {
    return value;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(@javax.annotation.Nullable Integer value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessagesContextManagementClearToolUsesTrigger messagesContextManagementClearToolUsesTrigger = (MessagesContextManagementClearToolUsesTrigger) o;
    return Objects.equals(this.type, messagesContextManagementClearToolUsesTrigger.type) &&
        Objects.equals(this.value, messagesContextManagementClearToolUsesTrigger.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessagesContextManagementClearToolUsesTrigger {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private MessagesContextManagementClearToolUsesTrigger instance;

    public Builder() {
      this(new MessagesContextManagementClearToolUsesTrigger());
    }

    protected Builder(MessagesContextManagementClearToolUsesTrigger instance) {
      this.instance = instance;
    }

    public MessagesContextManagementClearToolUsesTrigger.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public MessagesContextManagementClearToolUsesTrigger.Builder value(Integer value) {
      this.instance.value = value;
      return this;
    }


    /**
    * returns a built MessagesContextManagementClearToolUsesTrigger instance.
    *
    * The builder is not reusable.
    */
    public MessagesContextManagementClearToolUsesTrigger build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static MessagesContextManagementClearToolUsesTrigger.Builder builder() {
    return new MessagesContextManagementClearToolUsesTrigger.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public MessagesContextManagementClearToolUsesTrigger.Builder toBuilder() {
    return new MessagesContextManagementClearToolUsesTrigger.Builder()
      .type(getType())
      .value(getValue());
  }


}
