// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Messages API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MessagesContextManagementClearToolUses
 */
@JsonPropertyOrder({
  MessagesContextManagementClearToolUses.JSON_PROPERTY_TYPE,
  MessagesContextManagementClearToolUses.JSON_PROPERTY_KEEP,
  MessagesContextManagementClearToolUses.JSON_PROPERTY_EXCLUDE_TOOLS,
  MessagesContextManagementClearToolUses.JSON_PROPERTY_CLEAR_TOOL_INPUTS,
  MessagesContextManagementClearToolUses.JSON_PROPERTY_TRIGGER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class MessagesContextManagementClearToolUses implements MessagesContextManagementEdit {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private MessagesContextManagementEditType type = MessagesContextManagementEditType.CLEAR_TOOL_USES;

  public static final String JSON_PROPERTY_KEEP = "keep";
  @javax.annotation.Nullable
  private MessagesContextManagementKeep keep;

  public static final String JSON_PROPERTY_EXCLUDE_TOOLS = "exclude_tools";
  @javax.annotation.Nullable
  private List<String> excludeTools;

  public static final String JSON_PROPERTY_CLEAR_TOOL_INPUTS = "clear_tool_inputs";
  @javax.annotation.Nullable
  private Boolean clearToolInputs;

  public static final String JSON_PROPERTY_TRIGGER = "trigger";
  @javax.annotation.Nullable
  private MessagesContextManagementClearToolUsesTrigger trigger;

  public MessagesContextManagementClearToolUses() {
  }

  public MessagesContextManagementClearToolUses type(@javax.annotation.Nonnull MessagesContextManagementEditType type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MessagesContextManagementEditType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull MessagesContextManagementEditType type) {
    this.type = type;
  }

  public MessagesContextManagementClearToolUses keep(@javax.annotation.Nullable MessagesContextManagementKeep keep) {

    this.keep = keep;
    return this;
  }

  /**
   * Get keep
   * @return keep
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KEEP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MessagesContextManagementKeep getKeep() {
    return keep;
  }


  @JsonProperty(value = JSON_PROPERTY_KEEP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeep(@javax.annotation.Nullable MessagesContextManagementKeep keep) {
    this.keep = keep;
  }

  public MessagesContextManagementClearToolUses excludeTools(@javax.annotation.Nullable List<String> excludeTools) {

    this.excludeTools = excludeTools;
    return this;
  }

  public MessagesContextManagementClearToolUses addExcludeToolsItem(String excludeToolsItem) {
    if (this.excludeTools == null) {
      this.excludeTools = new ArrayList<>();
    }
    this.excludeTools.add(excludeToolsItem);
    return this;
  }

  /**
   * Get excludeTools
   * @return excludeTools
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXCLUDE_TOOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<String> getExcludeTools() {
    return excludeTools;
  }


  @JsonProperty(value = JSON_PROPERTY_EXCLUDE_TOOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setExcludeTools(@javax.annotation.Nullable List<String> excludeTools) {
    this.excludeTools = excludeTools;
  }

  public MessagesContextManagementClearToolUses clearToolInputs(@javax.annotation.Nullable Boolean clearToolInputs) {

    this.clearToolInputs = clearToolInputs;
    return this;
  }

  /**
   * Get clearToolInputs
   * @return clearToolInputs
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLEAR_TOOL_INPUTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getClearToolInputs() {
    return clearToolInputs;
  }


  @JsonProperty(value = JSON_PROPERTY_CLEAR_TOOL_INPUTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClearToolInputs(@javax.annotation.Nullable Boolean clearToolInputs) {
    this.clearToolInputs = clearToolInputs;
  }

  public MessagesContextManagementClearToolUses trigger(@javax.annotation.Nullable MessagesContextManagementClearToolUsesTrigger trigger) {

    this.trigger = trigger;
    return this;
  }

  /**
   * Get trigger
   * @return trigger
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRIGGER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MessagesContextManagementClearToolUsesTrigger getTrigger() {
    return trigger;
  }


  @JsonProperty(value = JSON_PROPERTY_TRIGGER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrigger(@javax.annotation.Nullable MessagesContextManagementClearToolUsesTrigger trigger) {
    this.trigger = trigger;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessagesContextManagementClearToolUses messagesContextManagementClearToolUses = (MessagesContextManagementClearToolUses) o;
    return Objects.equals(this.type, messagesContextManagementClearToolUses.type) &&
        Objects.equals(this.keep, messagesContextManagementClearToolUses.keep) &&
        Objects.equals(this.excludeTools, messagesContextManagementClearToolUses.excludeTools) &&
        Objects.equals(this.clearToolInputs, messagesContextManagementClearToolUses.clearToolInputs) &&
        Objects.equals(this.trigger, messagesContextManagementClearToolUses.trigger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, keep, excludeTools, clearToolInputs, trigger);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessagesContextManagementClearToolUses {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    keep: ").append(toIndentedString(keep)).append("\n");
    sb.append("    excludeTools: ").append(toIndentedString(excludeTools)).append("\n");
    sb.append("    clearToolInputs: ").append(toIndentedString(clearToolInputs)).append("\n");
    sb.append("    trigger: ").append(toIndentedString(trigger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private MessagesContextManagementClearToolUses instance;

    public Builder() {
      this(new MessagesContextManagementClearToolUses());
    }

    protected Builder(MessagesContextManagementClearToolUses instance) {
      this.instance = instance;
    }

    public MessagesContextManagementClearToolUses.Builder type(MessagesContextManagementEditType type) {
      this.instance.type = type;
      return this;
    }
    public MessagesContextManagementClearToolUses.Builder keep(MessagesContextManagementKeep keep) {
      this.instance.keep = keep;
      return this;
    }
    public MessagesContextManagementClearToolUses.Builder excludeTools(List<String> excludeTools) {
      this.instance.excludeTools = excludeTools;
      return this;
    }
    public MessagesContextManagementClearToolUses.Builder clearToolInputs(Boolean clearToolInputs) {
      this.instance.clearToolInputs = clearToolInputs;
      return this;
    }
    public MessagesContextManagementClearToolUses.Builder trigger(MessagesContextManagementClearToolUsesTrigger trigger) {
      this.instance.trigger = trigger;
      return this;
    }


    /**
    * returns a built MessagesContextManagementClearToolUses instance.
    *
    * The builder is not reusable.
    */
    public MessagesContextManagementClearToolUses build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static MessagesContextManagementClearToolUses.Builder builder() {
    return new MessagesContextManagementClearToolUses.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public MessagesContextManagementClearToolUses.Builder toBuilder() {
    return new MessagesContextManagementClearToolUses.Builder()
      .type(getType())
      .keep(getKeep())
      .excludeTools(getExcludeTools())
      .clearToolInputs(getClearToolInputs())
      .trigger(getTrigger());
  }


}
