// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Messages API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * MessagesIterationUsage
 */
@JsonPropertyOrder({
  MessagesIterationUsage.JSON_PROPERTY_TYPE,
  MessagesIterationUsage.JSON_PROPERTY_INPUT_TOKENS,
  MessagesIterationUsage.JSON_PROPERTY_OUTPUT_TOKENS,
  MessagesIterationUsage.JSON_PROPERTY_CACHE_READ_INPUT_TOKENS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class MessagesIterationUsage {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private String type;

  public static final String JSON_PROPERTY_INPUT_TOKENS = "input_tokens";
  @javax.annotation.Nonnull
  private Integer inputTokens;

  public static final String JSON_PROPERTY_OUTPUT_TOKENS = "output_tokens";
  @javax.annotation.Nonnull
  private Integer outputTokens;

  public static final String JSON_PROPERTY_CACHE_READ_INPUT_TOKENS = "cache_read_input_tokens";
  @javax.annotation.Nonnull
  private Integer cacheReadInputTokens;

  public MessagesIterationUsage() {
  }

  public MessagesIterationUsage type(@javax.annotation.Nonnull String type) {

    this.type = type;
    return this;
  }

  /**
   * The iteration usage record type.
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }

  public MessagesIterationUsage inputTokens(@javax.annotation.Nonnull Integer inputTokens) {

    this.inputTokens = inputTokens;
    return this;
  }

  /**
   * Number of input tokens consumed by this model iteration.
   * @return inputTokens
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INPUT_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getInputTokens() {
    return inputTokens;
  }


  @JsonProperty(value = JSON_PROPERTY_INPUT_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInputTokens(@javax.annotation.Nonnull Integer inputTokens) {
    this.inputTokens = inputTokens;
  }

  public MessagesIterationUsage outputTokens(@javax.annotation.Nonnull Integer outputTokens) {

    this.outputTokens = outputTokens;
    return this;
  }

  /**
   * Number of output tokens generated by this model iteration.
   * @return outputTokens
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTPUT_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getOutputTokens() {
    return outputTokens;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTPUT_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutputTokens(@javax.annotation.Nonnull Integer outputTokens) {
    this.outputTokens = outputTokens;
  }

  public MessagesIterationUsage cacheReadInputTokens(@javax.annotation.Nonnull Integer cacheReadInputTokens) {

    this.cacheReadInputTokens = cacheReadInputTokens;
    return this;
  }

  /**
   * Number of cached input tokens read by this model iteration.
   * @return cacheReadInputTokens
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CACHE_READ_INPUT_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCacheReadInputTokens() {
    return cacheReadInputTokens;
  }


  @JsonProperty(value = JSON_PROPERTY_CACHE_READ_INPUT_TOKENS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCacheReadInputTokens(@javax.annotation.Nonnull Integer cacheReadInputTokens) {
    this.cacheReadInputTokens = cacheReadInputTokens;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessagesIterationUsage messagesIterationUsage = (MessagesIterationUsage) o;
    return Objects.equals(this.type, messagesIterationUsage.type) &&
        Objects.equals(this.inputTokens, messagesIterationUsage.inputTokens) &&
        Objects.equals(this.outputTokens, messagesIterationUsage.outputTokens) &&
        Objects.equals(this.cacheReadInputTokens, messagesIterationUsage.cacheReadInputTokens);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, inputTokens, outputTokens, cacheReadInputTokens);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessagesIterationUsage {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    inputTokens: ").append(toIndentedString(inputTokens)).append("\n");
    sb.append("    outputTokens: ").append(toIndentedString(outputTokens)).append("\n");
    sb.append("    cacheReadInputTokens: ").append(toIndentedString(cacheReadInputTokens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private MessagesIterationUsage instance;

    public Builder() {
      this(new MessagesIterationUsage());
    }

    protected Builder(MessagesIterationUsage instance) {
      this.instance = instance;
    }

    public MessagesIterationUsage.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public MessagesIterationUsage.Builder inputTokens(Integer inputTokens) {
      this.instance.inputTokens = inputTokens;
      return this;
    }
    public MessagesIterationUsage.Builder outputTokens(Integer outputTokens) {
      this.instance.outputTokens = outputTokens;
      return this;
    }
    public MessagesIterationUsage.Builder cacheReadInputTokens(Integer cacheReadInputTokens) {
      this.instance.cacheReadInputTokens = cacheReadInputTokens;
      return this;
    }


    /**
    * returns a built MessagesIterationUsage instance.
    *
    * The builder is not reusable.
    */
    public MessagesIterationUsage build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static MessagesIterationUsage.Builder builder() {
    return new MessagesIterationUsage.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public MessagesIterationUsage.Builder toBuilder() {
    return new MessagesIterationUsage.Builder()
      .type(getType())
      .inputTokens(getInputTokens())
      .outputTokens(getOutputTokens())
      .cacheReadInputTokens(getCacheReadInputTokens());
  }


}
