// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Messages API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * MessagesContentPartDocumentSourceUrl
 */
@JsonPropertyOrder({
  MessagesContentPartDocumentSourceUrl.JSON_PROPERTY_TYPE,
  MessagesContentPartDocumentSourceUrl.JSON_PROPERTY_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class MessagesContentPartDocumentSourceUrl implements MessagesContentPartDocumentSource {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private MessagesContentPartDocumentSourceType type = MessagesContentPartDocumentSourceType.URL;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nonnull
  private String url;

  public MessagesContentPartDocumentSourceUrl() {
  }

  public MessagesContentPartDocumentSourceUrl type(@javax.annotation.Nonnull MessagesContentPartDocumentSourceType type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MessagesContentPartDocumentSourceType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull MessagesContentPartDocumentSourceType type) {
    this.type = type;
  }

  public MessagesContentPartDocumentSourceUrl url(@javax.annotation.Nonnull String url) {

    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(@javax.annotation.Nonnull String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessagesContentPartDocumentSourceUrl messagesContentPartDocumentSourceUrl = (MessagesContentPartDocumentSourceUrl) o;
    return Objects.equals(this.type, messagesContentPartDocumentSourceUrl.type) &&
        Objects.equals(this.url, messagesContentPartDocumentSourceUrl.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessagesContentPartDocumentSourceUrl {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private MessagesContentPartDocumentSourceUrl instance;

    public Builder() {
      this(new MessagesContentPartDocumentSourceUrl());
    }

    protected Builder(MessagesContentPartDocumentSourceUrl instance) {
      this.instance = instance;
    }

    public MessagesContentPartDocumentSourceUrl.Builder type(MessagesContentPartDocumentSourceType type) {
      this.instance.type = type;
      return this;
    }
    public MessagesContentPartDocumentSourceUrl.Builder url(String url) {
      this.instance.url = url;
      return this;
    }


    /**
    * returns a built MessagesContentPartDocumentSourceUrl instance.
    *
    * The builder is not reusable.
    */
    public MessagesContentPartDocumentSourceUrl build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static MessagesContentPartDocumentSourceUrl.Builder builder() {
    return new MessagesContentPartDocumentSourceUrl.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public MessagesContentPartDocumentSourceUrl.Builder toBuilder() {
    return new MessagesContentPartDocumentSourceUrl.Builder()
      .type(getType())
      .url(getUrl());
  }


}
