// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Messages API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.volcengine.ark.runtime.models.messages;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.io.IOException;
import java.util.Objects;

/**
 * MessagesContextManagementKeep
 *
 * Naked-union holder generated by gen/java/postprocess.py from the openapi
 * anyOf schema (variants: String, MessagesContextManagementKeepParameter).
 *
 * The Jackson apache-httpclient template openapi-generator runs against
 * does not support non-discriminated anyOf/oneOf — it either drops to a
 * degenerate empty shell or flattens one variant's fields onto the class,
 * losing the others. This postprocess rewrite replaces the parent with a
 * @JsonValue holder + typed static factories for write-side, plus a custom
 * @JsonDeserialize that dispatches by JsonNode shape on the read-side so
 * round-trips preserve variant types (string -> typed primitive/enum,
 * object -> typed model, array -> typed List).
 */
@JsonDeserialize(using = MessagesContextManagementKeep.Deserializer.class)
public class MessagesContextManagementKeep {

  private final Object value;

  @JsonCreator
  public MessagesContextManagementKeep(Object value) {
    this.value = value;
  }

  public MessagesContextManagementKeep() {
    this.value = null;
  }

  public static MessagesContextManagementKeep ofString(String value) {
    return new MessagesContextManagementKeep(value);
  }

  public static MessagesContextManagementKeep ofMessagesContextManagementKeepParameter(MessagesContextManagementKeepParameter value) {
    return new MessagesContextManagementKeep(value);
  }

  @JsonValue
  public Object getValue() {
    return this.value;
  }

  public static class Deserializer extends JsonDeserializer<MessagesContextManagementKeep> {
    @Override
    public MessagesContextManagementKeep deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
      ObjectMapper mapper = (ObjectMapper) p.getCodec();
      JsonNode node = mapper.readTree(p);
      if (node.isTextual()) {
        return new MessagesContextManagementKeep(mapper.treeToValue(node, String.class));
      }
      if (node.isObject()) {
        return new MessagesContextManagementKeep(mapper.treeToValue(node, MessagesContextManagementKeepParameter.class));
      }
      throw ctxt.weirdStringException(
          node == null ? "null" : node.toString(),
          MessagesContextManagementKeep.class,
          "no MessagesContextManagementKeep variant matched JSON node shape");
    }
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    MessagesContextManagementKeep other = (MessagesContextManagementKeep) o;
    return Objects.equals(this.value, other.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.value);
  }

  @Override
  public String toString() {
    return "class MessagesContextManagementKeep {" + Objects.toString(value) + "}";
  }

  public static class Builder {
    private Object value;
    public Builder() {}
    public Builder value(Object value) { this.value = value; return this; }
    public MessagesContextManagementKeep build() { return new MessagesContextManagementKeep(this.value); }
  }

  public static MessagesContextManagementKeep.Builder builder() { return new MessagesContextManagementKeep.Builder(); }

  public MessagesContextManagementKeep.Builder toBuilder() {
    return new MessagesContextManagementKeep.Builder().value(this.value);
  }
}
