// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Messages API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * MessagesResponseContentBlockDeltaThinking
 */
@JsonPropertyOrder({
  MessagesResponseContentBlockDeltaThinking.JSON_PROPERTY_TYPE,
  MessagesResponseContentBlockDeltaThinking.JSON_PROPERTY_THINKING
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class MessagesResponseContentBlockDeltaThinking implements MessagesResponseContentBlockDelta {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private MessagesResponseContentBlockDeltaType type = MessagesResponseContentBlockDeltaType.THINKING_DELTA;

  public static final String JSON_PROPERTY_THINKING = "thinking";
  @javax.annotation.Nonnull
  private String thinking;

  public MessagesResponseContentBlockDeltaThinking() {
  }

  public MessagesResponseContentBlockDeltaThinking type(@javax.annotation.Nonnull MessagesResponseContentBlockDeltaType type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MessagesResponseContentBlockDeltaType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull MessagesResponseContentBlockDeltaType type) {
    this.type = type;
  }

  public MessagesResponseContentBlockDeltaThinking thinking(@javax.annotation.Nonnull String thinking) {

    this.thinking = thinking;
    return this;
  }

  /**
   * Get thinking
   * @return thinking
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_THINKING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getThinking() {
    return thinking;
  }


  @JsonProperty(value = JSON_PROPERTY_THINKING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setThinking(@javax.annotation.Nonnull String thinking) {
    this.thinking = thinking;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessagesResponseContentBlockDeltaThinking messagesResponseContentBlockDeltaThinking = (MessagesResponseContentBlockDeltaThinking) o;
    return Objects.equals(this.type, messagesResponseContentBlockDeltaThinking.type) &&
        Objects.equals(this.thinking, messagesResponseContentBlockDeltaThinking.thinking);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, thinking);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessagesResponseContentBlockDeltaThinking {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    thinking: ").append(toIndentedString(thinking)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private MessagesResponseContentBlockDeltaThinking instance;

    public Builder() {
      this(new MessagesResponseContentBlockDeltaThinking());
    }

    protected Builder(MessagesResponseContentBlockDeltaThinking instance) {
      this.instance = instance;
    }

    public MessagesResponseContentBlockDeltaThinking.Builder type(MessagesResponseContentBlockDeltaType type) {
      this.instance.type = type;
      return this;
    }
    public MessagesResponseContentBlockDeltaThinking.Builder thinking(String thinking) {
      this.instance.thinking = thinking;
      return this;
    }


    /**
    * returns a built MessagesResponseContentBlockDeltaThinking instance.
    *
    * The builder is not reusable.
    */
    public MessagesResponseContentBlockDeltaThinking build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static MessagesResponseContentBlockDeltaThinking.Builder builder() {
    return new MessagesResponseContentBlockDeltaThinking.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public MessagesResponseContentBlockDeltaThinking.Builder toBuilder() {
    return new MessagesResponseContentBlockDeltaThinking.Builder()
      .type(getType())
      .thinking(getThinking());
  }


}
