// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Messages API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.messages;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * MessagesContentPartWebSearchToolResult
 */
@JsonPropertyOrder({
  MessagesContentPartWebSearchToolResult.JSON_PROPERTY_TYPE,
  MessagesContentPartWebSearchToolResult.JSON_PROPERTY_TOOL_USE_ID,
  MessagesContentPartWebSearchToolResult.JSON_PROPERTY_CONTENT,
  MessagesContentPartWebSearchToolResult.JSON_PROPERTY_CALLER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class MessagesContentPartWebSearchToolResult implements MessagesContentPart {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private ContentPartType type = ContentPartType.WEB_SEARCH_TOOL_RESULT;

  public static final String JSON_PROPERTY_TOOL_USE_ID = "tool_use_id";
  @javax.annotation.Nonnull
  private String toolUseId;

  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nonnull
  private MessagesWebSearchToolResultContent content;

  public static final String JSON_PROPERTY_CALLER = "caller";
  @javax.annotation.Nullable
  private MessagesServerToolCaller caller;

  public MessagesContentPartWebSearchToolResult() {
  }

  public MessagesContentPartWebSearchToolResult type(@javax.annotation.Nonnull ContentPartType type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ContentPartType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull ContentPartType type) {
    this.type = type;
  }

  public MessagesContentPartWebSearchToolResult toolUseId(@javax.annotation.Nonnull String toolUseId) {

    this.toolUseId = toolUseId;
    return this;
  }

  /**
   * The server-tool invocation this result answers.
   * @return toolUseId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOOL_USE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToolUseId() {
    return toolUseId;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL_USE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToolUseId(@javax.annotation.Nonnull String toolUseId) {
    this.toolUseId = toolUseId;
  }

  public MessagesContentPartWebSearchToolResult content(@javax.annotation.Nonnull MessagesWebSearchToolResultContent content) {

    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MessagesWebSearchToolResultContent getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContent(@javax.annotation.Nonnull MessagesWebSearchToolResultContent content) {
    this.content = content;
  }

  public MessagesContentPartWebSearchToolResult caller(@javax.annotation.Nullable MessagesServerToolCaller caller) {

    this.caller = caller;
    return this;
  }

  /**
   * Get caller
   * @return caller
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CALLER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MessagesServerToolCaller getCaller() {
    return caller;
  }


  @JsonProperty(value = JSON_PROPERTY_CALLER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCaller(@javax.annotation.Nullable MessagesServerToolCaller caller) {
    this.caller = caller;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessagesContentPartWebSearchToolResult messagesContentPartWebSearchToolResult = (MessagesContentPartWebSearchToolResult) o;
    return Objects.equals(this.type, messagesContentPartWebSearchToolResult.type) &&
        Objects.equals(this.toolUseId, messagesContentPartWebSearchToolResult.toolUseId) &&
        Objects.equals(this.content, messagesContentPartWebSearchToolResult.content) &&
        Objects.equals(this.caller, messagesContentPartWebSearchToolResult.caller);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, toolUseId, content, caller);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessagesContentPartWebSearchToolResult {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    toolUseId: ").append(toIndentedString(toolUseId)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    caller: ").append(toIndentedString(caller)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private MessagesContentPartWebSearchToolResult instance;

    public Builder() {
      this(new MessagesContentPartWebSearchToolResult());
    }

    protected Builder(MessagesContentPartWebSearchToolResult instance) {
      this.instance = instance;
    }

    public MessagesContentPartWebSearchToolResult.Builder type(ContentPartType type) {
      this.instance.type = type;
      return this;
    }
    public MessagesContentPartWebSearchToolResult.Builder toolUseId(String toolUseId) {
      this.instance.toolUseId = toolUseId;
      return this;
    }
    public MessagesContentPartWebSearchToolResult.Builder content(MessagesWebSearchToolResultContent content) {
      this.instance.content = content;
      return this;
    }
    public MessagesContentPartWebSearchToolResult.Builder caller(MessagesServerToolCaller caller) {
      this.instance.caller = caller;
      return this;
    }


    /**
    * returns a built MessagesContentPartWebSearchToolResult instance.
    *
    * The builder is not reusable.
    */
    public MessagesContentPartWebSearchToolResult build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static MessagesContentPartWebSearchToolResult.Builder builder() {
    return new MessagesContentPartWebSearchToolResult.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public MessagesContentPartWebSearchToolResult.Builder toBuilder() {
    return new MessagesContentPartWebSearchToolResult.Builder()
      .type(getType())
      .toolUseId(getToolUseId())
      .content(getContent())
      .caller(getCaller());
  }


}
