// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Chat Completions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.chat;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * ChatCompletionRequestToolMessage
 */
@JsonPropertyOrder({
  ChatCompletionRequestToolMessage.JSON_PROPERTY_ROLE,
  ChatCompletionRequestToolMessage.JSON_PROPERTY_CONTENT,
  ChatCompletionRequestToolMessage.JSON_PROPERTY_TOOL_CALL_ID,
  ChatCompletionRequestToolMessage.JSON_PROPERTY_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ChatCompletionRequestToolMessage implements ChatCompletionRequestMessage {
  public static final String JSON_PROPERTY_ROLE = "role";
  @javax.annotation.Nonnull
  private ChatCompletionRequestMessageType role = ChatCompletionRequestMessageType.TOOL;

  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nonnull
  private ChatCompletionMessageContent content;

  public static final String JSON_PROPERTY_TOOL_CALL_ID = "tool_call_id";
  @javax.annotation.Nonnull
  private String toolCallId;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public ChatCompletionRequestToolMessage() {
  }

  public ChatCompletionRequestToolMessage role(@javax.annotation.Nonnull ChatCompletionRequestMessageType role) {

    this.role = role;
    return this;
  }

  /**
   * Get role
   * @return role
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ROLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ChatCompletionRequestMessageType getRole() {
    return role;
  }


  @JsonProperty(value = JSON_PROPERTY_ROLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRole(@javax.annotation.Nonnull ChatCompletionRequestMessageType role) {
    this.role = role;
  }

  public ChatCompletionRequestToolMessage content(@javax.annotation.Nonnull ChatCompletionMessageContent content) {

    this.content = content;
    return this;
  }

  /**
   * The contents of the tool message.
   * @return content
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ChatCompletionMessageContent getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContent(@javax.annotation.Nonnull ChatCompletionMessageContent content) {
    this.content = content;
  }

  public ChatCompletionRequestToolMessage toolCallId(@javax.annotation.Nonnull String toolCallId) {

    this.toolCallId = toolCallId;
    return this;
  }

  /**
   * Tool call that this message is responding to.
   * @return toolCallId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOOL_CALL_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToolCallId() {
    return toolCallId;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL_CALL_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToolCallId(@javax.annotation.Nonnull String toolCallId) {
    this.toolCallId = toolCallId;
  }

  public ChatCompletionRequestToolMessage name(@javax.annotation.Nullable String name) {

    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionRequestToolMessage chatCompletionRequestToolMessage = (ChatCompletionRequestToolMessage) o;
    return Objects.equals(this.role, chatCompletionRequestToolMessage.role) &&
        Objects.equals(this.content, chatCompletionRequestToolMessage.content) &&
        Objects.equals(this.toolCallId, chatCompletionRequestToolMessage.toolCallId) &&
        Objects.equals(this.name, chatCompletionRequestToolMessage.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(role, content, toolCallId, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionRequestToolMessage {\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    toolCallId: ").append(toIndentedString(toolCallId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ChatCompletionRequestToolMessage instance;

    public Builder() {
      this(new ChatCompletionRequestToolMessage());
    }

    protected Builder(ChatCompletionRequestToolMessage instance) {
      this.instance = instance;
    }

    public ChatCompletionRequestToolMessage.Builder role(ChatCompletionRequestMessageType role) {
      this.instance.role = role;
      return this;
    }
    public ChatCompletionRequestToolMessage.Builder content(ChatCompletionMessageContent content) {
      this.instance.content = content;
      return this;
    }
    public ChatCompletionRequestToolMessage.Builder toolCallId(String toolCallId) {
      this.instance.toolCallId = toolCallId;
      return this;
    }
    public ChatCompletionRequestToolMessage.Builder name(String name) {
      this.instance.name = name;
      return this;
    }


    /**
    * returns a built ChatCompletionRequestToolMessage instance.
    *
    * The builder is not reusable.
    */
    public ChatCompletionRequestToolMessage build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ChatCompletionRequestToolMessage.Builder builder() {
    return new ChatCompletionRequestToolMessage.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ChatCompletionRequestToolMessage.Builder toBuilder() {
    return new ChatCompletionRequestToolMessage.Builder()
      .role(getRole())
      .content(getContent())
      .toolCallId(getToolCallId())
      .name(getName());
  }


}
