// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Chat Completions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.chat;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * ChatCompletionRequest
 */
@JsonPropertyOrder({
  ChatCompletionRequest.JSON_PROPERTY_MESSAGES,
  ChatCompletionRequest.JSON_PROPERTY_MODEL,
  ChatCompletionRequest.JSON_PROPERTY_FREQUENCY_PENALTY,
  ChatCompletionRequest.JSON_PROPERTY_PRESENCE_PENALTY,
  ChatCompletionRequest.JSON_PROPERTY_REPETITION_PENALTY,
  ChatCompletionRequest.JSON_PROPERTY_LOGIT_BIAS,
  ChatCompletionRequest.JSON_PROPERTY_LOGPROBS,
  ChatCompletionRequest.JSON_PROPERTY_TOP_LOGPROBS,
  ChatCompletionRequest.JSON_PROPERTY_MAX_TOKENS,
  ChatCompletionRequest.JSON_PROPERTY_MAX_COMPLETION_TOKENS,
  ChatCompletionRequest.JSON_PROPERTY_N,
  ChatCompletionRequest.JSON_PROPERTY_RESPONSE_FORMAT,
  ChatCompletionRequest.JSON_PROPERTY_STOP,
  ChatCompletionRequest.JSON_PROPERTY_STREAM,
  ChatCompletionRequest.JSON_PROPERTY_STREAM_OPTIONS,
  ChatCompletionRequest.JSON_PROPERTY_TEMPERATURE,
  ChatCompletionRequest.JSON_PROPERTY_TOP_P,
  ChatCompletionRequest.JSON_PROPERTY_TOOL_CHOICE,
  ChatCompletionRequest.JSON_PROPERTY_TOOLS,
  ChatCompletionRequest.JSON_PROPERTY_PARALLEL_TOOL_CALLS,
  ChatCompletionRequest.JSON_PROPERTY_USER,
  ChatCompletionRequest.JSON_PROPERTY_SERVICE_TIER,
  ChatCompletionRequest.JSON_PROPERTY_REASONING_EFFORT,
  ChatCompletionRequest.JSON_PROPERTY_THINKING
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ChatCompletionRequest {
  public static final String JSON_PROPERTY_MESSAGES = "messages";
  @javax.annotation.Nonnull
  private List<ChatCompletionRequestMessage> messages;

  public static final String JSON_PROPERTY_MODEL = "model";
  @javax.annotation.Nonnull
  private String model;

  public static final String JSON_PROPERTY_FREQUENCY_PENALTY = "frequency_penalty";
  @javax.annotation.Nullable
  private Double frequencyPenalty;

  public static final String JSON_PROPERTY_PRESENCE_PENALTY = "presence_penalty";
  @javax.annotation.Nullable
  private Double presencePenalty;

  public static final String JSON_PROPERTY_REPETITION_PENALTY = "repetition_penalty";
  @javax.annotation.Nullable
  private Double repetitionPenalty;

  public static final String JSON_PROPERTY_LOGIT_BIAS = "logit_bias";
  @javax.annotation.Nullable
  private Map<String, Float> logitBias;

  public static final String JSON_PROPERTY_LOGPROBS = "logprobs";
  @javax.annotation.Nullable
  private Boolean logprobs;

  public static final String JSON_PROPERTY_TOP_LOGPROBS = "top_logprobs";
  @javax.annotation.Nullable
  private Integer topLogprobs;

  public static final String JSON_PROPERTY_MAX_TOKENS = "max_tokens";
  @javax.annotation.Nullable
  private Integer maxTokens;

  public static final String JSON_PROPERTY_MAX_COMPLETION_TOKENS = "max_completion_tokens";
  @javax.annotation.Nullable
  private Integer maxCompletionTokens;

  public static final String JSON_PROPERTY_N = "n";
  @javax.annotation.Nullable
  private Integer n;

  public static final String JSON_PROPERTY_RESPONSE_FORMAT = "response_format";
  @javax.annotation.Nullable
  private ChatCompletionResponseFormat responseFormat;

  public static final String JSON_PROPERTY_STOP = "stop";
  @javax.annotation.Nullable
  private ChatCompletionStop stop;

  public static final String JSON_PROPERTY_STREAM = "stream";
  @javax.annotation.Nullable
  private Boolean stream;

  public static final String JSON_PROPERTY_STREAM_OPTIONS = "stream_options";
  @javax.annotation.Nullable
  private ChatCompletionStreamOptions streamOptions;

  public static final String JSON_PROPERTY_TEMPERATURE = "temperature";
  @javax.annotation.Nullable
  private Double temperature;

  public static final String JSON_PROPERTY_TOP_P = "top_p";
  @javax.annotation.Nullable
  private Double topP;

  public static final String JSON_PROPERTY_TOOL_CHOICE = "tool_choice";
  @javax.annotation.Nullable
  private ChatCompletionToolChoice toolChoice;

  public static final String JSON_PROPERTY_TOOLS = "tools";
  @javax.annotation.Nullable
  private List<ChatCompletionTool> tools;

  public static final String JSON_PROPERTY_PARALLEL_TOOL_CALLS = "parallel_tool_calls";
  @javax.annotation.Nullable
  private Boolean parallelToolCalls;

  public static final String JSON_PROPERTY_USER = "user";
  @javax.annotation.Nullable
  private String user;

  public static final String JSON_PROPERTY_SERVICE_TIER = "service_tier";
  @javax.annotation.Nullable
  private RequestServiceTier serviceTier;

  public static final String JSON_PROPERTY_REASONING_EFFORT = "reasoning_effort";
  @javax.annotation.Nullable
  private ReasoningEffort reasoningEffort;

  public static final String JSON_PROPERTY_THINKING = "thinking";
  @javax.annotation.Nullable
  private Thinking thinking;

  public ChatCompletionRequest() {
  }

  public ChatCompletionRequest messages(@javax.annotation.Nonnull List<ChatCompletionRequestMessage> messages) {

    this.messages = messages;
    return this;
  }

  public ChatCompletionRequest addMessagesItem(ChatCompletionRequestMessage messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<>();
    }
    this.messages.add(messagesItem);
    return this;
  }

  /**
   * A list of messages comprising the conversation so far.
   * @return messages
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ChatCompletionRequestMessage> getMessages() {
    return messages;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessages(@javax.annotation.Nonnull List<ChatCompletionRequestMessage> messages) {
    this.messages = messages;
  }

  public ChatCompletionRequest model(@javax.annotation.Nonnull String model) {

    this.model = model;
    return this;
  }

  /**
   * ID of the model to use.
   * @return model
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getModel() {
    return model;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModel(@javax.annotation.Nonnull String model) {
    this.model = model;
  }

  public ChatCompletionRequest frequencyPenalty(@javax.annotation.Nullable Double frequencyPenalty) {

    this.frequencyPenalty = frequencyPenalty;
    return this;
  }

  /**
   * Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far.
   * @return frequencyPenalty
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FREQUENCY_PENALTY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getFrequencyPenalty() {
    return frequencyPenalty;
  }


  @JsonProperty(value = JSON_PROPERTY_FREQUENCY_PENALTY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFrequencyPenalty(@javax.annotation.Nullable Double frequencyPenalty) {
    this.frequencyPenalty = frequencyPenalty;
  }

  public ChatCompletionRequest presencePenalty(@javax.annotation.Nullable Double presencePenalty) {

    this.presencePenalty = presencePenalty;
    return this;
  }

  /**
   * Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far.
   * @return presencePenalty
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRESENCE_PENALTY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPresencePenalty() {
    return presencePenalty;
  }


  @JsonProperty(value = JSON_PROPERTY_PRESENCE_PENALTY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPresencePenalty(@javax.annotation.Nullable Double presencePenalty) {
    this.presencePenalty = presencePenalty;
  }

  public ChatCompletionRequest repetitionPenalty(@javax.annotation.Nullable Double repetitionPenalty) {

    this.repetitionPenalty = repetitionPenalty;
    return this;
  }

  /**
   * Number between 0.0 and 2.0. Penalizes repetition independently of frequency.
   * @return repetitionPenalty
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPETITION_PENALTY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getRepetitionPenalty() {
    return repetitionPenalty;
  }


  @JsonProperty(value = JSON_PROPERTY_REPETITION_PENALTY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepetitionPenalty(@javax.annotation.Nullable Double repetitionPenalty) {
    this.repetitionPenalty = repetitionPenalty;
  }

  public ChatCompletionRequest logitBias(@javax.annotation.Nullable Map<String, Float> logitBias) {

    this.logitBias = logitBias;
    return this;
  }

  public ChatCompletionRequest putLogitBiasItem(String key, Float logitBiasItem) {
    if (this.logitBias == null) {
      this.logitBias = new HashMap<>();
    }
    this.logitBias.put(key, logitBiasItem);
    return this;
  }

  /**
   * Modify the likelihood of specified tokens appearing in the completion. Maps token IDs (as strings) to a bias from -100 to 100.
   * @return logitBias
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOGIT_BIAS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public Map<String, Float> getLogitBias() {
    return logitBias;
  }


  @JsonProperty(value = JSON_PROPERTY_LOGIT_BIAS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setLogitBias(@javax.annotation.Nullable Map<String, Float> logitBias) {
    this.logitBias = logitBias;
  }

  public ChatCompletionRequest logprobs(@javax.annotation.Nullable Boolean logprobs) {

    this.logprobs = logprobs;
    return this;
  }

  /**
   * Whether to return log probabilities of the output tokens.
   * @return logprobs
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOGPROBS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLogprobs() {
    return logprobs;
  }


  @JsonProperty(value = JSON_PROPERTY_LOGPROBS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogprobs(@javax.annotation.Nullable Boolean logprobs) {
    this.logprobs = logprobs;
  }

  public ChatCompletionRequest topLogprobs(@javax.annotation.Nullable Integer topLogprobs) {

    this.topLogprobs = topLogprobs;
    return this;
  }

  /**
   * Number of most-likely tokens to return at each position when &#x60;logprobs&#x60; is true. Range 0-20.
   * @return topLogprobs
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOP_LOGPROBS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTopLogprobs() {
    return topLogprobs;
  }


  @JsonProperty(value = JSON_PROPERTY_TOP_LOGPROBS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTopLogprobs(@javax.annotation.Nullable Integer topLogprobs) {
    this.topLogprobs = topLogprobs;
  }

  public ChatCompletionRequest maxTokens(@javax.annotation.Nullable Integer maxTokens) {

    this.maxTokens = maxTokens;
    return this;
  }

  /**
   * The maximum number of tokens that can be generated in the completion.
   * @return maxTokens
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxTokens() {
    return maxTokens;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxTokens(@javax.annotation.Nullable Integer maxTokens) {
    this.maxTokens = maxTokens;
  }

  public ChatCompletionRequest maxCompletionTokens(@javax.annotation.Nullable Integer maxCompletionTokens) {

    this.maxCompletionTokens = maxCompletionTokens;
    return this;
  }

  /**
   * Upper bound on completion tokens, including reasoning tokens.
   * @return maxCompletionTokens
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_COMPLETION_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaxCompletionTokens() {
    return maxCompletionTokens;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_COMPLETION_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxCompletionTokens(@javax.annotation.Nullable Integer maxCompletionTokens) {
    this.maxCompletionTokens = maxCompletionTokens;
  }

  public ChatCompletionRequest n(@javax.annotation.Nullable Integer n) {

    this.n = n;
    return this;
  }

  /**
   * How many chat completion choices to generate for each input message. Range 1-5.
   * @return n
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_N, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getN() {
    return n;
  }


  @JsonProperty(value = JSON_PROPERTY_N, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setN(@javax.annotation.Nullable Integer n) {
    this.n = n;
  }

  public ChatCompletionRequest responseFormat(@javax.annotation.Nullable ChatCompletionResponseFormat responseFormat) {

    this.responseFormat = responseFormat;
    return this;
  }

  /**
   * An object specifying the format that the model must output.
   * @return responseFormat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESPONSE_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ChatCompletionResponseFormat getResponseFormat() {
    return responseFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_RESPONSE_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponseFormat(@javax.annotation.Nullable ChatCompletionResponseFormat responseFormat) {
    this.responseFormat = responseFormat;
  }

  public ChatCompletionRequest stop(@javax.annotation.Nullable ChatCompletionStop stop) {

    this.stop = stop;
    return this;
  }

  /**
   * Up to 4 sequences where the API will stop generating further tokens.
   * @return stop
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STOP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ChatCompletionStop getStop() {
    return stop;
  }


  @JsonProperty(value = JSON_PROPERTY_STOP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStop(@javax.annotation.Nullable ChatCompletionStop stop) {
    this.stop = stop;
  }

  public ChatCompletionRequest stream(@javax.annotation.Nullable Boolean stream) {

    this.stream = stream;
    return this;
  }

  /**
   * If set, partial message deltas will be sent as data-only server-sent events.
   * @return stream
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STREAM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getStream() {
    return stream;
  }


  @JsonProperty(value = JSON_PROPERTY_STREAM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStream(@javax.annotation.Nullable Boolean stream) {
    this.stream = stream;
  }

  public ChatCompletionRequest streamOptions(@javax.annotation.Nullable ChatCompletionStreamOptions streamOptions) {

    this.streamOptions = streamOptions;
    return this;
  }

  /**
   * Options for streaming responses.
   * @return streamOptions
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STREAM_OPTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ChatCompletionStreamOptions getStreamOptions() {
    return streamOptions;
  }


  @JsonProperty(value = JSON_PROPERTY_STREAM_OPTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStreamOptions(@javax.annotation.Nullable ChatCompletionStreamOptions streamOptions) {
    this.streamOptions = streamOptions;
  }

  public ChatCompletionRequest temperature(@javax.annotation.Nullable Double temperature) {

    this.temperature = temperature;
    return this;
  }

  /**
   * What sampling temperature to use, between 0 and 2.
   * @return temperature
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEMPERATURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTemperature() {
    return temperature;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPERATURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemperature(@javax.annotation.Nullable Double temperature) {
    this.temperature = temperature;
  }

  public ChatCompletionRequest topP(@javax.annotation.Nullable Double topP) {

    this.topP = topP;
    return this;
  }

  /**
   * Nucleus sampling: between 0 and 1.
   * @return topP
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOP_P, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getTopP() {
    return topP;
  }


  @JsonProperty(value = JSON_PROPERTY_TOP_P, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTopP(@javax.annotation.Nullable Double topP) {
    this.topP = topP;
  }

  public ChatCompletionRequest toolChoice(@javax.annotation.Nullable ChatCompletionToolChoice toolChoice) {

    this.toolChoice = toolChoice;
    return this;
  }

  /**
   * Controls which (if any) tool is called by the model.
   * @return toolChoice
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOL_CHOICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ChatCompletionToolChoice getToolChoice() {
    return toolChoice;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL_CHOICE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToolChoice(@javax.annotation.Nullable ChatCompletionToolChoice toolChoice) {
    this.toolChoice = toolChoice;
  }

  public ChatCompletionRequest tools(@javax.annotation.Nullable List<ChatCompletionTool> tools) {

    this.tools = tools;
    return this;
  }

  public ChatCompletionRequest addToolsItem(ChatCompletionTool toolsItem) {
    if (this.tools == null) {
      this.tools = new ArrayList<>();
    }
    this.tools.add(toolsItem);
    return this;
  }

  /**
   * A list of tools the model may call.
   * @return tools
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<ChatCompletionTool> getTools() {
    return tools;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setTools(@javax.annotation.Nullable List<ChatCompletionTool> tools) {
    this.tools = tools;
  }

  public ChatCompletionRequest parallelToolCalls(@javax.annotation.Nullable Boolean parallelToolCalls) {

    this.parallelToolCalls = parallelToolCalls;
    return this;
  }

  /**
   * Whether to enable parallel function calling during tool use.
   * @return parallelToolCalls
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARALLEL_TOOL_CALLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getParallelToolCalls() {
    return parallelToolCalls;
  }


  @JsonProperty(value = JSON_PROPERTY_PARALLEL_TOOL_CALLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParallelToolCalls(@javax.annotation.Nullable Boolean parallelToolCalls) {
    this.parallelToolCalls = parallelToolCalls;
  }

  public ChatCompletionRequest user(@javax.annotation.Nullable String user) {

    this.user = user;
    return this;
  }

  /**
   * A unique identifier representing your end-user.
   * @return user
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUser() {
    return user;
  }


  @JsonProperty(value = JSON_PROPERTY_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUser(@javax.annotation.Nullable String user) {
    this.user = user;
  }

  public ChatCompletionRequest serviceTier(@javax.annotation.Nullable RequestServiceTier serviceTier) {

    this.serviceTier = serviceTier;
    return this;
  }

  /**
   * The service tier to use for the request.
   * @return serviceTier
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVICE_TIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RequestServiceTier getServiceTier() {
    return serviceTier;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVICE_TIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceTier(@javax.annotation.Nullable RequestServiceTier serviceTier) {
    this.serviceTier = serviceTier;
  }

  public ChatCompletionRequest reasoningEffort(@javax.annotation.Nullable ReasoningEffort reasoningEffort) {

    this.reasoningEffort = reasoningEffort;
    return this;
  }

  /**
   * Constrains effort on reasoning.
   * @return reasoningEffort
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REASONING_EFFORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ReasoningEffort getReasoningEffort() {
    return reasoningEffort;
  }


  @JsonProperty(value = JSON_PROPERTY_REASONING_EFFORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReasoningEffort(@javax.annotation.Nullable ReasoningEffort reasoningEffort) {
    this.reasoningEffort = reasoningEffort;
  }

  public ChatCompletionRequest thinking(@javax.annotation.Nullable Thinking thinking) {

    this.thinking = thinking;
    return this;
  }

  /**
   * Configuration for thinking-mode models.
   * @return thinking
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THINKING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Thinking getThinking() {
    return thinking;
  }


  @JsonProperty(value = JSON_PROPERTY_THINKING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThinking(@javax.annotation.Nullable Thinking thinking) {
    this.thinking = thinking;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionRequest chatCompletionRequest = (ChatCompletionRequest) o;
    return Objects.equals(this.messages, chatCompletionRequest.messages) &&
        Objects.equals(this.model, chatCompletionRequest.model) &&
        Objects.equals(this.frequencyPenalty, chatCompletionRequest.frequencyPenalty) &&
        Objects.equals(this.presencePenalty, chatCompletionRequest.presencePenalty) &&
        Objects.equals(this.repetitionPenalty, chatCompletionRequest.repetitionPenalty) &&
        Objects.equals(this.logitBias, chatCompletionRequest.logitBias) &&
        Objects.equals(this.logprobs, chatCompletionRequest.logprobs) &&
        Objects.equals(this.topLogprobs, chatCompletionRequest.topLogprobs) &&
        Objects.equals(this.maxTokens, chatCompletionRequest.maxTokens) &&
        Objects.equals(this.maxCompletionTokens, chatCompletionRequest.maxCompletionTokens) &&
        Objects.equals(this.n, chatCompletionRequest.n) &&
        Objects.equals(this.responseFormat, chatCompletionRequest.responseFormat) &&
        Objects.equals(this.stop, chatCompletionRequest.stop) &&
        Objects.equals(this.stream, chatCompletionRequest.stream) &&
        Objects.equals(this.streamOptions, chatCompletionRequest.streamOptions) &&
        Objects.equals(this.temperature, chatCompletionRequest.temperature) &&
        Objects.equals(this.topP, chatCompletionRequest.topP) &&
        Objects.equals(this.toolChoice, chatCompletionRequest.toolChoice) &&
        Objects.equals(this.tools, chatCompletionRequest.tools) &&
        Objects.equals(this.parallelToolCalls, chatCompletionRequest.parallelToolCalls) &&
        Objects.equals(this.user, chatCompletionRequest.user) &&
        Objects.equals(this.serviceTier, chatCompletionRequest.serviceTier) &&
        Objects.equals(this.reasoningEffort, chatCompletionRequest.reasoningEffort) &&
        Objects.equals(this.thinking, chatCompletionRequest.thinking);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messages, model, frequencyPenalty, presencePenalty, repetitionPenalty, logitBias, logprobs, topLogprobs, maxTokens, maxCompletionTokens, n, responseFormat, stop, stream, streamOptions, temperature, topP, toolChoice, tools, parallelToolCalls, user, serviceTier, reasoningEffort, thinking);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionRequest {\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    frequencyPenalty: ").append(toIndentedString(frequencyPenalty)).append("\n");
    sb.append("    presencePenalty: ").append(toIndentedString(presencePenalty)).append("\n");
    sb.append("    repetitionPenalty: ").append(toIndentedString(repetitionPenalty)).append("\n");
    sb.append("    logitBias: ").append(toIndentedString(logitBias)).append("\n");
    sb.append("    logprobs: ").append(toIndentedString(logprobs)).append("\n");
    sb.append("    topLogprobs: ").append(toIndentedString(topLogprobs)).append("\n");
    sb.append("    maxTokens: ").append(toIndentedString(maxTokens)).append("\n");
    sb.append("    maxCompletionTokens: ").append(toIndentedString(maxCompletionTokens)).append("\n");
    sb.append("    n: ").append(toIndentedString(n)).append("\n");
    sb.append("    responseFormat: ").append(toIndentedString(responseFormat)).append("\n");
    sb.append("    stop: ").append(toIndentedString(stop)).append("\n");
    sb.append("    stream: ").append(toIndentedString(stream)).append("\n");
    sb.append("    streamOptions: ").append(toIndentedString(streamOptions)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    topP: ").append(toIndentedString(topP)).append("\n");
    sb.append("    toolChoice: ").append(toIndentedString(toolChoice)).append("\n");
    sb.append("    tools: ").append(toIndentedString(tools)).append("\n");
    sb.append("    parallelToolCalls: ").append(toIndentedString(parallelToolCalls)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    serviceTier: ").append(toIndentedString(serviceTier)).append("\n");
    sb.append("    reasoningEffort: ").append(toIndentedString(reasoningEffort)).append("\n");
    sb.append("    thinking: ").append(toIndentedString(thinking)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ChatCompletionRequest instance;

    public Builder() {
      this(new ChatCompletionRequest());
    }

    protected Builder(ChatCompletionRequest instance) {
      this.instance = instance;
    }

    public ChatCompletionRequest.Builder messages(List<ChatCompletionRequestMessage> messages) {
      this.instance.messages = messages;
      return this;
    }
    public ChatCompletionRequest.Builder model(String model) {
      this.instance.model = model;
      return this;
    }
    public ChatCompletionRequest.Builder frequencyPenalty(Double frequencyPenalty) {
      this.instance.frequencyPenalty = frequencyPenalty;
      return this;
    }
    public ChatCompletionRequest.Builder presencePenalty(Double presencePenalty) {
      this.instance.presencePenalty = presencePenalty;
      return this;
    }
    public ChatCompletionRequest.Builder repetitionPenalty(Double repetitionPenalty) {
      this.instance.repetitionPenalty = repetitionPenalty;
      return this;
    }
    public ChatCompletionRequest.Builder logitBias(Map<String, Float> logitBias) {
      this.instance.logitBias = logitBias;
      return this;
    }
    public ChatCompletionRequest.Builder logprobs(Boolean logprobs) {
      this.instance.logprobs = logprobs;
      return this;
    }
    public ChatCompletionRequest.Builder topLogprobs(Integer topLogprobs) {
      this.instance.topLogprobs = topLogprobs;
      return this;
    }
    public ChatCompletionRequest.Builder maxTokens(Integer maxTokens) {
      this.instance.maxTokens = maxTokens;
      return this;
    }
    public ChatCompletionRequest.Builder maxCompletionTokens(Integer maxCompletionTokens) {
      this.instance.maxCompletionTokens = maxCompletionTokens;
      return this;
    }
    public ChatCompletionRequest.Builder n(Integer n) {
      this.instance.n = n;
      return this;
    }
    public ChatCompletionRequest.Builder responseFormat(ChatCompletionResponseFormat responseFormat) {
      this.instance.responseFormat = responseFormat;
      return this;
    }
    public ChatCompletionRequest.Builder stop(ChatCompletionStop stop) {
      this.instance.stop = stop;
      return this;
    }
    public ChatCompletionRequest.Builder stream(Boolean stream) {
      this.instance.stream = stream;
      return this;
    }
    public ChatCompletionRequest.Builder streamOptions(ChatCompletionStreamOptions streamOptions) {
      this.instance.streamOptions = streamOptions;
      return this;
    }
    public ChatCompletionRequest.Builder temperature(Double temperature) {
      this.instance.temperature = temperature;
      return this;
    }
    public ChatCompletionRequest.Builder topP(Double topP) {
      this.instance.topP = topP;
      return this;
    }
    public ChatCompletionRequest.Builder toolChoice(ChatCompletionToolChoice toolChoice) {
      this.instance.toolChoice = toolChoice;
      return this;
    }
    public ChatCompletionRequest.Builder tools(List<ChatCompletionTool> tools) {
      this.instance.tools = tools;
      return this;
    }
    public ChatCompletionRequest.Builder parallelToolCalls(Boolean parallelToolCalls) {
      this.instance.parallelToolCalls = parallelToolCalls;
      return this;
    }
    public ChatCompletionRequest.Builder user(String user) {
      this.instance.user = user;
      return this;
    }
    public ChatCompletionRequest.Builder serviceTier(RequestServiceTier serviceTier) {
      this.instance.serviceTier = serviceTier;
      return this;
    }
    public ChatCompletionRequest.Builder reasoningEffort(ReasoningEffort reasoningEffort) {
      this.instance.reasoningEffort = reasoningEffort;
      return this;
    }
    public ChatCompletionRequest.Builder thinking(Thinking thinking) {
      this.instance.thinking = thinking;
      return this;
    }


    /**
    * returns a built ChatCompletionRequest instance.
    *
    * The builder is not reusable.
    */
    public ChatCompletionRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ChatCompletionRequest.Builder builder() {
    return new ChatCompletionRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ChatCompletionRequest.Builder toBuilder() {
    return new ChatCompletionRequest.Builder()
      .messages(getMessages())
      .model(getModel())
      .frequencyPenalty(getFrequencyPenalty())
      .presencePenalty(getPresencePenalty())
      .repetitionPenalty(getRepetitionPenalty())
      .logitBias(getLogitBias())
      .logprobs(getLogprobs())
      .topLogprobs(getTopLogprobs())
      .maxTokens(getMaxTokens())
      .maxCompletionTokens(getMaxCompletionTokens())
      .n(getN())
      .responseFormat(getResponseFormat())
      .stop(getStop())
      .stream(getStream())
      .streamOptions(getStreamOptions())
      .temperature(getTemperature())
      .topP(getTopP())
      .toolChoice(getToolChoice())
      .tools(getTools())
      .parallelToolCalls(getParallelToolCalls())
      .user(getUser())
      .serviceTier(getServiceTier())
      .reasoningEffort(getReasoningEffort())
      .thinking(getThinking());
  }


}
