// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Chat Completions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.chat;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/**
 * ChatCompletionNamedToolChoice
 */
@JsonPropertyOrder({
  ChatCompletionNamedToolChoice.JSON_PROPERTY_TYPE,
  ChatCompletionNamedToolChoice.JSON_PROPERTY_FUNCTION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ChatCompletionNamedToolChoice {
  /**
   * For function calling, the type is always &#x60;function&#x60;.
   */
  public enum TypeEnum {
    FUNCTION(String.valueOf("function"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equalsIgnoreCase(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_FUNCTION = "function";
  @javax.annotation.Nonnull
  private ChatCompletionToolChoiceFunction function;

  public ChatCompletionNamedToolChoice() {
  }

  public ChatCompletionNamedToolChoice type(@javax.annotation.Nonnull TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * For function calling, the type is always &#x60;function&#x60;.
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public ChatCompletionNamedToolChoice function(@javax.annotation.Nonnull ChatCompletionToolChoiceFunction function) {

    this.function = function;
    return this;
  }

  /**
   * Get function
   * @return function
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FUNCTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ChatCompletionToolChoiceFunction getFunction() {
    return function;
  }


  @JsonProperty(value = JSON_PROPERTY_FUNCTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFunction(@javax.annotation.Nonnull ChatCompletionToolChoiceFunction function) {
    this.function = function;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionNamedToolChoice chatCompletionNamedToolChoice = (ChatCompletionNamedToolChoice) o;
    return Objects.equals(this.type, chatCompletionNamedToolChoice.type) &&
        Objects.equals(this.function, chatCompletionNamedToolChoice.function);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, function);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionNamedToolChoice {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ChatCompletionNamedToolChoice instance;

    public Builder() {
      this(new ChatCompletionNamedToolChoice());
    }

    protected Builder(ChatCompletionNamedToolChoice instance) {
      this.instance = instance;
    }

    public ChatCompletionNamedToolChoice.Builder type(TypeEnum type) {
      this.instance.type = type;
      return this;
    }
    public ChatCompletionNamedToolChoice.Builder function(ChatCompletionToolChoiceFunction function) {
      this.instance.function = function;
      return this;
    }


    /**
    * returns a built ChatCompletionNamedToolChoice instance.
    *
    * The builder is not reusable.
    */
    public ChatCompletionNamedToolChoice build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ChatCompletionNamedToolChoice.Builder builder() {
    return new ChatCompletionNamedToolChoice.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ChatCompletionNamedToolChoice.Builder toBuilder() {
    return new ChatCompletionNamedToolChoice.Builder()
      .type(getType())
      .function(getFunction());
  }


}
