// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Chat Completions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.chat;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * ChatCompletionRequestMessageToolCall
 */
@JsonPropertyOrder({
  ChatCompletionRequestMessageToolCall.JSON_PROPERTY_ID,
  ChatCompletionRequestMessageToolCall.JSON_PROPERTY_TYPE,
  ChatCompletionRequestMessageToolCall.JSON_PROPERTY_FUNCTION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ChatCompletionRequestMessageToolCall {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private ToolType type;

  public static final String JSON_PROPERTY_FUNCTION = "function";
  @javax.annotation.Nonnull
  private ChatCompletionRequestMessageToolCallFunction function;

  public ChatCompletionRequestMessageToolCall() {
  }

  public ChatCompletionRequestMessageToolCall id(@javax.annotation.Nullable String id) {

    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public ChatCompletionRequestMessageToolCall type(@javax.annotation.Nonnull ToolType type) {

    this.type = type;
    return this;
  }

  /**
   * The type of the tool. Currently, only &#x60;function&#x60; is supported.
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ToolType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull ToolType type) {
    this.type = type;
  }

  public ChatCompletionRequestMessageToolCall function(@javax.annotation.Nonnull ChatCompletionRequestMessageToolCallFunction function) {

    this.function = function;
    return this;
  }

  /**
   * The function called in a previous assistant message.
   * @return function
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FUNCTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ChatCompletionRequestMessageToolCallFunction getFunction() {
    return function;
  }


  @JsonProperty(value = JSON_PROPERTY_FUNCTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFunction(@javax.annotation.Nonnull ChatCompletionRequestMessageToolCallFunction function) {
    this.function = function;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionRequestMessageToolCall chatCompletionRequestMessageToolCall = (ChatCompletionRequestMessageToolCall) o;
    return Objects.equals(this.id, chatCompletionRequestMessageToolCall.id) &&
        Objects.equals(this.type, chatCompletionRequestMessageToolCall.type) &&
        Objects.equals(this.function, chatCompletionRequestMessageToolCall.function);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, function);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionRequestMessageToolCall {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ChatCompletionRequestMessageToolCall instance;

    public Builder() {
      this(new ChatCompletionRequestMessageToolCall());
    }

    protected Builder(ChatCompletionRequestMessageToolCall instance) {
      this.instance = instance;
    }

    public ChatCompletionRequestMessageToolCall.Builder id(String id) {
      this.instance.id = id;
      return this;
    }
    public ChatCompletionRequestMessageToolCall.Builder type(ToolType type) {
      this.instance.type = type;
      return this;
    }
    public ChatCompletionRequestMessageToolCall.Builder function(ChatCompletionRequestMessageToolCallFunction function) {
      this.instance.function = function;
      return this;
    }


    /**
    * returns a built ChatCompletionRequestMessageToolCall instance.
    *
    * The builder is not reusable.
    */
    public ChatCompletionRequestMessageToolCall build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ChatCompletionRequestMessageToolCall.Builder builder() {
    return new ChatCompletionRequestMessageToolCall.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ChatCompletionRequestMessageToolCall.Builder toBuilder() {
    return new ChatCompletionRequestMessageToolCall.Builder()
      .id(getId())
      .type(getType())
      .function(getFunction());
  }


}
