// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Chat Completions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.chat;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * ChatCompletionContentPartFileFile
 */
@JsonPropertyOrder({
  ChatCompletionContentPartFileFile.JSON_PROPERTY_FILE_ID,
  ChatCompletionContentPartFileFile.JSON_PROPERTY_FILE_URL,
  ChatCompletionContentPartFileFile.JSON_PROPERTY_FILE_DATA,
  ChatCompletionContentPartFileFile.JSON_PROPERTY_FILENAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ChatCompletionContentPartFileFile {
  public static final String JSON_PROPERTY_FILE_ID = "file_id";
  @javax.annotation.Nullable
  private String fileId;

  public static final String JSON_PROPERTY_FILE_URL = "file_url";
  @javax.annotation.Nullable
  private String fileUrl;

  public static final String JSON_PROPERTY_FILE_DATA = "file_data";
  @javax.annotation.Nullable
  private String fileData;

  public static final String JSON_PROPERTY_FILENAME = "filename";
  @javax.annotation.Nullable
  private String filename;

  public ChatCompletionContentPartFileFile() {
  }

  public ChatCompletionContentPartFileFile fileId(@javax.annotation.Nullable String fileId) {

    this.fileId = fileId;
    return this;
  }

  /**
   * The blob id of a file uploaded out-of-band.
   * @return fileId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileId() {
    return fileId;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileId(@javax.annotation.Nullable String fileId) {
    this.fileId = fileId;
  }

  public ChatCompletionContentPartFileFile fileUrl(@javax.annotation.Nullable String fileUrl) {

    this.fileUrl = fileUrl;
    return this;
  }

  /**
   * The URL of the file to be sent to the model.
   * @return fileUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileUrl() {
    return fileUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileUrl(@javax.annotation.Nullable String fileUrl) {
    this.fileUrl = fileUrl;
  }

  public ChatCompletionContentPartFileFile fileData(@javax.annotation.Nullable String fileData) {

    this.fileData = fileData;
    return this;
  }

  /**
   * The base64 encoded file data, used when passing the file inline.
   * @return fileData
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILE_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFileData() {
    return fileData;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileData(@javax.annotation.Nullable String fileData) {
    this.fileData = fileData;
  }

  public ChatCompletionContentPartFileFile filename(@javax.annotation.Nullable String filename) {

    this.filename = filename;
    return this;
  }

  /**
   * The name of the file, required when &#x60;file_data&#x60; is set.
   * @return filename
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILENAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilename() {
    return filename;
  }


  @JsonProperty(value = JSON_PROPERTY_FILENAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilename(@javax.annotation.Nullable String filename) {
    this.filename = filename;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionContentPartFileFile chatCompletionContentPartFileFile = (ChatCompletionContentPartFileFile) o;
    return Objects.equals(this.fileId, chatCompletionContentPartFileFile.fileId) &&
        Objects.equals(this.fileUrl, chatCompletionContentPartFileFile.fileUrl) &&
        Objects.equals(this.fileData, chatCompletionContentPartFileFile.fileData) &&
        Objects.equals(this.filename, chatCompletionContentPartFileFile.filename);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileId, fileUrl, fileData, filename);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionContentPartFileFile {\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    fileUrl: ").append(toIndentedString(fileUrl)).append("\n");
    sb.append("    fileData: ").append(toIndentedString(fileData)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ChatCompletionContentPartFileFile instance;

    public Builder() {
      this(new ChatCompletionContentPartFileFile());
    }

    protected Builder(ChatCompletionContentPartFileFile instance) {
      this.instance = instance;
    }

    public ChatCompletionContentPartFileFile.Builder fileId(String fileId) {
      this.instance.fileId = fileId;
      return this;
    }
    public ChatCompletionContentPartFileFile.Builder fileUrl(String fileUrl) {
      this.instance.fileUrl = fileUrl;
      return this;
    }
    public ChatCompletionContentPartFileFile.Builder fileData(String fileData) {
      this.instance.fileData = fileData;
      return this;
    }
    public ChatCompletionContentPartFileFile.Builder filename(String filename) {
      this.instance.filename = filename;
      return this;
    }


    /**
    * returns a built ChatCompletionContentPartFileFile instance.
    *
    * The builder is not reusable.
    */
    public ChatCompletionContentPartFileFile build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ChatCompletionContentPartFileFile.Builder builder() {
    return new ChatCompletionContentPartFileFile.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ChatCompletionContentPartFileFile.Builder toBuilder() {
    return new ChatCompletionContentPartFileFile.Builder()
      .fileId(getFileId())
      .fileUrl(getFileUrl())
      .fileData(getFileData())
      .filename(getFilename());
  }


}
