// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Chat Completions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.chat;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ChatCompletionChoiceLogprobs
 */
@JsonPropertyOrder({
  ChatCompletionChoiceLogprobs.JSON_PROPERTY_CONTENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ChatCompletionChoiceLogprobs {
  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nonnull
  private List<ChatCompletionTokenLogprob> content;

  public ChatCompletionChoiceLogprobs() {
  }

  public ChatCompletionChoiceLogprobs content(@javax.annotation.Nonnull List<ChatCompletionTokenLogprob> content) {
    
    this.content = content;
    return this;
  }

  public ChatCompletionChoiceLogprobs addContentItem(ChatCompletionTokenLogprob contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<>();
    }
    this.content.add(contentItem);
    return this;
  }

  /**
   * A list of message content tokens with log probability information.
   * @return content
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ChatCompletionTokenLogprob> getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContent(@javax.annotation.Nonnull List<ChatCompletionTokenLogprob> content) {
    this.content = content;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionChoiceLogprobs chatCompletionChoiceLogprobs = (ChatCompletionChoiceLogprobs) o;
    return Objects.equals(this.content, chatCompletionChoiceLogprobs.content);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionChoiceLogprobs {\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ChatCompletionChoiceLogprobs instance;

    public Builder() {
      this(new ChatCompletionChoiceLogprobs());
    }

    protected Builder(ChatCompletionChoiceLogprobs instance) {
      this.instance = instance;
    }

    public ChatCompletionChoiceLogprobs.Builder content(List<ChatCompletionTokenLogprob> content) {
      this.instance.content = content;
      return this;
    }


    /**
    * returns a built ChatCompletionChoiceLogprobs instance.
    *
    * The builder is not reusable.
    */
    public ChatCompletionChoiceLogprobs build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ChatCompletionChoiceLogprobs.Builder builder() {
    return new ChatCompletionChoiceLogprobs.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ChatCompletionChoiceLogprobs.Builder toBuilder() {
    return new ChatCompletionChoiceLogprobs.Builder()
      .content(getContent());
  }


}

