// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Chat Completions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.chat;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * ChatCompletionContentPartFile
 */
@JsonPropertyOrder({
  ChatCompletionContentPartFile.JSON_PROPERTY_TYPE,
  ChatCompletionContentPartFile.JSON_PROPERTY_FILE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ChatCompletionContentPartFile implements ChatCompletionContentPart {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private ChatCompletionContentPartType type = ChatCompletionContentPartType.FILE;

  public static final String JSON_PROPERTY_FILE = "file";
  @javax.annotation.Nonnull
  private ChatCompletionContentPartFileFile _file;

  public ChatCompletionContentPartFile() {
  }

  public ChatCompletionContentPartFile type(@javax.annotation.Nonnull ChatCompletionContentPartType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ChatCompletionContentPartType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull ChatCompletionContentPartType type) {
    this.type = type;
  }

  public ChatCompletionContentPartFile _file(@javax.annotation.Nonnull ChatCompletionContentPartFileFile _file) {
    
    this._file = _file;
    return this;
  }

  /**
   * Get _file
   * @return _file
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FILE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ChatCompletionContentPartFileFile getFile() {
    return _file;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFile(@javax.annotation.Nonnull ChatCompletionContentPartFileFile _file) {
    this._file = _file;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionContentPartFile chatCompletionContentPartFile = (ChatCompletionContentPartFile) o;
    return Objects.equals(this.type, chatCompletionContentPartFile.type) &&
        Objects.equals(this._file, chatCompletionContentPartFile._file);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, _file);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionContentPartFile {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    _file: ").append(toIndentedString(_file)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ChatCompletionContentPartFile instance;

    public Builder() {
      this(new ChatCompletionContentPartFile());
    }

    protected Builder(ChatCompletionContentPartFile instance) {
      this.instance = instance;
    }

    public ChatCompletionContentPartFile.Builder type(ChatCompletionContentPartType type) {
      this.instance.type = type;
      return this;
    }
    public ChatCompletionContentPartFile.Builder _file(ChatCompletionContentPartFileFile _file) {
      this.instance._file = _file;
      return this;
    }


    /**
    * returns a built ChatCompletionContentPartFile instance.
    *
    * The builder is not reusable.
    */
    public ChatCompletionContentPartFile build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ChatCompletionContentPartFile.Builder builder() {
    return new ChatCompletionContentPartFile.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ChatCompletionContentPartFile.Builder toBuilder() {
    return new ChatCompletionContentPartFile.Builder()
      .type(getType())
      ._file(getFile());
  }


}

