// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Chat Completions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.chat;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * ChatCompletionRequestUserMessage
 */
@JsonPropertyOrder({
  ChatCompletionRequestUserMessage.JSON_PROPERTY_ROLE,
  ChatCompletionRequestUserMessage.JSON_PROPERTY_CONTENT,
  ChatCompletionRequestUserMessage.JSON_PROPERTY_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ChatCompletionRequestUserMessage implements ChatCompletionRequestMessage {
  public static final String JSON_PROPERTY_ROLE = "role";
  @javax.annotation.Nonnull
  private ChatCompletionRequestMessageType role = ChatCompletionRequestMessageType.USER;

  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nonnull
  private ChatCompletionMessageContent content;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public ChatCompletionRequestUserMessage() {
  }

  public ChatCompletionRequestUserMessage role(@javax.annotation.Nonnull ChatCompletionRequestMessageType role) {

    this.role = role;
    return this;
  }

  /**
   * Get role
   * @return role
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ROLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ChatCompletionRequestMessageType getRole() {
    return role;
  }


  @JsonProperty(value = JSON_PROPERTY_ROLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRole(@javax.annotation.Nonnull ChatCompletionRequestMessageType role) {
    this.role = role;
  }

  public ChatCompletionRequestUserMessage content(@javax.annotation.Nonnull ChatCompletionMessageContent content) {

    this.content = content;
    return this;
  }

  /**
   * The contents of the user message.
   * @return content
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ChatCompletionMessageContent getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContent(@javax.annotation.Nonnull ChatCompletionMessageContent content) {
    this.content = content;
  }

  public ChatCompletionRequestUserMessage name(@javax.annotation.Nullable String name) {

    this.name = name;
    return this;
  }

  /**
   * An optional name for the participant. Provides the model information to differentiate between participants of the same role.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionRequestUserMessage chatCompletionRequestUserMessage = (ChatCompletionRequestUserMessage) o;
    return Objects.equals(this.role, chatCompletionRequestUserMessage.role) &&
        Objects.equals(this.content, chatCompletionRequestUserMessage.content) &&
        Objects.equals(this.name, chatCompletionRequestUserMessage.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(role, content, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionRequestUserMessage {\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ChatCompletionRequestUserMessage instance;

    public Builder() {
      this(new ChatCompletionRequestUserMessage());
    }

    protected Builder(ChatCompletionRequestUserMessage instance) {
      this.instance = instance;
    }

    public ChatCompletionRequestUserMessage.Builder role(ChatCompletionRequestMessageType role) {
      this.instance.role = role;
      return this;
    }
    public ChatCompletionRequestUserMessage.Builder content(ChatCompletionMessageContent content) {
      this.instance.content = content;
      return this;
    }
    public ChatCompletionRequestUserMessage.Builder name(String name) {
      this.instance.name = name;
      return this;
    }


    /**
    * returns a built ChatCompletionRequestUserMessage instance.
    *
    * The builder is not reusable.
    */
    public ChatCompletionRequestUserMessage build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ChatCompletionRequestUserMessage.Builder builder() {
    return new ChatCompletionRequestUserMessage.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ChatCompletionRequestUserMessage.Builder toBuilder() {
    return new ChatCompletionRequestUserMessage.Builder()
      .role(getRole())
      .content(getContent())
      .name(getName());
  }


}
