// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Chat Completions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.chat;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * ChatCompletionMessageToolCallChunk
 */
@JsonPropertyOrder({
  ChatCompletionMessageToolCallChunk.JSON_PROPERTY_INDEX,
  ChatCompletionMessageToolCallChunk.JSON_PROPERTY_ID,
  ChatCompletionMessageToolCallChunk.JSON_PROPERTY_TYPE,
  ChatCompletionMessageToolCallChunk.JSON_PROPERTY_FUNCTION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ChatCompletionMessageToolCallChunk {
  public static final String JSON_PROPERTY_INDEX = "index";
  @javax.annotation.Nonnull
  private Integer index;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nullable
  private String type;

  public static final String JSON_PROPERTY_FUNCTION = "function";
  @javax.annotation.Nullable
  private ChatCompletionMessageToolCallChunkFunction function;

  public ChatCompletionMessageToolCallChunk() {
  }

  public ChatCompletionMessageToolCallChunk index(@javax.annotation.Nonnull Integer index) {

    this.index = index;
    return this;
  }

  /**
   * Index of the tool call in the array of tool calls.
   * @return index
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getIndex() {
    return index;
  }


  @JsonProperty(value = JSON_PROPERTY_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIndex(@javax.annotation.Nonnull Integer index) {
    this.index = index;
  }

  public ChatCompletionMessageToolCallChunk id(@javax.annotation.Nullable String id) {

    this.id = id;
    return this;
  }

  /**
   * The ID of the tool call.
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public ChatCompletionMessageToolCallChunk type(@javax.annotation.Nullable String type) {

    this.type = type;
    return this;
  }

  /**
   * The type of the tool.
   * @return type
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }

  public ChatCompletionMessageToolCallChunk function(@javax.annotation.Nullable ChatCompletionMessageToolCallChunkFunction function) {

    this.function = function;
    return this;
  }

  /**
   * Get function
   * @return function
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FUNCTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ChatCompletionMessageToolCallChunkFunction getFunction() {
    return function;
  }


  @JsonProperty(value = JSON_PROPERTY_FUNCTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFunction(@javax.annotation.Nullable ChatCompletionMessageToolCallChunkFunction function) {
    this.function = function;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatCompletionMessageToolCallChunk chatCompletionMessageToolCallChunk = (ChatCompletionMessageToolCallChunk) o;
    return Objects.equals(this.index, chatCompletionMessageToolCallChunk.index) &&
        Objects.equals(this.id, chatCompletionMessageToolCallChunk.id) &&
        Objects.equals(this.type, chatCompletionMessageToolCallChunk.type) &&
        Objects.equals(this.function, chatCompletionMessageToolCallChunk.function);
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, id, type, function);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatCompletionMessageToolCallChunk {\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    function: ").append(toIndentedString(function)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ChatCompletionMessageToolCallChunk instance;

    public Builder() {
      this(new ChatCompletionMessageToolCallChunk());
    }

    protected Builder(ChatCompletionMessageToolCallChunk instance) {
      this.instance = instance;
    }

    public ChatCompletionMessageToolCallChunk.Builder index(Integer index) {
      this.instance.index = index;
      return this;
    }
    public ChatCompletionMessageToolCallChunk.Builder id(String id) {
      this.instance.id = id;
      return this;
    }
    public ChatCompletionMessageToolCallChunk.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public ChatCompletionMessageToolCallChunk.Builder function(ChatCompletionMessageToolCallChunkFunction function) {
      this.instance.function = function;
      return this;
    }


    /**
    * returns a built ChatCompletionMessageToolCallChunk instance.
    *
    * The builder is not reusable.
    */
    public ChatCompletionMessageToolCallChunk build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ChatCompletionMessageToolCallChunk.Builder builder() {
    return new ChatCompletionMessageToolCallChunk.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ChatCompletionMessageToolCallChunk.Builder toBuilder() {
    return new ChatCompletionMessageToolCallChunk.Builder()
      .index(getIndex())
      .id(getId())
      .type(getType())
      .function(getFunction());
  }


}
