// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Chat Completions API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.chat;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * FunctionObject
 */
@JsonPropertyOrder({
  FunctionObject.JSON_PROPERTY_NAME,
  FunctionObject.JSON_PROPERTY_DESCRIPTION,
  FunctionObject.JSON_PROPERTY_PARAMETERS,
  FunctionObject.JSON_PROPERTY_STRICT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class FunctionObject {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_PARAMETERS = "parameters";
  @javax.annotation.Nullable
  private Map<String, Object> parameters;

  public static final String JSON_PROPERTY_STRICT = "strict";
  @javax.annotation.Nullable
  private Boolean strict;

  public FunctionObject() {
  }

  public FunctionObject name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public FunctionObject description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * A description of what the function does, used by the model to choose when and how to call the function.
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public FunctionObject parameters(@javax.annotation.Nullable Map<String, Object> parameters) {
    
    this.parameters = parameters;
    return this;
  }

  public FunctionObject putParametersItem(String key, Object parametersItem) {
    if (this.parameters == null) {
      this.parameters = new HashMap<>();
    }
    this.parameters.put(key, parametersItem);
    return this;
  }

  /**
   * The parameters the function accepts, described as a JSON Schema object. Omitting &#x60;parameters&#x60; defines a function with an empty parameter list.
   * @return parameters
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARAMETERS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.NON_EMPTY)

  public Map<String, Object> getParameters() {
    return parameters;
  }


  @JsonProperty(value = JSON_PROPERTY_PARAMETERS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.NON_EMPTY)
  public void setParameters(@javax.annotation.Nullable Map<String, Object> parameters) {
    this.parameters = parameters;
  }

  public FunctionObject strict(@javax.annotation.Nullable Boolean strict) {
    
    this.strict = strict;
    return this;
  }

  /**
   * Whether to enable strict schema adherence when generating the function call.
   * @return strict
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STRICT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getStrict() {
    return strict;
  }


  @JsonProperty(value = JSON_PROPERTY_STRICT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStrict(@javax.annotation.Nullable Boolean strict) {
    this.strict = strict;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FunctionObject functionObject = (FunctionObject) o;
    return Objects.equals(this.name, functionObject.name) &&
        Objects.equals(this.description, functionObject.description) &&
        Objects.equals(this.parameters, functionObject.parameters) &&
        Objects.equals(this.strict, functionObject.strict);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, parameters, strict);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FunctionObject {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    strict: ").append(toIndentedString(strict)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private FunctionObject instance;

    public Builder() {
      this(new FunctionObject());
    }

    protected Builder(FunctionObject instance) {
      this.instance = instance;
    }

    public FunctionObject.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public FunctionObject.Builder description(String description) {
      this.instance.description = description;
      return this;
    }
    public FunctionObject.Builder parameters(Map<String, Object> parameters) {
      this.instance.parameters = parameters;
      return this;
    }
    public FunctionObject.Builder strict(Boolean strict) {
      this.instance.strict = strict;
      return this;
    }


    /**
    * returns a built FunctionObject instance.
    *
    * The builder is not reusable.
    */
    public FunctionObject build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static FunctionObject.Builder builder() {
    return new FunctionObject.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public FunctionObject.Builder toBuilder() {
    return new FunctionObject.Builder()
      .name(getName())
      .description(getDescription())
      .parameters(getParameters())
      .strict(getStrict());
  }


}

