// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Managed Agents Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.agent;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * coordinator Agent 编排的下属 Agent 引用。
 */
@JsonPropertyOrder({
  AgentRef.JSON_PROPERTY_TYPE,
  AgentRef.JSON_PROPERTY_ID,
  AgentRef.JSON_PROPERTY_VERSION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class AgentRef {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private AgentRefType type;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_VERSION = "version";
  @javax.annotation.Nullable
  private Integer version;

  public AgentRef() {
  }

  public AgentRef type(@javax.annotation.Nonnull AgentRefType type) {

    this.type = type;
    return this;
  }

  /**
   * 引用类型。
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AgentRefType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull AgentRefType type) {
    this.type = type;
  }

  public AgentRef id(@javax.annotation.Nullable String id) {

    this.id = id;
    return this;
  }

  /**
   * 被引用 Agent 的 ID。
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public AgentRef version(@javax.annotation.Nullable Integer version) {

    this.version = version;
    return this;
  }

  /**
   * 被引用 Agent 的版本号。
   * @return version
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(@javax.annotation.Nullable Integer version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgentRef agentRef = (AgentRef) o;
    return Objects.equals(this.type, agentRef.type) &&
        Objects.equals(this.id, agentRef.id) &&
        Objects.equals(this.version, agentRef.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, id, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentRef {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private AgentRef instance;

    public Builder() {
      this(new AgentRef());
    }

    protected Builder(AgentRef instance) {
      this.instance = instance;
    }

    public AgentRef.Builder type(AgentRefType type) {
      this.instance.type = type;
      return this;
    }
    public AgentRef.Builder id(String id) {
      this.instance.id = id;
      return this;
    }
    public AgentRef.Builder version(Integer version) {
      this.instance.version = version;
      return this;
    }


    /**
    * returns a built AgentRef instance.
    *
    * The builder is not reusable.
    */
    public AgentRef build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static AgentRef.Builder builder() {
    return new AgentRef.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public AgentRef.Builder toBuilder() {
    return new AgentRef.Builder()
      .type(getType())
      .id(getId())
      .version(getVersion());
  }


}
