// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Managed Agents Agent API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.agent;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * List Agents / List Agent Versions 响应体。
 */
@JsonPropertyOrder({
  ListAgentsResponse.JSON_PROPERTY_DATA,
  ListAgentsResponse.JSON_PROPERTY_NEXT_PAGE,
  ListAgentsResponse.JSON_PROPERTY_TOTAL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ListAgentsResponse {
  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nonnull
  private List<Agent> data;

  public static final String JSON_PROPERTY_NEXT_PAGE = "next_page";
  @javax.annotation.Nullable
  private String nextPage;

  public static final String JSON_PROPERTY_TOTAL = "total";
  @javax.annotation.Nullable
  private Long total;

  public ListAgentsResponse() {
  }

  public ListAgentsResponse data(@javax.annotation.Nonnull List<Agent> data) {
    
    this.data = data;
    return this;
  }

  public ListAgentsResponse addDataItem(Agent dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * 本页 Agent 列表。
   * @return data
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Agent> getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(@javax.annotation.Nonnull List<Agent> data) {
    this.data = data;
  }

  public ListAgentsResponse nextPage(@javax.annotation.Nullable String nextPage) {
    
    this.nextPage = nextPage;
    return this;
  }

  /**
   * 下一页页码；无更多数据时为空字符串或缺省。
   * @return nextPage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NEXT_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNextPage() {
    return nextPage;
  }


  @JsonProperty(value = JSON_PROPERTY_NEXT_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNextPage(@javax.annotation.Nullable String nextPage) {
    this.nextPage = nextPage;
  }

  public ListAgentsResponse total(@javax.annotation.Nullable Long total) {
    
    this.total = total;
    return this;
  }

  /**
   * 命中总条数（可选，服务器决定是否返回）。
   * @return total
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotal() {
    return total;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotal(@javax.annotation.Nullable Long total) {
    this.total = total;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListAgentsResponse listAgentsResponse = (ListAgentsResponse) o;
    return Objects.equals(this.data, listAgentsResponse.data) &&
        Objects.equals(this.nextPage, listAgentsResponse.nextPage) &&
        Objects.equals(this.total, listAgentsResponse.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, nextPage, total);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListAgentsResponse {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    nextPage: ").append(toIndentedString(nextPage)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ListAgentsResponse instance;

    public Builder() {
      this(new ListAgentsResponse());
    }

    protected Builder(ListAgentsResponse instance) {
      this.instance = instance;
    }

    public ListAgentsResponse.Builder data(List<Agent> data) {
      this.instance.data = data;
      return this;
    }
    public ListAgentsResponse.Builder nextPage(String nextPage) {
      this.instance.nextPage = nextPage;
      return this;
    }
    public ListAgentsResponse.Builder total(Long total) {
      this.instance.total = total;
      return this;
    }


    /**
    * returns a built ListAgentsResponse instance.
    *
    * The builder is not reusable.
    */
    public ListAgentsResponse build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ListAgentsResponse.Builder builder() {
    return new ListAgentsResponse.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ListAgentsResponse.Builder toBuilder() {
    return new ListAgentsResponse.Builder()
      .data(getData())
      .nextPage(getNextPage())
      .total(getTotal());
  }


}

