// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Responses API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.responses;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * DoubaoAppFeature
 */
@JsonPropertyOrder({
  DoubaoAppFeature.JSON_PROPERTY_CHAT,
  DoubaoAppFeature.JSON_PROPERTY_DEEP_CHAT,
  DoubaoAppFeature.JSON_PROPERTY_AI_SEARCH,
  DoubaoAppFeature.JSON_PROPERTY_REASONING_SEARCH
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class DoubaoAppFeature {
  public static final String JSON_PROPERTY_CHAT = "chat";
  @javax.annotation.Nullable
  private DoubaoAppFeatureItem chat;

  public static final String JSON_PROPERTY_DEEP_CHAT = "deep_chat";
  @javax.annotation.Nullable
  private DoubaoAppFeatureItem deepChat;

  public static final String JSON_PROPERTY_AI_SEARCH = "ai_search";
  @javax.annotation.Nullable
  private DoubaoAppFeatureItem aiSearch;

  public static final String JSON_PROPERTY_REASONING_SEARCH = "reasoning_search";
  @javax.annotation.Nullable
  private DoubaoAppFeatureItem reasoningSearch;

  public DoubaoAppFeature() {
  }

  public DoubaoAppFeature chat(@javax.annotation.Nullable DoubaoAppFeatureItem chat) {

    this.chat = chat;
    return this;
  }

  /**
   * Get chat
   * @return chat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DoubaoAppFeatureItem getChat() {
    return chat;
  }


  @JsonProperty(value = JSON_PROPERTY_CHAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChat(@javax.annotation.Nullable DoubaoAppFeatureItem chat) {
    this.chat = chat;
  }

  public DoubaoAppFeature deepChat(@javax.annotation.Nullable DoubaoAppFeatureItem deepChat) {

    this.deepChat = deepChat;
    return this;
  }

  /**
   * Get deepChat
   * @return deepChat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEEP_CHAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DoubaoAppFeatureItem getDeepChat() {
    return deepChat;
  }


  @JsonProperty(value = JSON_PROPERTY_DEEP_CHAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeepChat(@javax.annotation.Nullable DoubaoAppFeatureItem deepChat) {
    this.deepChat = deepChat;
  }

  public DoubaoAppFeature aiSearch(@javax.annotation.Nullable DoubaoAppFeatureItem aiSearch) {

    this.aiSearch = aiSearch;
    return this;
  }

  /**
   * Get aiSearch
   * @return aiSearch
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AI_SEARCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DoubaoAppFeatureItem getAiSearch() {
    return aiSearch;
  }


  @JsonProperty(value = JSON_PROPERTY_AI_SEARCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAiSearch(@javax.annotation.Nullable DoubaoAppFeatureItem aiSearch) {
    this.aiSearch = aiSearch;
  }

  public DoubaoAppFeature reasoningSearch(@javax.annotation.Nullable DoubaoAppFeatureItem reasoningSearch) {

    this.reasoningSearch = reasoningSearch;
    return this;
  }

  /**
   * Get reasoningSearch
   * @return reasoningSearch
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REASONING_SEARCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DoubaoAppFeatureItem getReasoningSearch() {
    return reasoningSearch;
  }


  @JsonProperty(value = JSON_PROPERTY_REASONING_SEARCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReasoningSearch(@javax.annotation.Nullable DoubaoAppFeatureItem reasoningSearch) {
    this.reasoningSearch = reasoningSearch;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DoubaoAppFeature doubaoAppFeature = (DoubaoAppFeature) o;
    return Objects.equals(this.chat, doubaoAppFeature.chat) &&
        Objects.equals(this.deepChat, doubaoAppFeature.deepChat) &&
        Objects.equals(this.aiSearch, doubaoAppFeature.aiSearch) &&
        Objects.equals(this.reasoningSearch, doubaoAppFeature.reasoningSearch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chat, deepChat, aiSearch, reasoningSearch);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DoubaoAppFeature {\n");
    sb.append("    chat: ").append(toIndentedString(chat)).append("\n");
    sb.append("    deepChat: ").append(toIndentedString(deepChat)).append("\n");
    sb.append("    aiSearch: ").append(toIndentedString(aiSearch)).append("\n");
    sb.append("    reasoningSearch: ").append(toIndentedString(reasoningSearch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private DoubaoAppFeature instance;

    public Builder() {
      this(new DoubaoAppFeature());
    }

    protected Builder(DoubaoAppFeature instance) {
      this.instance = instance;
    }

    public DoubaoAppFeature.Builder chat(DoubaoAppFeatureItem chat) {
      this.instance.chat = chat;
      return this;
    }
    public DoubaoAppFeature.Builder deepChat(DoubaoAppFeatureItem deepChat) {
      this.instance.deepChat = deepChat;
      return this;
    }
    public DoubaoAppFeature.Builder aiSearch(DoubaoAppFeatureItem aiSearch) {
      this.instance.aiSearch = aiSearch;
      return this;
    }
    public DoubaoAppFeature.Builder reasoningSearch(DoubaoAppFeatureItem reasoningSearch) {
      this.instance.reasoningSearch = reasoningSearch;
      return this;
    }


    /**
    * returns a built DoubaoAppFeature instance.
    *
    * The builder is not reusable.
    */
    public DoubaoAppFeature build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static DoubaoAppFeature.Builder builder() {
    return new DoubaoAppFeature.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public DoubaoAppFeature.Builder toBuilder() {
    return new DoubaoAppFeature.Builder()
      .chat(getChat())
      .deepChat(getDeepChat())
      .aiSearch(getAiSearch())
      .reasoningSearch(getReasoningSearch());
  }


}
