// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Responses API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.responses;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * ItemFunctionToolCall
 */
@JsonPropertyOrder({
  ItemFunctionToolCall.JSON_PROPERTY_ID,
  ItemFunctionToolCall.JSON_PROPERTY_TYPE,
  ItemFunctionToolCall.JSON_PROPERTY_ARGUMENTS,
  ItemFunctionToolCall.JSON_PROPERTY_CALL_ID,
  ItemFunctionToolCall.JSON_PROPERTY_NAME,
  ItemFunctionToolCall.JSON_PROPERTY_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ItemFunctionToolCall implements InputItem, OutputItem {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private ItemType type = ItemType.FUNCTION_CALL;

  public static final String JSON_PROPERTY_ARGUMENTS = "arguments";
  @javax.annotation.Nullable
  private String arguments;

  public static final String JSON_PROPERTY_CALL_ID = "call_id";
  @javax.annotation.Nullable
  private String callId;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private ItemStatus status;

  public ItemFunctionToolCall() {
  }

  public ItemFunctionToolCall id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * The unique ID of the function tool call.
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  public ItemFunctionToolCall type(@javax.annotation.Nonnull ItemType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ItemType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull ItemType type) {
    this.type = type;
  }

  public ItemFunctionToolCall arguments(@javax.annotation.Nullable String arguments) {
    
    this.arguments = arguments;
    return this;
  }

  /**
   * A JSON string of the arguments passed to the function.
   * @return arguments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARGUMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getArguments() {
    return arguments;
  }


  @JsonProperty(value = JSON_PROPERTY_ARGUMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArguments(@javax.annotation.Nullable String arguments) {
    this.arguments = arguments;
  }

  public ItemFunctionToolCall callId(@javax.annotation.Nullable String callId) {
    
    this.callId = callId;
    return this;
  }

  /**
   * The ID of the call that produced this tool call.
   * @return callId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CALL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCallId() {
    return callId;
  }


  @JsonProperty(value = JSON_PROPERTY_CALL_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallId(@javax.annotation.Nullable String callId) {
    this.callId = callId;
  }

  public ItemFunctionToolCall name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of the function to call.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public ItemFunctionToolCall status(@javax.annotation.Nullable ItemStatus status) {
    
    this.status = status;
    return this;
  }

  /**
   * The status of the item.
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ItemStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable ItemStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemFunctionToolCall itemFunctionToolCall = (ItemFunctionToolCall) o;
    return Objects.equals(this.id, itemFunctionToolCall.id) &&
        Objects.equals(this.type, itemFunctionToolCall.type) &&
        Objects.equals(this.arguments, itemFunctionToolCall.arguments) &&
        Objects.equals(this.callId, itemFunctionToolCall.callId) &&
        Objects.equals(this.name, itemFunctionToolCall.name) &&
        Objects.equals(this.status, itemFunctionToolCall.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, arguments, callId, name, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemFunctionToolCall {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    arguments: ").append(toIndentedString(arguments)).append("\n");
    sb.append("    callId: ").append(toIndentedString(callId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ItemFunctionToolCall instance;

    public Builder() {
      this(new ItemFunctionToolCall());
    }

    protected Builder(ItemFunctionToolCall instance) {
      this.instance = instance;
    }

    public ItemFunctionToolCall.Builder id(String id) {
      this.instance.id = id;
      return this;
    }
    public ItemFunctionToolCall.Builder type(ItemType type) {
      this.instance.type = type;
      return this;
    }
    public ItemFunctionToolCall.Builder arguments(String arguments) {
      this.instance.arguments = arguments;
      return this;
    }
    public ItemFunctionToolCall.Builder callId(String callId) {
      this.instance.callId = callId;
      return this;
    }
    public ItemFunctionToolCall.Builder name(String name) {
      this.instance.name = name;
      return this;
    }
    public ItemFunctionToolCall.Builder status(ItemStatus status) {
      this.instance.status = status;
      return this;
    }


    /**
    * returns a built ItemFunctionToolCall instance.
    *
    * The builder is not reusable.
    */
    public ItemFunctionToolCall build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ItemFunctionToolCall.Builder builder() {
    return new ItemFunctionToolCall.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ItemFunctionToolCall.Builder toBuilder() {
    return new ItemFunctionToolCall.Builder()
      .id(getId())
      .type(getType())
      .arguments(getArguments())
      .callId(getCallId())
      .name(getName())
      .status(getStatus());
  }


}

