// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Responses API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.responses;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ItemFunctionKnowledgeSearch
 */
@JsonPropertyOrder({
  ItemFunctionKnowledgeSearch.JSON_PROPERTY_TYPE,
  ItemFunctionKnowledgeSearch.JSON_PROPERTY_QUERIES,
  ItemFunctionKnowledgeSearch.JSON_PROPERTY_KNOWLEDGE_RESOURCE_ID,
  ItemFunctionKnowledgeSearch.JSON_PROPERTY_STATUS,
  ItemFunctionKnowledgeSearch.JSON_PROPERTY_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ItemFunctionKnowledgeSearch implements OutputItem {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private ItemType type = ItemType.KNOWLEDGE_SEARCH_CALL;

  public static final String JSON_PROPERTY_QUERIES = "queries";
  @javax.annotation.Nonnull
  private List<String> queries;

  public static final String JSON_PROPERTY_KNOWLEDGE_RESOURCE_ID = "knowledge_resource_id";
  @javax.annotation.Nonnull
  private String knowledgeResourceId;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private ItemStatus status;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public ItemFunctionKnowledgeSearch() {
  }

  public ItemFunctionKnowledgeSearch type(@javax.annotation.Nonnull ItemType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ItemType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull ItemType type) {
    this.type = type;
  }

  public ItemFunctionKnowledgeSearch queries(@javax.annotation.Nonnull List<String> queries) {
    
    this.queries = queries;
    return this;
  }

  public ItemFunctionKnowledgeSearch addQueriesItem(String queriesItem) {
    if (this.queries == null) {
      this.queries = new ArrayList<>();
    }
    this.queries.add(queriesItem);
    return this;
  }

  /**
   * Get queries
   * @return queries
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUERIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getQueries() {
    return queries;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQueries(@javax.annotation.Nonnull List<String> queries) {
    this.queries = queries;
  }

  public ItemFunctionKnowledgeSearch knowledgeResourceId(@javax.annotation.Nonnull String knowledgeResourceId) {
    
    this.knowledgeResourceId = knowledgeResourceId;
    return this;
  }

  /**
   * Get knowledgeResourceId
   * @return knowledgeResourceId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KNOWLEDGE_RESOURCE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKnowledgeResourceId() {
    return knowledgeResourceId;
  }


  @JsonProperty(value = JSON_PROPERTY_KNOWLEDGE_RESOURCE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKnowledgeResourceId(@javax.annotation.Nonnull String knowledgeResourceId) {
    this.knowledgeResourceId = knowledgeResourceId;
  }

  public ItemFunctionKnowledgeSearch status(@javax.annotation.Nonnull ItemStatus status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ItemStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull ItemStatus status) {
    this.status = status;
  }

  public ItemFunctionKnowledgeSearch id(@javax.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemFunctionKnowledgeSearch itemFunctionKnowledgeSearch = (ItemFunctionKnowledgeSearch) o;
    return Objects.equals(this.type, itemFunctionKnowledgeSearch.type) &&
        Objects.equals(this.queries, itemFunctionKnowledgeSearch.queries) &&
        Objects.equals(this.knowledgeResourceId, itemFunctionKnowledgeSearch.knowledgeResourceId) &&
        Objects.equals(this.status, itemFunctionKnowledgeSearch.status) &&
        Objects.equals(this.id, itemFunctionKnowledgeSearch.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, queries, knowledgeResourceId, status, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemFunctionKnowledgeSearch {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    queries: ").append(toIndentedString(queries)).append("\n");
    sb.append("    knowledgeResourceId: ").append(toIndentedString(knowledgeResourceId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ItemFunctionKnowledgeSearch instance;

    public Builder() {
      this(new ItemFunctionKnowledgeSearch());
    }

    protected Builder(ItemFunctionKnowledgeSearch instance) {
      this.instance = instance;
    }

    public ItemFunctionKnowledgeSearch.Builder type(ItemType type) {
      this.instance.type = type;
      return this;
    }
    public ItemFunctionKnowledgeSearch.Builder queries(List<String> queries) {
      this.instance.queries = queries;
      return this;
    }
    public ItemFunctionKnowledgeSearch.Builder knowledgeResourceId(String knowledgeResourceId) {
      this.instance.knowledgeResourceId = knowledgeResourceId;
      return this;
    }
    public ItemFunctionKnowledgeSearch.Builder status(ItemStatus status) {
      this.instance.status = status;
      return this;
    }
    public ItemFunctionKnowledgeSearch.Builder id(String id) {
      this.instance.id = id;
      return this;
    }


    /**
    * returns a built ItemFunctionKnowledgeSearch instance.
    *
    * The builder is not reusable.
    */
    public ItemFunctionKnowledgeSearch build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ItemFunctionKnowledgeSearch.Builder builder() {
    return new ItemFunctionKnowledgeSearch.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ItemFunctionKnowledgeSearch.Builder toBuilder() {
    return new ItemFunctionKnowledgeSearch.Builder()
      .type(getType())
      .queries(getQueries())
      .knowledgeResourceId(getKnowledgeResourceId())
      .status(getStatus())
      .id(getId());
  }


}

