// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Responses API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.responses;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * ResponseMcpApprovalRequestEvent
 */
@JsonPropertyOrder({
  ResponseMcpApprovalRequestEvent.JSON_PROPERTY_TYPE,
  ResponseMcpApprovalRequestEvent.JSON_PROPERTY_FUNCTION_MCP_APPROVAL_REQUEST,
  ResponseMcpApprovalRequestEvent.JSON_PROPERTY_OUTPUT_INDEX,
  ResponseMcpApprovalRequestEvent.JSON_PROPERTY_SEQUENCE_NUMBER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ResponseMcpApprovalRequestEvent implements ResponseStreamEvent {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private ResponseStreamEventType type = ResponseStreamEventType.RESPONSE_MCP_APPROVAL_REQUEST;

  public static final String JSON_PROPERTY_FUNCTION_MCP_APPROVAL_REQUEST = "function_mcp_approval_request";
  @javax.annotation.Nonnull
  private ItemFunctionMcpApprovalRequest functionMcpApprovalRequest;

  public static final String JSON_PROPERTY_OUTPUT_INDEX = "output_index";
  @javax.annotation.Nonnull
  private Long outputIndex;

  public static final String JSON_PROPERTY_SEQUENCE_NUMBER = "sequence_number";
  @javax.annotation.Nonnull
  private Long sequenceNumber;

  public ResponseMcpApprovalRequestEvent() {
  }

  public ResponseMcpApprovalRequestEvent type(@javax.annotation.Nonnull ResponseStreamEventType type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ResponseStreamEventType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull ResponseStreamEventType type) {
    this.type = type;
  }

  public ResponseMcpApprovalRequestEvent functionMcpApprovalRequest(@javax.annotation.Nonnull ItemFunctionMcpApprovalRequest functionMcpApprovalRequest) {

    this.functionMcpApprovalRequest = functionMcpApprovalRequest;
    return this;
  }

  /**
   * Get functionMcpApprovalRequest
   * @return functionMcpApprovalRequest
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FUNCTION_MCP_APPROVAL_REQUEST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ItemFunctionMcpApprovalRequest getFunctionMcpApprovalRequest() {
    return functionMcpApprovalRequest;
  }


  @JsonProperty(value = JSON_PROPERTY_FUNCTION_MCP_APPROVAL_REQUEST, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFunctionMcpApprovalRequest(@javax.annotation.Nonnull ItemFunctionMcpApprovalRequest functionMcpApprovalRequest) {
    this.functionMcpApprovalRequest = functionMcpApprovalRequest;
  }

  public ResponseMcpApprovalRequestEvent outputIndex(@javax.annotation.Nonnull Long outputIndex) {

    this.outputIndex = outputIndex;
    return this;
  }

  /**
   * Get outputIndex
   * @return outputIndex
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTPUT_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getOutputIndex() {
    return outputIndex;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTPUT_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutputIndex(@javax.annotation.Nonnull Long outputIndex) {
    this.outputIndex = outputIndex;
  }

  public ResponseMcpApprovalRequestEvent sequenceNumber(@javax.annotation.Nonnull Long sequenceNumber) {

    this.sequenceNumber = sequenceNumber;
    return this;
  }

  /**
   * Get sequenceNumber
   * @return sequenceNumber
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getSequenceNumber() {
    return sequenceNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSequenceNumber(@javax.annotation.Nonnull Long sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseMcpApprovalRequestEvent responseMcpApprovalRequestEvent = (ResponseMcpApprovalRequestEvent) o;
    return Objects.equals(this.type, responseMcpApprovalRequestEvent.type) &&
        Objects.equals(this.functionMcpApprovalRequest, responseMcpApprovalRequestEvent.functionMcpApprovalRequest) &&
        Objects.equals(this.outputIndex, responseMcpApprovalRequestEvent.outputIndex) &&
        Objects.equals(this.sequenceNumber, responseMcpApprovalRequestEvent.sequenceNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, functionMcpApprovalRequest, outputIndex, sequenceNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseMcpApprovalRequestEvent {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    functionMcpApprovalRequest: ").append(toIndentedString(functionMcpApprovalRequest)).append("\n");
    sb.append("    outputIndex: ").append(toIndentedString(outputIndex)).append("\n");
    sb.append("    sequenceNumber: ").append(toIndentedString(sequenceNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ResponseMcpApprovalRequestEvent instance;

    public Builder() {
      this(new ResponseMcpApprovalRequestEvent());
    }

    protected Builder(ResponseMcpApprovalRequestEvent instance) {
      this.instance = instance;
    }

    public ResponseMcpApprovalRequestEvent.Builder type(ResponseStreamEventType type) {
      this.instance.type = type;
      return this;
    }
    public ResponseMcpApprovalRequestEvent.Builder functionMcpApprovalRequest(ItemFunctionMcpApprovalRequest functionMcpApprovalRequest) {
      this.instance.functionMcpApprovalRequest = functionMcpApprovalRequest;
      return this;
    }
    public ResponseMcpApprovalRequestEvent.Builder outputIndex(Long outputIndex) {
      this.instance.outputIndex = outputIndex;
      return this;
    }
    public ResponseMcpApprovalRequestEvent.Builder sequenceNumber(Long sequenceNumber) {
      this.instance.sequenceNumber = sequenceNumber;
      return this;
    }


    /**
    * returns a built ResponseMcpApprovalRequestEvent instance.
    *
    * The builder is not reusable.
    */
    public ResponseMcpApprovalRequestEvent build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ResponseMcpApprovalRequestEvent.Builder builder() {
    return new ResponseMcpApprovalRequestEvent.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ResponseMcpApprovalRequestEvent.Builder toBuilder() {
    return new ResponseMcpApprovalRequestEvent.Builder()
      .type(getType())
      .functionMcpApprovalRequest(getFunctionMcpApprovalRequest())
      .outputIndex(getOutputIndex())
      .sequenceNumber(getSequenceNumber());
  }


}
