// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Responses API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.volcengine.ark.runtime.models.responses;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.io.IOException;
import java.util.Objects;

/**
 * ResponsesInput
 *
 * Naked-union holder generated by gen/java/postprocess.py from the openapi
 * anyOf schema (variants: String, java.util.List<InputItem>).
 *
 * The Jackson apache-httpclient template openapi-generator runs against
 * does not support non-discriminated anyOf/oneOf — it either drops to a
 * degenerate empty shell or flattens one variant's fields onto the class,
 * losing the others. This postprocess rewrite replaces the parent with a
 * @JsonValue holder + typed static factories for write-side, plus a custom
 * @JsonDeserialize that dispatches by JsonNode shape on the read-side so
 * round-trips preserve variant types (string -> typed primitive/enum,
 * object -> typed model, array -> typed List).
 */
@JsonDeserialize(using = ResponsesInput.Deserializer.class)
public class ResponsesInput {

  private final Object value;

  @JsonCreator
  public ResponsesInput(Object value) {
    this.value = value;
  }

  public ResponsesInput() {
    this.value = null;
  }

  public static ResponsesInput ofString(String value) {
    return new ResponsesInput(value);
  }

  public static ResponsesInput ofList(java.util.List<InputItem> value) {
    return new ResponsesInput(value);
  }

  @JsonValue
  public Object getValue() {
    return this.value;
  }

  public static class Deserializer extends JsonDeserializer<ResponsesInput> {
    @Override
    public ResponsesInput deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
      ObjectMapper mapper = (ObjectMapper) p.getCodec();
      JsonNode node = mapper.readTree(p);
      if (node.isTextual()) {
        return new ResponsesInput(mapper.treeToValue(node, String.class));
      }
      if (node.isArray()) {
        return new ResponsesInput(
            mapper.convertValue(node, new com.fasterxml.jackson.core.type.TypeReference<java.util.List<InputItem>>() {}));
      }
      throw ctxt.weirdStringException(
          node == null ? "null" : node.toString(),
          ResponsesInput.class,
          "no ResponsesInput variant matched JSON node shape");
    }
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    ResponsesInput other = (ResponsesInput) o;
    return Objects.equals(this.value, other.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.value);
  }

  @Override
  public String toString() {
    return "class ResponsesInput {" + Objects.toString(value) + "}";
  }

  public static class Builder {
    private Object value;
    public Builder() {}
    public Builder value(Object value) { this.value = value; return this; }
    public ResponsesInput build() { return new ResponsesInput(this.value); }
  }

  public static ResponsesInput.Builder builder() { return new ResponsesInput.Builder(); }

  public ResponsesInput.Builder toBuilder() {
    return new ResponsesInput.Builder().value(this.value);
  }
}
