// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Responses API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.responses;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * ResponseFunctionCallArgumentsDoneEvent
 */
@JsonPropertyOrder({
  ResponseFunctionCallArgumentsDoneEvent.JSON_PROPERTY_TYPE,
  ResponseFunctionCallArgumentsDoneEvent.JSON_PROPERTY_ARGUMENTS,
  ResponseFunctionCallArgumentsDoneEvent.JSON_PROPERTY_ITEM_ID,
  ResponseFunctionCallArgumentsDoneEvent.JSON_PROPERTY_OUTPUT_INDEX,
  ResponseFunctionCallArgumentsDoneEvent.JSON_PROPERTY_SEQUENCE_NUMBER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ResponseFunctionCallArgumentsDoneEvent implements ResponseStreamEvent {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private ResponseStreamEventType type = ResponseStreamEventType.RESPONSE_FUNCTION_CALL_ARGUMENTS_DONE;

  public static final String JSON_PROPERTY_ARGUMENTS = "arguments";
  @javax.annotation.Nullable
  private String arguments;

  public static final String JSON_PROPERTY_ITEM_ID = "item_id";
  @javax.annotation.Nonnull
  private String itemId;

  public static final String JSON_PROPERTY_OUTPUT_INDEX = "output_index";
  @javax.annotation.Nonnull
  private Long outputIndex;

  public static final String JSON_PROPERTY_SEQUENCE_NUMBER = "sequence_number";
  @javax.annotation.Nonnull
  private Long sequenceNumber;

  public ResponseFunctionCallArgumentsDoneEvent() {
  }

  public ResponseFunctionCallArgumentsDoneEvent type(@javax.annotation.Nonnull ResponseStreamEventType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ResponseStreamEventType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull ResponseStreamEventType type) {
    this.type = type;
  }

  public ResponseFunctionCallArgumentsDoneEvent arguments(@javax.annotation.Nullable String arguments) {
    
    this.arguments = arguments;
    return this;
  }

  /**
   * The function-call arguments.
   * @return arguments
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARGUMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getArguments() {
    return arguments;
  }


  @JsonProperty(value = JSON_PROPERTY_ARGUMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArguments(@javax.annotation.Nullable String arguments) {
    this.arguments = arguments;
  }

  public ResponseFunctionCallArgumentsDoneEvent itemId(@javax.annotation.Nonnull String itemId) {
    
    this.itemId = itemId;
    return this;
  }

  /**
   * The ID of the item.
   * @return itemId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ITEM_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getItemId() {
    return itemId;
  }


  @JsonProperty(value = JSON_PROPERTY_ITEM_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setItemId(@javax.annotation.Nonnull String itemId) {
    this.itemId = itemId;
  }

  public ResponseFunctionCallArgumentsDoneEvent outputIndex(@javax.annotation.Nonnull Long outputIndex) {
    
    this.outputIndex = outputIndex;
    return this;
  }

  /**
   * The index of the output item.
   * @return outputIndex
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTPUT_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getOutputIndex() {
    return outputIndex;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTPUT_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutputIndex(@javax.annotation.Nonnull Long outputIndex) {
    this.outputIndex = outputIndex;
  }

  public ResponseFunctionCallArgumentsDoneEvent sequenceNumber(@javax.annotation.Nonnull Long sequenceNumber) {
    
    this.sequenceNumber = sequenceNumber;
    return this;
  }

  /**
   * The sequence number of this event.
   * @return sequenceNumber
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getSequenceNumber() {
    return sequenceNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSequenceNumber(@javax.annotation.Nonnull Long sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseFunctionCallArgumentsDoneEvent responseFunctionCallArgumentsDoneEvent = (ResponseFunctionCallArgumentsDoneEvent) o;
    return Objects.equals(this.type, responseFunctionCallArgumentsDoneEvent.type) &&
        Objects.equals(this.arguments, responseFunctionCallArgumentsDoneEvent.arguments) &&
        Objects.equals(this.itemId, responseFunctionCallArgumentsDoneEvent.itemId) &&
        Objects.equals(this.outputIndex, responseFunctionCallArgumentsDoneEvent.outputIndex) &&
        Objects.equals(this.sequenceNumber, responseFunctionCallArgumentsDoneEvent.sequenceNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, arguments, itemId, outputIndex, sequenceNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseFunctionCallArgumentsDoneEvent {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    arguments: ").append(toIndentedString(arguments)).append("\n");
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    outputIndex: ").append(toIndentedString(outputIndex)).append("\n");
    sb.append("    sequenceNumber: ").append(toIndentedString(sequenceNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ResponseFunctionCallArgumentsDoneEvent instance;

    public Builder() {
      this(new ResponseFunctionCallArgumentsDoneEvent());
    }

    protected Builder(ResponseFunctionCallArgumentsDoneEvent instance) {
      this.instance = instance;
    }

    public ResponseFunctionCallArgumentsDoneEvent.Builder type(ResponseStreamEventType type) {
      this.instance.type = type;
      return this;
    }
    public ResponseFunctionCallArgumentsDoneEvent.Builder arguments(String arguments) {
      this.instance.arguments = arguments;
      return this;
    }
    public ResponseFunctionCallArgumentsDoneEvent.Builder itemId(String itemId) {
      this.instance.itemId = itemId;
      return this;
    }
    public ResponseFunctionCallArgumentsDoneEvent.Builder outputIndex(Long outputIndex) {
      this.instance.outputIndex = outputIndex;
      return this;
    }
    public ResponseFunctionCallArgumentsDoneEvent.Builder sequenceNumber(Long sequenceNumber) {
      this.instance.sequenceNumber = sequenceNumber;
      return this;
    }


    /**
    * returns a built ResponseFunctionCallArgumentsDoneEvent instance.
    *
    * The builder is not reusable.
    */
    public ResponseFunctionCallArgumentsDoneEvent build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ResponseFunctionCallArgumentsDoneEvent.Builder builder() {
    return new ResponseFunctionCallArgumentsDoneEvent.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ResponseFunctionCallArgumentsDoneEvent.Builder toBuilder() {
    return new ResponseFunctionCallArgumentsDoneEvent.Builder()
      .type(getType())
      .arguments(getArguments())
      .itemId(getItemId())
      .outputIndex(getOutputIndex())
      .sequenceNumber(getSequenceNumber());
  }


}

