// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Responses API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.responses;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * ResponseImageProcessAction
 */
@JsonPropertyOrder({
  ResponseImageProcessAction.JSON_PROPERTY_TYPE,
  ResponseImageProcessAction.JSON_PROPERTY_RESULT_IMAGE_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ResponseImageProcessAction {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private String type;

  public static final String JSON_PROPERTY_RESULT_IMAGE_URL = "result_image_url";
  @javax.annotation.Nullable
  private String resultImageUrl;

  public ResponseImageProcessAction() {
  }

  public ResponseImageProcessAction type(@javax.annotation.Nonnull String type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull String type) {
    this.type = type;
  }

  public ResponseImageProcessAction resultImageUrl(@javax.annotation.Nullable String resultImageUrl) {
    
    this.resultImageUrl = resultImageUrl;
    return this;
  }

  /**
   * Get resultImageUrl
   * @return resultImageUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESULT_IMAGE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResultImageUrl() {
    return resultImageUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_RESULT_IMAGE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResultImageUrl(@javax.annotation.Nullable String resultImageUrl) {
    this.resultImageUrl = resultImageUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseImageProcessAction responseImageProcessAction = (ResponseImageProcessAction) o;
    return Objects.equals(this.type, responseImageProcessAction.type) &&
        Objects.equals(this.resultImageUrl, responseImageProcessAction.resultImageUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, resultImageUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseImageProcessAction {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    resultImageUrl: ").append(toIndentedString(resultImageUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ResponseImageProcessAction instance;

    public Builder() {
      this(new ResponseImageProcessAction());
    }

    protected Builder(ResponseImageProcessAction instance) {
      this.instance = instance;
    }

    public ResponseImageProcessAction.Builder type(String type) {
      this.instance.type = type;
      return this;
    }
    public ResponseImageProcessAction.Builder resultImageUrl(String resultImageUrl) {
      this.instance.resultImageUrl = resultImageUrl;
      return this;
    }


    /**
    * returns a built ResponseImageProcessAction instance.
    *
    * The builder is not reusable.
    */
    public ResponseImageProcessAction build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ResponseImageProcessAction.Builder builder() {
    return new ResponseImageProcessAction.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ResponseImageProcessAction.Builder toBuilder() {
    return new ResponseImageProcessAction.Builder()
      .type(getType())
      .resultImageUrl(getResultImageUrl());
  }


}

