// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Responses API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.responses;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * ResponseIncompleteEvent
 */
@JsonPropertyOrder({
  ResponseIncompleteEvent.JSON_PROPERTY_TYPE,
  ResponseIncompleteEvent.JSON_PROPERTY_RESPONSE,
  ResponseIncompleteEvent.JSON_PROPERTY_SEQUENCE_NUMBER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ResponseIncompleteEvent implements ResponseStreamEvent {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private ResponseStreamEventType type = ResponseStreamEventType.RESPONSE_INCOMPLETE;

  public static final String JSON_PROPERTY_RESPONSE = "response";
  @javax.annotation.Nonnull
  private Response response;

  public static final String JSON_PROPERTY_SEQUENCE_NUMBER = "sequence_number";
  @javax.annotation.Nonnull
  private Long sequenceNumber;

  public ResponseIncompleteEvent() {
  }

  public ResponseIncompleteEvent type(@javax.annotation.Nonnull ResponseStreamEventType type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ResponseStreamEventType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull ResponseStreamEventType type) {
    this.type = type;
  }

  public ResponseIncompleteEvent response(@javax.annotation.Nonnull Response response) {

    this.response = response;
    return this;
  }

  /**
   * The response that was incomplete.
   * @return response
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RESPONSE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Response getResponse() {
    return response;
  }


  @JsonProperty(value = JSON_PROPERTY_RESPONSE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponse(@javax.annotation.Nonnull Response response) {
    this.response = response;
  }

  public ResponseIncompleteEvent sequenceNumber(@javax.annotation.Nonnull Long sequenceNumber) {

    this.sequenceNumber = sequenceNumber;
    return this;
  }

  /**
   * The sequence number of this event.
   * @return sequenceNumber
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getSequenceNumber() {
    return sequenceNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSequenceNumber(@javax.annotation.Nonnull Long sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseIncompleteEvent responseIncompleteEvent = (ResponseIncompleteEvent) o;
    return Objects.equals(this.type, responseIncompleteEvent.type) &&
        Objects.equals(this.response, responseIncompleteEvent.response) &&
        Objects.equals(this.sequenceNumber, responseIncompleteEvent.sequenceNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, response, sequenceNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseIncompleteEvent {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    sequenceNumber: ").append(toIndentedString(sequenceNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ResponseIncompleteEvent instance;

    public Builder() {
      this(new ResponseIncompleteEvent());
    }

    protected Builder(ResponseIncompleteEvent instance) {
      this.instance = instance;
    }

    public ResponseIncompleteEvent.Builder type(ResponseStreamEventType type) {
      this.instance.type = type;
      return this;
    }
    public ResponseIncompleteEvent.Builder response(Response response) {
      this.instance.response = response;
      return this;
    }
    public ResponseIncompleteEvent.Builder sequenceNumber(Long sequenceNumber) {
      this.instance.sequenceNumber = sequenceNumber;
      return this;
    }


    /**
    * returns a built ResponseIncompleteEvent instance.
    *
    * The builder is not reusable.
    */
    public ResponseIncompleteEvent build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ResponseIncompleteEvent.Builder builder() {
    return new ResponseIncompleteEvent.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ResponseIncompleteEvent.Builder toBuilder() {
    return new ResponseIncompleteEvent.Builder()
      .type(getType())
      .response(getResponse())
      .sequenceNumber(getSequenceNumber());
  }


}
