// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Responses API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.responses;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * ResponseDoubaoAppCallSearchInProgressEvent
 */
@JsonPropertyOrder({
  ResponseDoubaoAppCallSearchInProgressEvent.JSON_PROPERTY_TYPE,
  ResponseDoubaoAppCallSearchInProgressEvent.JSON_PROPERTY_ITEM_ID,
  ResponseDoubaoAppCallSearchInProgressEvent.JSON_PROPERTY_OUTPUT_INDEX,
  ResponseDoubaoAppCallSearchInProgressEvent.JSON_PROPERTY_BLOCK_INDEX,
  ResponseDoubaoAppCallSearchInProgressEvent.JSON_PROPERTY_SEQUENCE_NUMBER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ResponseDoubaoAppCallSearchInProgressEvent implements ResponseStreamEvent {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private ResponseStreamEventType type = ResponseStreamEventType.RESPONSE_DOUBAO_APP_CALL_SEARCH_IN_PROGRESS;

  public static final String JSON_PROPERTY_ITEM_ID = "item_id";
  @javax.annotation.Nonnull
  private String itemId;

  public static final String JSON_PROPERTY_OUTPUT_INDEX = "output_index";
  @javax.annotation.Nonnull
  private Long outputIndex;

  public static final String JSON_PROPERTY_BLOCK_INDEX = "block_index";
  @javax.annotation.Nullable
  private Long blockIndex;

  public static final String JSON_PROPERTY_SEQUENCE_NUMBER = "sequence_number";
  @javax.annotation.Nonnull
  private Long sequenceNumber;

  public ResponseDoubaoAppCallSearchInProgressEvent() {
  }

  public ResponseDoubaoAppCallSearchInProgressEvent type(@javax.annotation.Nonnull ResponseStreamEventType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ResponseStreamEventType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull ResponseStreamEventType type) {
    this.type = type;
  }

  public ResponseDoubaoAppCallSearchInProgressEvent itemId(@javax.annotation.Nonnull String itemId) {
    
    this.itemId = itemId;
    return this;
  }

  /**
   * Get itemId
   * @return itemId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ITEM_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getItemId() {
    return itemId;
  }


  @JsonProperty(value = JSON_PROPERTY_ITEM_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setItemId(@javax.annotation.Nonnull String itemId) {
    this.itemId = itemId;
  }

  public ResponseDoubaoAppCallSearchInProgressEvent outputIndex(@javax.annotation.Nonnull Long outputIndex) {
    
    this.outputIndex = outputIndex;
    return this;
  }

  /**
   * Get outputIndex
   * @return outputIndex
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTPUT_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getOutputIndex() {
    return outputIndex;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTPUT_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutputIndex(@javax.annotation.Nonnull Long outputIndex) {
    this.outputIndex = outputIndex;
  }

  public ResponseDoubaoAppCallSearchInProgressEvent blockIndex(@javax.annotation.Nullable Long blockIndex) {
    
    this.blockIndex = blockIndex;
    return this;
  }

  /**
   * Get blockIndex
   * @return blockIndex
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BLOCK_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getBlockIndex() {
    return blockIndex;
  }


  @JsonProperty(value = JSON_PROPERTY_BLOCK_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBlockIndex(@javax.annotation.Nullable Long blockIndex) {
    this.blockIndex = blockIndex;
  }

  public ResponseDoubaoAppCallSearchInProgressEvent sequenceNumber(@javax.annotation.Nonnull Long sequenceNumber) {
    
    this.sequenceNumber = sequenceNumber;
    return this;
  }

  /**
   * Get sequenceNumber
   * @return sequenceNumber
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getSequenceNumber() {
    return sequenceNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSequenceNumber(@javax.annotation.Nonnull Long sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseDoubaoAppCallSearchInProgressEvent responseDoubaoAppCallSearchInProgressEvent = (ResponseDoubaoAppCallSearchInProgressEvent) o;
    return Objects.equals(this.type, responseDoubaoAppCallSearchInProgressEvent.type) &&
        Objects.equals(this.itemId, responseDoubaoAppCallSearchInProgressEvent.itemId) &&
        Objects.equals(this.outputIndex, responseDoubaoAppCallSearchInProgressEvent.outputIndex) &&
        Objects.equals(this.blockIndex, responseDoubaoAppCallSearchInProgressEvent.blockIndex) &&
        Objects.equals(this.sequenceNumber, responseDoubaoAppCallSearchInProgressEvent.sequenceNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, itemId, outputIndex, blockIndex, sequenceNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseDoubaoAppCallSearchInProgressEvent {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    outputIndex: ").append(toIndentedString(outputIndex)).append("\n");
    sb.append("    blockIndex: ").append(toIndentedString(blockIndex)).append("\n");
    sb.append("    sequenceNumber: ").append(toIndentedString(sequenceNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ResponseDoubaoAppCallSearchInProgressEvent instance;

    public Builder() {
      this(new ResponseDoubaoAppCallSearchInProgressEvent());
    }

    protected Builder(ResponseDoubaoAppCallSearchInProgressEvent instance) {
      this.instance = instance;
    }

    public ResponseDoubaoAppCallSearchInProgressEvent.Builder type(ResponseStreamEventType type) {
      this.instance.type = type;
      return this;
    }
    public ResponseDoubaoAppCallSearchInProgressEvent.Builder itemId(String itemId) {
      this.instance.itemId = itemId;
      return this;
    }
    public ResponseDoubaoAppCallSearchInProgressEvent.Builder outputIndex(Long outputIndex) {
      this.instance.outputIndex = outputIndex;
      return this;
    }
    public ResponseDoubaoAppCallSearchInProgressEvent.Builder blockIndex(Long blockIndex) {
      this.instance.blockIndex = blockIndex;
      return this;
    }
    public ResponseDoubaoAppCallSearchInProgressEvent.Builder sequenceNumber(Long sequenceNumber) {
      this.instance.sequenceNumber = sequenceNumber;
      return this;
    }


    /**
    * returns a built ResponseDoubaoAppCallSearchInProgressEvent instance.
    *
    * The builder is not reusable.
    */
    public ResponseDoubaoAppCallSearchInProgressEvent build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ResponseDoubaoAppCallSearchInProgressEvent.Builder builder() {
    return new ResponseDoubaoAppCallSearchInProgressEvent.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ResponseDoubaoAppCallSearchInProgressEvent.Builder toBuilder() {
    return new ResponseDoubaoAppCallSearchInProgressEvent.Builder()
      .type(getType())
      .itemId(getItemId())
      .outputIndex(getOutputIndex())
      .blockIndex(getBlockIndex())
      .sequenceNumber(getSequenceNumber());
  }


}

