// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Responses API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.responses;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ResponseDoubaoAppCallReasoningSearchCompletedEvent
 */
@JsonPropertyOrder({
  ResponseDoubaoAppCallReasoningSearchCompletedEvent.JSON_PROPERTY_TYPE,
  ResponseDoubaoAppCallReasoningSearchCompletedEvent.JSON_PROPERTY_ITEM_ID,
  ResponseDoubaoAppCallReasoningSearchCompletedEvent.JSON_PROPERTY_OUTPUT_INDEX,
  ResponseDoubaoAppCallReasoningSearchCompletedEvent.JSON_PROPERTY_BLOCK_INDEX,
  ResponseDoubaoAppCallReasoningSearchCompletedEvent.JSON_PROPERTY_SUMMARY,
  ResponseDoubaoAppCallReasoningSearchCompletedEvent.JSON_PROPERTY_QUERIES,
  ResponseDoubaoAppCallReasoningSearchCompletedEvent.JSON_PROPERTY_RESULTS,
  ResponseDoubaoAppCallReasoningSearchCompletedEvent.JSON_PROPERTY_SEQUENCE_NUMBER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ResponseDoubaoAppCallReasoningSearchCompletedEvent implements ResponseStreamEvent {
  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private ResponseStreamEventType type = ResponseStreamEventType.RESPONSE_DOUBAO_APP_CALL_REASONING_SEARCH_COMPLETED;

  public static final String JSON_PROPERTY_ITEM_ID = "item_id";
  @javax.annotation.Nonnull
  private String itemId;

  public static final String JSON_PROPERTY_OUTPUT_INDEX = "output_index";
  @javax.annotation.Nonnull
  private Long outputIndex;

  public static final String JSON_PROPERTY_BLOCK_INDEX = "block_index";
  @javax.annotation.Nullable
  private Long blockIndex;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @javax.annotation.Nullable
  private String summary;

  public static final String JSON_PROPERTY_QUERIES = "queries";
  @javax.annotation.Nonnull
  private List<String> queries;

  public static final String JSON_PROPERTY_RESULTS = "results";
  @javax.annotation.Nonnull
  private List<DoubaoAppSearchResult> results;

  public static final String JSON_PROPERTY_SEQUENCE_NUMBER = "sequence_number";
  @javax.annotation.Nonnull
  private Long sequenceNumber;

  public ResponseDoubaoAppCallReasoningSearchCompletedEvent() {
  }

  public ResponseDoubaoAppCallReasoningSearchCompletedEvent type(@javax.annotation.Nonnull ResponseStreamEventType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ResponseStreamEventType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull ResponseStreamEventType type) {
    this.type = type;
  }

  public ResponseDoubaoAppCallReasoningSearchCompletedEvent itemId(@javax.annotation.Nonnull String itemId) {
    
    this.itemId = itemId;
    return this;
  }

  /**
   * Get itemId
   * @return itemId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ITEM_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getItemId() {
    return itemId;
  }


  @JsonProperty(value = JSON_PROPERTY_ITEM_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setItemId(@javax.annotation.Nonnull String itemId) {
    this.itemId = itemId;
  }

  public ResponseDoubaoAppCallReasoningSearchCompletedEvent outputIndex(@javax.annotation.Nonnull Long outputIndex) {
    
    this.outputIndex = outputIndex;
    return this;
  }

  /**
   * Get outputIndex
   * @return outputIndex
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTPUT_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getOutputIndex() {
    return outputIndex;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTPUT_INDEX, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutputIndex(@javax.annotation.Nonnull Long outputIndex) {
    this.outputIndex = outputIndex;
  }

  public ResponseDoubaoAppCallReasoningSearchCompletedEvent blockIndex(@javax.annotation.Nullable Long blockIndex) {
    
    this.blockIndex = blockIndex;
    return this;
  }

  /**
   * Get blockIndex
   * @return blockIndex
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BLOCK_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getBlockIndex() {
    return blockIndex;
  }


  @JsonProperty(value = JSON_PROPERTY_BLOCK_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBlockIndex(@javax.annotation.Nullable Long blockIndex) {
    this.blockIndex = blockIndex;
  }

  public ResponseDoubaoAppCallReasoningSearchCompletedEvent summary(@javax.annotation.Nullable String summary) {
    
    this.summary = summary;
    return this;
  }

  /**
   * Get summary
   * @return summary
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSummary() {
    return summary;
  }


  @JsonProperty(value = JSON_PROPERTY_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSummary(@javax.annotation.Nullable String summary) {
    this.summary = summary;
  }

  public ResponseDoubaoAppCallReasoningSearchCompletedEvent queries(@javax.annotation.Nonnull List<String> queries) {
    
    this.queries = queries;
    return this;
  }

  public ResponseDoubaoAppCallReasoningSearchCompletedEvent addQueriesItem(String queriesItem) {
    if (this.queries == null) {
      this.queries = new ArrayList<>();
    }
    this.queries.add(queriesItem);
    return this;
  }

  /**
   * Get queries
   * @return queries
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUERIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getQueries() {
    return queries;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQueries(@javax.annotation.Nonnull List<String> queries) {
    this.queries = queries;
  }

  public ResponseDoubaoAppCallReasoningSearchCompletedEvent results(@javax.annotation.Nonnull List<DoubaoAppSearchResult> results) {
    
    this.results = results;
    return this;
  }

  public ResponseDoubaoAppCallReasoningSearchCompletedEvent addResultsItem(DoubaoAppSearchResult resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<>();
    }
    this.results.add(resultsItem);
    return this;
  }

  /**
   * Get results
   * @return results
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RESULTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<DoubaoAppSearchResult> getResults() {
    return results;
  }


  @JsonProperty(value = JSON_PROPERTY_RESULTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResults(@javax.annotation.Nonnull List<DoubaoAppSearchResult> results) {
    this.results = results;
  }

  public ResponseDoubaoAppCallReasoningSearchCompletedEvent sequenceNumber(@javax.annotation.Nonnull Long sequenceNumber) {
    
    this.sequenceNumber = sequenceNumber;
    return this;
  }

  /**
   * Get sequenceNumber
   * @return sequenceNumber
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getSequenceNumber() {
    return sequenceNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_SEQUENCE_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSequenceNumber(@javax.annotation.Nonnull Long sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseDoubaoAppCallReasoningSearchCompletedEvent responseDoubaoAppCallReasoningSearchCompletedEvent = (ResponseDoubaoAppCallReasoningSearchCompletedEvent) o;
    return Objects.equals(this.type, responseDoubaoAppCallReasoningSearchCompletedEvent.type) &&
        Objects.equals(this.itemId, responseDoubaoAppCallReasoningSearchCompletedEvent.itemId) &&
        Objects.equals(this.outputIndex, responseDoubaoAppCallReasoningSearchCompletedEvent.outputIndex) &&
        Objects.equals(this.blockIndex, responseDoubaoAppCallReasoningSearchCompletedEvent.blockIndex) &&
        Objects.equals(this.summary, responseDoubaoAppCallReasoningSearchCompletedEvent.summary) &&
        Objects.equals(this.queries, responseDoubaoAppCallReasoningSearchCompletedEvent.queries) &&
        Objects.equals(this.results, responseDoubaoAppCallReasoningSearchCompletedEvent.results) &&
        Objects.equals(this.sequenceNumber, responseDoubaoAppCallReasoningSearchCompletedEvent.sequenceNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, itemId, outputIndex, blockIndex, summary, queries, results, sequenceNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseDoubaoAppCallReasoningSearchCompletedEvent {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    outputIndex: ").append(toIndentedString(outputIndex)).append("\n");
    sb.append("    blockIndex: ").append(toIndentedString(blockIndex)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    queries: ").append(toIndentedString(queries)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    sequenceNumber: ").append(toIndentedString(sequenceNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ResponseDoubaoAppCallReasoningSearchCompletedEvent instance;

    public Builder() {
      this(new ResponseDoubaoAppCallReasoningSearchCompletedEvent());
    }

    protected Builder(ResponseDoubaoAppCallReasoningSearchCompletedEvent instance) {
      this.instance = instance;
    }

    public ResponseDoubaoAppCallReasoningSearchCompletedEvent.Builder type(ResponseStreamEventType type) {
      this.instance.type = type;
      return this;
    }
    public ResponseDoubaoAppCallReasoningSearchCompletedEvent.Builder itemId(String itemId) {
      this.instance.itemId = itemId;
      return this;
    }
    public ResponseDoubaoAppCallReasoningSearchCompletedEvent.Builder outputIndex(Long outputIndex) {
      this.instance.outputIndex = outputIndex;
      return this;
    }
    public ResponseDoubaoAppCallReasoningSearchCompletedEvent.Builder blockIndex(Long blockIndex) {
      this.instance.blockIndex = blockIndex;
      return this;
    }
    public ResponseDoubaoAppCallReasoningSearchCompletedEvent.Builder summary(String summary) {
      this.instance.summary = summary;
      return this;
    }
    public ResponseDoubaoAppCallReasoningSearchCompletedEvent.Builder queries(List<String> queries) {
      this.instance.queries = queries;
      return this;
    }
    public ResponseDoubaoAppCallReasoningSearchCompletedEvent.Builder results(List<DoubaoAppSearchResult> results) {
      this.instance.results = results;
      return this;
    }
    public ResponseDoubaoAppCallReasoningSearchCompletedEvent.Builder sequenceNumber(Long sequenceNumber) {
      this.instance.sequenceNumber = sequenceNumber;
      return this;
    }


    /**
    * returns a built ResponseDoubaoAppCallReasoningSearchCompletedEvent instance.
    *
    * The builder is not reusable.
    */
    public ResponseDoubaoAppCallReasoningSearchCompletedEvent build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ResponseDoubaoAppCallReasoningSearchCompletedEvent.Builder builder() {
    return new ResponseDoubaoAppCallReasoningSearchCompletedEvent.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ResponseDoubaoAppCallReasoningSearchCompletedEvent.Builder toBuilder() {
    return new ResponseDoubaoAppCallReasoningSearchCompletedEvent.Builder()
      .type(getType())
      .itemId(getItemId())
      .outputIndex(getOutputIndex())
      .blockIndex(getBlockIndex())
      .summary(getSummary())
      .queries(getQueries())
      .results(getResults())
      .sequenceNumber(getSequenceNumber());
  }


}

