// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Responses API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.responses;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * ToolUsageDetails
 */
@JsonPropertyOrder({
  ToolUsageDetails.JSON_PROPERTY_WEB_SEARCH,
  ToolUsageDetails.JSON_PROPERTY_MCP,
  ToolUsageDetails.JSON_PROPERTY_KNOWLEDGE_SEARCH,
  ToolUsageDetails.JSON_PROPERTY_DOUBAO_APP
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class ToolUsageDetails {
  public static final String JSON_PROPERTY_WEB_SEARCH = "web_search";
  @javax.annotation.Nullable
  private Map<String, Object> webSearch;

  public static final String JSON_PROPERTY_MCP = "mcp";
  @javax.annotation.Nullable
  private Map<String, Object> mcp;

  public static final String JSON_PROPERTY_KNOWLEDGE_SEARCH = "knowledge_search";
  @javax.annotation.Nullable
  private Map<String, Object> knowledgeSearch;

  public static final String JSON_PROPERTY_DOUBAO_APP = "doubao_app";
  @javax.annotation.Nullable
  private Map<String, Object> doubaoApp;

  public ToolUsageDetails() {
  }

  public ToolUsageDetails webSearch(@javax.annotation.Nullable Map<String, Object> webSearch) {

    this.webSearch = webSearch;
    return this;
  }

  public ToolUsageDetails putWebSearchItem(String key, Object webSearchItem) {
    if (this.webSearch == null) {
      this.webSearch = new HashMap<>();
    }
    this.webSearch.put(key, webSearchItem);
    return this;
  }

  /**
   * The usage of web search tools.
   * @return webSearch
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEB_SEARCH, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.NON_EMPTY)

  public Map<String, Object> getWebSearch() {
    return webSearch;
  }


  @JsonProperty(value = JSON_PROPERTY_WEB_SEARCH, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.NON_EMPTY)
  public void setWebSearch(@javax.annotation.Nullable Map<String, Object> webSearch) {
    this.webSearch = webSearch;
  }

  public ToolUsageDetails mcp(@javax.annotation.Nullable Map<String, Object> mcp) {

    this.mcp = mcp;
    return this;
  }

  public ToolUsageDetails putMcpItem(String key, Object mcpItem) {
    if (this.mcp == null) {
      this.mcp = new HashMap<>();
    }
    this.mcp.put(key, mcpItem);
    return this;
  }

  /**
   * The usage of MCP tools.
   * @return mcp
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MCP, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.NON_EMPTY)

  public Map<String, Object> getMcp() {
    return mcp;
  }


  @JsonProperty(value = JSON_PROPERTY_MCP, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.NON_EMPTY)
  public void setMcp(@javax.annotation.Nullable Map<String, Object> mcp) {
    this.mcp = mcp;
  }

  public ToolUsageDetails knowledgeSearch(@javax.annotation.Nullable Map<String, Object> knowledgeSearch) {

    this.knowledgeSearch = knowledgeSearch;
    return this;
  }

  public ToolUsageDetails putKnowledgeSearchItem(String key, Object knowledgeSearchItem) {
    if (this.knowledgeSearch == null) {
      this.knowledgeSearch = new HashMap<>();
    }
    this.knowledgeSearch.put(key, knowledgeSearchItem);
    return this;
  }

  /**
   * The usage of knowledge search tools.
   * @return knowledgeSearch
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_KNOWLEDGE_SEARCH, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.NON_EMPTY)

  public Map<String, Object> getKnowledgeSearch() {
    return knowledgeSearch;
  }


  @JsonProperty(value = JSON_PROPERTY_KNOWLEDGE_SEARCH, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.NON_EMPTY)
  public void setKnowledgeSearch(@javax.annotation.Nullable Map<String, Object> knowledgeSearch) {
    this.knowledgeSearch = knowledgeSearch;
  }

  public ToolUsageDetails doubaoApp(@javax.annotation.Nullable Map<String, Object> doubaoApp) {

    this.doubaoApp = doubaoApp;
    return this;
  }

  public ToolUsageDetails putDoubaoAppItem(String key, Object doubaoAppItem) {
    if (this.doubaoApp == null) {
      this.doubaoApp = new HashMap<>();
    }
    this.doubaoApp.put(key, doubaoAppItem);
    return this;
  }

  /**
   * The usage of doubao app tools.
   * @return doubaoApp
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DOUBAO_APP, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.NON_EMPTY)

  public Map<String, Object> getDoubaoApp() {
    return doubaoApp;
  }


  @JsonProperty(value = JSON_PROPERTY_DOUBAO_APP, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.NON_EMPTY)
  public void setDoubaoApp(@javax.annotation.Nullable Map<String, Object> doubaoApp) {
    this.doubaoApp = doubaoApp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ToolUsageDetails toolUsageDetails = (ToolUsageDetails) o;
    return Objects.equals(this.webSearch, toolUsageDetails.webSearch) &&
        Objects.equals(this.mcp, toolUsageDetails.mcp) &&
        Objects.equals(this.knowledgeSearch, toolUsageDetails.knowledgeSearch) &&
        Objects.equals(this.doubaoApp, toolUsageDetails.doubaoApp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(webSearch, mcp, knowledgeSearch, doubaoApp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ToolUsageDetails {\n");
    sb.append("    webSearch: ").append(toIndentedString(webSearch)).append("\n");
    sb.append("    mcp: ").append(toIndentedString(mcp)).append("\n");
    sb.append("    knowledgeSearch: ").append(toIndentedString(knowledgeSearch)).append("\n");
    sb.append("    doubaoApp: ").append(toIndentedString(doubaoApp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private ToolUsageDetails instance;

    public Builder() {
      this(new ToolUsageDetails());
    }

    protected Builder(ToolUsageDetails instance) {
      this.instance = instance;
    }

    public ToolUsageDetails.Builder webSearch(Map<String, Object> webSearch) {
      this.instance.webSearch = webSearch;
      return this;
    }
    public ToolUsageDetails.Builder mcp(Map<String, Object> mcp) {
      this.instance.mcp = mcp;
      return this;
    }
    public ToolUsageDetails.Builder knowledgeSearch(Map<String, Object> knowledgeSearch) {
      this.instance.knowledgeSearch = knowledgeSearch;
      return this;
    }
    public ToolUsageDetails.Builder doubaoApp(Map<String, Object> doubaoApp) {
      this.instance.doubaoApp = doubaoApp;
      return this;
    }


    /**
    * returns a built ToolUsageDetails instance.
    *
    * The builder is not reusable.
    */
    public ToolUsageDetails build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ToolUsageDetails.Builder builder() {
    return new ToolUsageDetails.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ToolUsageDetails.Builder toBuilder() {
    return new ToolUsageDetails.Builder()
      .webSearch(getWebSearch())
      .mcp(getMcp())
      .knowledgeSearch(getKnowledgeSearch())
      .doubaoApp(getDoubaoApp());
  }


}
