// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Responses API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.responses;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * TranscriptionPart
 */
@JsonPropertyOrder({
  TranscriptionPart.JSON_PROPERTY_TYPE,
  TranscriptionPart.JSON_PROPERTY_TEXT,
  TranscriptionPart.JSON_PROPERTY_CHUNKS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class TranscriptionPart {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    TRANSCRIPTION_TEXT(String.valueOf("transcription_text"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equalsIgnoreCase(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_TEXT = "text";
  @javax.annotation.Nullable
  private String text;

  public static final String JSON_PROPERTY_CHUNKS = "chunks";
  @javax.annotation.Nullable
  private List<AudioChunk> chunks;

  public TranscriptionPart() {
  }

  public TranscriptionPart type(@javax.annotation.Nonnull TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public TranscriptionPart text(@javax.annotation.Nullable String text) {

    this.text = text;
    return this;
  }

  /**
   * Get text
   * @return text
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getText() {
    return text;
  }


  @JsonProperty(value = JSON_PROPERTY_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setText(@javax.annotation.Nullable String text) {
    this.text = text;
  }

  public TranscriptionPart chunks(@javax.annotation.Nullable List<AudioChunk> chunks) {

    this.chunks = chunks;
    return this;
  }

  public TranscriptionPart addChunksItem(AudioChunk chunksItem) {
    if (this.chunks == null) {
      this.chunks = new ArrayList<>();
    }
    this.chunks.add(chunksItem);
    return this;
  }

  /**
   * Get chunks
   * @return chunks
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHUNKS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)

  public List<AudioChunk> getChunks() {
    return chunks;
  }


  @JsonProperty(value = JSON_PROPERTY_CHUNKS, required = false)
  @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
  public void setChunks(@javax.annotation.Nullable List<AudioChunk> chunks) {
    this.chunks = chunks;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranscriptionPart transcriptionPart = (TranscriptionPart) o;
    return Objects.equals(this.type, transcriptionPart.type) &&
        Objects.equals(this.text, transcriptionPart.text) &&
        Objects.equals(this.chunks, transcriptionPart.chunks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, text, chunks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranscriptionPart {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    chunks: ").append(toIndentedString(chunks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private TranscriptionPart instance;

    public Builder() {
      this(new TranscriptionPart());
    }

    protected Builder(TranscriptionPart instance) {
      this.instance = instance;
    }

    public TranscriptionPart.Builder type(TypeEnum type) {
      this.instance.type = type;
      return this;
    }
    public TranscriptionPart.Builder text(String text) {
      this.instance.text = text;
      return this;
    }
    public TranscriptionPart.Builder chunks(List<AudioChunk> chunks) {
      this.instance.chunks = chunks;
      return this;
    }


    /**
    * returns a built TranscriptionPart instance.
    *
    * The builder is not reusable.
    */
    public TranscriptionPart build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static TranscriptionPart.Builder builder() {
    return new TranscriptionPart.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public TranscriptionPart.Builder toBuilder() {
    return new TranscriptionPart.Builder()
      .type(getType())
      .text(getText())
      .chunks(getChunks());
  }


}
