// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark File API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.file;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/**
 * FileListRequest
 */
@JsonPropertyOrder({
  FileListRequest.JSON_PROPERTY_PURPOSE,
  FileListRequest.JSON_PROPERTY_AFTER,
  FileListRequest.JSON_PROPERTY_LIMIT,
  FileListRequest.JSON_PROPERTY_ORDER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class FileListRequest {
  public static final String JSON_PROPERTY_PURPOSE = "purpose";
  @javax.annotation.Nullable
  private Purpose purpose;

  public static final String JSON_PROPERTY_AFTER = "after";
  @javax.annotation.Nullable
  private String after;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @javax.annotation.Nullable
  private Long limit;

  public static final String JSON_PROPERTY_ORDER = "order";
  @javax.annotation.Nullable
  private Order order;

  public FileListRequest() {
  }

  public FileListRequest purpose(@javax.annotation.Nullable Purpose purpose) {
    
    this.purpose = purpose;
    return this;
  }

  /**
   * Filter results to a single purpose.
   * @return purpose
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PURPOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Purpose getPurpose() {
    return purpose;
  }


  @JsonProperty(value = JSON_PROPERTY_PURPOSE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPurpose(@javax.annotation.Nullable Purpose purpose) {
    this.purpose = purpose;
  }

  public FileListRequest after(@javax.annotation.Nullable String after) {
    
    this.after = after;
    return this;
  }

  /**
   * Cursor (file id) for pagination — return items after this id.
   * @return after
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AFTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAfter() {
    return after;
  }


  @JsonProperty(value = JSON_PROPERTY_AFTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAfter(@javax.annotation.Nullable String after) {
    this.after = after;
  }

  public FileListRequest limit(@javax.annotation.Nullable Long limit) {
    
    this.limit = limit;
    return this;
  }

  /**
   * Maximum number of items to return. Server-defined default and ceiling.
   * @return limit
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLimit() {
    return limit;
  }


  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLimit(@javax.annotation.Nullable Long limit) {
    this.limit = limit;
  }

  public FileListRequest order(@javax.annotation.Nullable Order order) {
    
    this.order = order;
    return this;
  }

  /**
   * Sort order by &#x60;created_at&#x60;.
   * @return order
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Order getOrder() {
    return order;
  }


  @JsonProperty(value = JSON_PROPERTY_ORDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrder(@javax.annotation.Nullable Order order) {
    this.order = order;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileListRequest fileListRequest = (FileListRequest) o;
    return Objects.equals(this.purpose, fileListRequest.purpose) &&
        Objects.equals(this.after, fileListRequest.after) &&
        Objects.equals(this.limit, fileListRequest.limit) &&
        Objects.equals(this.order, fileListRequest.order);
  }

  @Override
  public int hashCode() {
    return Objects.hash(purpose, after, limit, order);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileListRequest {\n");
    sb.append("    purpose: ").append(toIndentedString(purpose)).append("\n");
    sb.append("    after: ").append(toIndentedString(after)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private FileListRequest instance;

    public Builder() {
      this(new FileListRequest());
    }

    protected Builder(FileListRequest instance) {
      this.instance = instance;
    }

    public FileListRequest.Builder purpose(Purpose purpose) {
      this.instance.purpose = purpose;
      return this;
    }
    public FileListRequest.Builder after(String after) {
      this.instance.after = after;
      return this;
    }
    public FileListRequest.Builder limit(Long limit) {
      this.instance.limit = limit;
      return this;
    }
    public FileListRequest.Builder order(Order order) {
      this.instance.order = order;
      return this;
    }


    /**
    * returns a built FileListRequest instance.
    *
    * The builder is not reusable.
    */
    public FileListRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static FileListRequest.Builder builder() {
    return new FileListRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public FileListRequest.Builder toBuilder() {
    return new FileListRequest.Builder()
      .purpose(getPurpose())
      .after(getAfter())
      .limit(getLimit())
      .order(getOrder());
  }


}

