// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Multimodal Embedding API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.multimodal_embedding;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;

/**
 * MultiModalEmbeddingResponse
 */
@JsonPropertyOrder({
  MultiModalEmbeddingResponse.JSON_PROPERTY_ID,
  MultiModalEmbeddingResponse.JSON_PROPERTY_MODEL,
  MultiModalEmbeddingResponse.JSON_PROPERTY_CREATED,
  MultiModalEmbeddingResponse.JSON_PROPERTY_OBJECT,
  MultiModalEmbeddingResponse.JSON_PROPERTY_DATA,
  MultiModalEmbeddingResponse.JSON_PROPERTY_USAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class MultiModalEmbeddingResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_MODEL = "model";
  @javax.annotation.Nonnull
  private String model;

  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nonnull
  private Long created;

  /**
   * The object type. Always &#x60;list&#x60;.
   */
  public enum ObjectEnum {
    LIST(String.valueOf("list"));

    private String value;

    ObjectEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ObjectEnum fromValue(String value) {
      for (ObjectEnum b : ObjectEnum.values()) {
        if (b.value.equalsIgnoreCase(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OBJECT = "object";
  @javax.annotation.Nonnull
  private ObjectEnum _object;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nonnull
  private EmbeddingDataItem data;

  public static final String JSON_PROPERTY_USAGE = "usage";
  @javax.annotation.Nonnull
  private EmbeddingUsage usage;

  public MultiModalEmbeddingResponse() {
  }

  public MultiModalEmbeddingResponse id(@javax.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * The unique identifier for the embedding response.
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }

  public MultiModalEmbeddingResponse model(@javax.annotation.Nonnull String model) {
    
    this.model = model;
    return this;
  }

  /**
   * The model that produced the embeddings.
   * @return model
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getModel() {
    return model;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModel(@javax.annotation.Nonnull String model) {
    this.model = model;
  }

  public MultiModalEmbeddingResponse created(@javax.annotation.Nonnull Long created) {
    
    this.created = created;
    return this;
  }

  /**
   * Unix timestamp (in seconds) of when the response was created.
   * @return created
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getCreated() {
    return created;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreated(@javax.annotation.Nonnull Long created) {
    this.created = created;
  }

  public MultiModalEmbeddingResponse _object(@javax.annotation.Nonnull ObjectEnum _object) {
    
    this._object = _object;
    return this;
  }

  /**
   * The object type. Always &#x60;list&#x60;.
   * @return _object
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ObjectEnum getObject() {
    return _object;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObject(@javax.annotation.Nonnull ObjectEnum _object) {
    this._object = _object;
  }

  public MultiModalEmbeddingResponse data(@javax.annotation.Nonnull EmbeddingDataItem data) {
    
    this.data = data;
    return this;
  }

  /**
   * The embedding result.
   * @return data
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EmbeddingDataItem getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(@javax.annotation.Nonnull EmbeddingDataItem data) {
    this.data = data;
  }

  public MultiModalEmbeddingResponse usage(@javax.annotation.Nonnull EmbeddingUsage usage) {
    
    this.usage = usage;
    return this;
  }

  /**
   * Token usage information.
   * @return usage
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EmbeddingUsage getUsage() {
    return usage;
  }


  @JsonProperty(value = JSON_PROPERTY_USAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsage(@javax.annotation.Nonnull EmbeddingUsage usage) {
    this.usage = usage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultiModalEmbeddingResponse multiModalEmbeddingResponse = (MultiModalEmbeddingResponse) o;
    return Objects.equals(this.id, multiModalEmbeddingResponse.id) &&
        Objects.equals(this.model, multiModalEmbeddingResponse.model) &&
        Objects.equals(this.created, multiModalEmbeddingResponse.created) &&
        Objects.equals(this._object, multiModalEmbeddingResponse._object) &&
        Objects.equals(this.data, multiModalEmbeddingResponse.data) &&
        Objects.equals(this.usage, multiModalEmbeddingResponse.usage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, model, created, _object, data, usage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultiModalEmbeddingResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private MultiModalEmbeddingResponse instance;

    public Builder() {
      this(new MultiModalEmbeddingResponse());
    }

    protected Builder(MultiModalEmbeddingResponse instance) {
      this.instance = instance;
    }

    public MultiModalEmbeddingResponse.Builder id(String id) {
      this.instance.id = id;
      return this;
    }
    public MultiModalEmbeddingResponse.Builder model(String model) {
      this.instance.model = model;
      return this;
    }
    public MultiModalEmbeddingResponse.Builder created(Long created) {
      this.instance.created = created;
      return this;
    }
    public MultiModalEmbeddingResponse.Builder _object(ObjectEnum _object) {
      this.instance._object = _object;
      return this;
    }
    public MultiModalEmbeddingResponse.Builder data(EmbeddingDataItem data) {
      this.instance.data = data;
      return this;
    }
    public MultiModalEmbeddingResponse.Builder usage(EmbeddingUsage usage) {
      this.instance.usage = usage;
      return this;
    }


    /**
    * returns a built MultiModalEmbeddingResponse instance.
    *
    * The builder is not reusable.
    */
    public MultiModalEmbeddingResponse build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static MultiModalEmbeddingResponse.Builder builder() {
    return new MultiModalEmbeddingResponse.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public MultiModalEmbeddingResponse.Builder toBuilder() {
    return new MultiModalEmbeddingResponse.Builder()
      .id(getId())
      .model(getModel())
      .created(getCreated())
      ._object(getObject())
      .data(getData())
      .usage(getUsage());
  }


}

