// Copyright (c) 2026 ByteDance Ltd. and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

/*
 * Ark Embedding API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.volcengine.ark.runtime.models.embedding;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EmbeddingResponse
 */
@JsonPropertyOrder({
  EmbeddingResponse.JSON_PROPERTY_ID,
  EmbeddingResponse.JSON_PROPERTY_OBJECT,
  EmbeddingResponse.JSON_PROPERTY_CREATED,
  EmbeddingResponse.JSON_PROPERTY_MODEL,
  EmbeddingResponse.JSON_PROPERTY_DATA,
  EmbeddingResponse.JSON_PROPERTY_USAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.21.0")
public class EmbeddingResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  /**
   * The object type. Always &#x60;list&#x60;.
   */
  public enum ObjectEnum {
    LIST(String.valueOf("list"));

    private String value;

    ObjectEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ObjectEnum fromValue(String value) {
      for (ObjectEnum b : ObjectEnum.values()) {
        if (b.value.equalsIgnoreCase(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OBJECT = "object";
  @javax.annotation.Nonnull
  private ObjectEnum _object;

  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nonnull
  private Long created;

  public static final String JSON_PROPERTY_MODEL = "model";
  @javax.annotation.Nonnull
  private String model;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nonnull
  private List<EmbeddingItem> data;

  public static final String JSON_PROPERTY_USAGE = "usage";
  @javax.annotation.Nonnull
  private EmbeddingUsage usage;

  public EmbeddingResponse() {
  }

  public EmbeddingResponse id(@javax.annotation.Nonnull String id) {
    
    this.id = id;
    return this;
  }

  /**
   * A unique identifier for the embedding response.
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }

  public EmbeddingResponse _object(@javax.annotation.Nonnull ObjectEnum _object) {
    
    this._object = _object;
    return this;
  }

  /**
   * The object type. Always &#x60;list&#x60;.
   * @return _object
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ObjectEnum getObject() {
    return _object;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObject(@javax.annotation.Nonnull ObjectEnum _object) {
    this._object = _object;
  }

  public EmbeddingResponse created(@javax.annotation.Nonnull Long created) {
    
    this.created = created;
    return this;
  }

  /**
   * Unix timestamp (in seconds) of when the response was created.
   * @return created
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getCreated() {
    return created;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreated(@javax.annotation.Nonnull Long created) {
    this.created = created;
  }

  public EmbeddingResponse model(@javax.annotation.Nonnull String model) {
    
    this.model = model;
    return this;
  }

  /**
   * The model that produced the embeddings.
   * @return model
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getModel() {
    return model;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModel(@javax.annotation.Nonnull String model) {
    this.model = model;
  }

  public EmbeddingResponse data(@javax.annotation.Nonnull List<EmbeddingItem> data) {
    
    this.data = data;
    return this;
  }

  public EmbeddingResponse addDataItem(EmbeddingItem dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * The list of embeddings, one per input.
   * @return data
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<EmbeddingItem> getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(@javax.annotation.Nonnull List<EmbeddingItem> data) {
    this.data = data;
  }

  public EmbeddingResponse usage(@javax.annotation.Nonnull EmbeddingUsage usage) {
    
    this.usage = usage;
    return this;
  }

  /**
   * Token usage information for the request.
   * @return usage
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EmbeddingUsage getUsage() {
    return usage;
  }


  @JsonProperty(value = JSON_PROPERTY_USAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsage(@javax.annotation.Nonnull EmbeddingUsage usage) {
    this.usage = usage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmbeddingResponse embeddingResponse = (EmbeddingResponse) o;
    return Objects.equals(this.id, embeddingResponse.id) &&
        Objects.equals(this._object, embeddingResponse._object) &&
        Objects.equals(this.created, embeddingResponse.created) &&
        Objects.equals(this.model, embeddingResponse.model) &&
        Objects.equals(this.data, embeddingResponse.data) &&
        Objects.equals(this.usage, embeddingResponse.usage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, _object, created, model, data, usage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmbeddingResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public static class Builder {

    private EmbeddingResponse instance;

    public Builder() {
      this(new EmbeddingResponse());
    }

    protected Builder(EmbeddingResponse instance) {
      this.instance = instance;
    }

    public EmbeddingResponse.Builder id(String id) {
      this.instance.id = id;
      return this;
    }
    public EmbeddingResponse.Builder _object(ObjectEnum _object) {
      this.instance._object = _object;
      return this;
    }
    public EmbeddingResponse.Builder created(Long created) {
      this.instance.created = created;
      return this;
    }
    public EmbeddingResponse.Builder model(String model) {
      this.instance.model = model;
      return this;
    }
    public EmbeddingResponse.Builder data(List<EmbeddingItem> data) {
      this.instance.data = data;
      return this;
    }
    public EmbeddingResponse.Builder usage(EmbeddingUsage usage) {
      this.instance.usage = usage;
      return this;
    }


    /**
    * returns a built EmbeddingResponse instance.
    *
    * The builder is not reusable.
    */
    public EmbeddingResponse build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static EmbeddingResponse.Builder builder() {
    return new EmbeddingResponse.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public EmbeddingResponse.Builder toBuilder() {
    return new EmbeddingResponse.Builder()
      .id(getId())
      ._object(getObject())
      .created(getCreated())
      .model(getModel())
      .data(getData())
      .usage(getUsage());
  }


}

